### ISSUE TITLE
Auth token not masked when using openshift.verbose()

### ISSUE THREAD

**Issue by rbkrabbe** [openshift/jenkins-client-plugin#101]
When running with `openshift.verbose()` enabled, token stored in jenkins as `os-developer` "OpenShift Token for OpenShift Client Plugin"-credentials is logged in plain text.

Example pipeline:
```
pipeline {
    agent any
    parameters {
        string(name: 'PROJECT', description: 'The project to describe resources from.')
    }
    stages {
        stage('Describe resources'){
            steps {
                script{
                    openshift.verbose()
                    openshift.withCluster( ) {
                        openshift.withProject( "${params.PROJECT}" ) {
                            openshift.doAs( 'os-developer' ) {
                                def selector = openshift.selector( 'all' )
                                selector.describe()
                            }
                        }
                    }
                    
                }
            }
        }
    }
}
```

The command is masked correctly:

> Command> oc --server=https://172.30.0.1:443 --namespace=testproj --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --loglevel=8 --token=XXXXX describe all

But the token is printed in clear text when http traffic is logged:

> ...
> StdErr> I1221 21:11:49.507844    1094 round_trippers.go:414] GET https://172.30.0.1:443/oapi/v1/namespaces/testproj/buildconfigs?includeUninitialized=true
> I1221 21:11:49.507949    1094 round_trippers.go:421] Request Headers:
> I1221 21:11:49.507955    1094 round_trippers.go:424]     Accept: application/json
> I1221 21:11:49.507960    1094 round_trippers.go:424]     User-Agent: oc/v1.8.1+0d5291c (linux/amd64) kubernetes/0d5291c
> I1221 21:11:49.507963    1094 round_trippers.go:424]     Authorization: Bearer hrHoOFyeANcnhVKsXgLYs2o5M4Q-INYf72bTek6Ou_A
> I1221 21:11:49.536286    1094 round_trippers.go:439] Response Status: 200 OK in 28 milliseconds
> I1221 21:11:49.536326    1094 round_trippers.go:442] Response Headers:
> I1221 21:11:49.536332    1094 round_trippers.go:445]     Content-Length: 797
> ...

**Comment by bparees** [comment]
there's nothing we can do about what the oc client chooses to log under verbose flags.  You will need to open an issue against openshift itself if you have concerns about what the oc client is logging.
