### ISSUE TITLE
Checkout scm behavior cannot be used in OpenShift editor for inline pipelines

### ISSUE THREAD

**Issue by eformat** [openshift/jenkins-client-plugin#116]
The nature of Declarative Jenkins pipelines has changed how checkout scm works. SCM checkout occurs in the agent/node declaration of your pipeline but only if (in Jenkins) the pipeline type is a “Multibranch Pipeline” or “Pipeline script from SCM”

So you get different behavior now from the same pipeline definition depending on whether it is defined as a:

"Pipeline script from SCM" in Jenkins when using "jenkinsFIlePath"
```
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
```
"Pipeline script" in Jenkins when using inline "jenkinsfile"
```
    jenkinsPipelineStrategy:
      jenkinsfile: |+
```
Calling a simple pipeline using the OpenShift Pipeline editor (i.e. a "Pipeline script" in Jenkins)
```
#!groovy
openshift.withCluster() {
    openshift.withProject() {
        echo "Using project: ${openshift.project()}"
        pipeline {
            agent {
                node {
                    // spin up a node.js slave pod to run this build on
                    label 'nodejs'
                }
            }
            stages {
                stage('Initialise') {
                    steps {
                        sh 'printenv'
                        checkout scm
                    }
                }
            }
        }
    }
}
```
You will get this error:
```
ERROR: ‘checkout scm’ is only available when using “Multibranch Pipeline” or “Pipeline script from SCM”
```
And if you do not add "checkout scm" into your "Pipeline script" your code does not get checked out

This worked in the previous non-declarative pipeline style i.e. your checked in Jenkinsfile could be cut and pasted into an inline version pretty seamlessly so you didn't have to checkin your pipeline definition when working on it. 

I am not sure if there is an easy workaround ?

Tested using OCP v3.7.23 and Jenkins ver. 2.89.2 from  jenkins-2-centos7:latest

**Comment by gabemontero** [comment]
Hey @eformat - see https://github.com/openshift/jenkins-client-plugin#overview

We cannot support `pipeline` nested within `openshift.withCluster`.  Try reversing the order, with `pipeline` at the outer most level, and reopen if you still see some discrepancies.

@bparees fyi - potentially another one of these;  side note - when I originally diagnosed all this I tried to see if I could somehow infer this nesting issue and abort on the `withCluster` call, but could not find a reliable way at the time.  It might be worth budgeting some time to try it again.

**Comment by eformat** [comment]
Thanks @gabemontero, of course. It seesm the shorthand `checkout scm` does not work, but the long hand version does. The following works OK
```
pipeline {
    agent {
        node {
            label 'nodejs'
        }
    }
    stages {
        stage('checkout') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withCredentials() {
                            openshift.withProject() {
                                checkout([$class           : 'GitSCM',
                                          branches         : [[name: "*/${PS_GIT_REF}"]],
                                          userRemoteConfigs: [[url: "${PS_GIT_URI}"]]
                                ]);
                                dir("${WORKSPACE}") {
                                    def commit_id = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
                                    echo "${commit_id}"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
I read the second paragraph of the Doco, and promptly forgot it - i think mainly because i was working off the origin example which has it the other way round ! 

https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml#L13-L16

**Comment by gabemontero** [comment]
On Wed, Jan 31, 2018 at 5:48 PM mike hepburn <notifications@github.com>
wrote:

> Thanks @gabemontero <https://github.com/gabemontero>, of course. It seesm
> the shorthand checkout scm does not work, but the long hand version does.
> The following works OK
>
> pipeline {
>     agent {
>         node {
>             label 'nodejs'
>         }
>     }
>     stages {
>         stage('checkout') {
>             steps {
>                 script {
>                     openshift.withCluster() {
>                         openshift.withCredentials() {
>                             openshift.withProject() {
>                                 checkout([$class           : 'GitSCM',
>                                           branches         : [[name: "*/${PS_GIT_REF}"]],
>                                           userRemoteConfigs: [[url: "${PS_GIT_URI}"]]
>                                 ]);
>                                 dir("${WORKSPACE}") {
>                                     def commit_id = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
>                                     echo "${commit_id}"
>                                 }
>                             }
>                         }
>                     }
>                 }
>             }
>         }
>     }
> }
>
> I read the second paragraph of the Doco, and promptly forgot it - i think
> mainly because i was working off the origin example which has it the other
> way round !
>
>
> https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml#L13-L16
>
ah yeah we need to fix that sample  thanks

**Comment by gabemontero** [comment]
On Wed, Jan 31, 2018 at 10:57 PM, Gabe Montero <gmontero@redhat.com> wrote:

>
> On Wed, Jan 31, 2018 at 5:48 PM mike hepburn <notifications@github.com>
> wrote:
>
>> Thanks @gabemontero <https://github.com/gabemontero>, of course. It
>> seesm the shorthand checkout scm does not work, but the long hand
>> version does. The following works OK
>>
>> pipeline {
>>     agent {
>>         node {
>>             label 'nodejs'
>>         }
>>     }
>>     stages {
>>         stage('checkout') {
>>             steps {
>>                 script {
>>                     openshift.withCluster() {
>>                         openshift.withCredentials() {
>>                             openshift.withProject() {
>>                                 checkout([$class           : 'GitSCM',
>>                                           branches         : [[name: "*/${PS_GIT_REF}"]],
>>                                           userRemoteConfigs: [[url: "${PS_GIT_URI}"]]
>>                                 ]);
>>                                 dir("${WORKSPACE}") {
>>                                     def commit_id = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
>>                                     echo "${commit_id}"
>>                                 }
>>                             }
>>                         }
>>                     }
>>                 }
>>             }
>>         }
>>     }
>> }
>>
>> I read the second paragraph of the Doco, and promptly forgot it - i think
>> mainly because i was working off the origin example which has it the other
>> way round !
>>
>> https://github.com/openshift/origin/blob/master/examples/
>> jenkins/pipeline/nodejs-sample-pipeline.yaml#L13-L16
>>
> ah yeah we need to fix that sample  thanks
>

Addressing with https://github.com/openshift/origin/pull/18390 ... thanks
again for the heads up @eformat

**Comment by etoews** [comment]
@eformat Thanks a lot for sharing your solution. I'm trying to do something similar but I'm using an access key to clone my Bitbucket repo. 

Was your repo using any kind of credentials? 

How did you specify those credentials in OpenShift?

I wrote up a question on StackOverflow about it [Using a secret for scm checkout from on-prem Bitbucket in a Jenkins pipeline in OpenShift](https://stackoverflow.com/questions/51492034/using-a-secret-for-scm-checkout-from-on-prem-bitbucket-in-a-jenkins-pipeline-in).

**Comment by megakoresh** [comment]
@gabemontero This does not work anymore, even if it did before, so I think the issue should be reopened. Example:

```yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: some-service-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: test
      uri: 'https://private.github.url/some-service'
    sourceSecret:
      name: phs-jenkins-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |
        node("master") {
          stage("Checkout SCM") {
            checkout scm
        }
    type: JenkinsPipeline
  triggers:
    - github:
        secretReference:
          name: webhook
      type: GitHub
```

Prints the same message as in OP:

```
ERROR: ‘checkout scm’ is only available when using “Multibranch Pipeline” or “Pipeline script from SCM”
```

Tested with openshift `3.11`

**Comment by gabemontero** [comment]
@megakoresh the form of your pipeline in your BC does not match what is required by the `checkout` command ... plus your pipeline in now way even uses the plugin for this repo.

There is no need to reopen this issue.

Read the jenkins docs for pipelines and the scm step and use the jenkins `pipeline` directive like the example above at https://github.com/openshift/jenkins-client-plugin/issues/116#issuecomment-362097453
