### ISSUE TITLE
OcWatch via untilEach on a pod selector does not enter the closure body

### ISSUE THREAD

**Issue by tomcooperca** [openshift/jenkins-client-plugin#118]
I have a series of modules in a multi-module Maven project that are deployed onto OpenShift. Using the client plugin and after a new deploy, I check each pod and validate the ready status via this snippet:

```Groovy
def modulesToBuild = ['module-a', 'module-b'] //In reality, this array is populated by Jenkins via currentBuild.changeSets
timeout(10) {
    for (module in modulesToBuild) {
        def dcObj = openshift.selector('dc', module).object()
        def podSelector = openshift.selector('pod', [deployment: "${module}-${dcObj.status.latestVersion}"])
        podSelector.untilEach {
            echo "pod: ${it.name()}"
            return it.object().status.containerStatuses[0].ready
        }
    }
}
```

However, I get intermittent behavior where after evaluating a number of modules, OcWatch does not get to the next `echo "pod: ${it.name()}"` and the closure does not evaluate before the timeout is reached. See console output below and note how the closure does not get "entered" on the last series of watches:

```
[Pipeline] echo
pod: pods/module-a-27-750hd
[Pipeline] _OcAction
[Pipeline] _OcAction

watch closure returned true; terminating watch
[Pipeline] }
[Pipeline] // _OcWatch
[Pipeline] _OcAction
[Pipeline] _OcWatch
Entering watch
Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] echo
pod: pods/module-b-27-9mczx
[Pipeline] _OcAction
[Pipeline] _OcAction
Checking watch output again in 300ms
[Pipeline] }
Checking watch output again in 360ms
Checking watch output again in 432ms
Checking watch output again in 518ms
Checking watch output again in 621ms
Checking watch output again in 745ms
Checking watch output again in 894ms
Checking watch output again in 1072ms
Checking watch output again in 1286ms
Checking watch output again in 1543ms
Checking watch output again in 1851ms
Checking watch output again in 2221ms
Checking watch output again in 2665ms
Checking watch output again in 3198ms
Checking watch output again in 3837ms
Checking watch output again in 4604ms
Checking watch output again in 5524ms
Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] echo
pod: pods/module-b-27-9mczx
[Pipeline] _OcAction
[Pipeline] _OcAction

watch closure returned true; terminating watch
[Pipeline] }
[Pipeline] // _OcWatch
[Pipeline] _OcAction
[Pipeline] _OcWatch
Entering watch
Running watch closure body
[Pipeline] {
[Pipeline] _OcAction
Checking watch output again in 300ms
[Pipeline] }
Checking watch output again in 360ms
Checking watch output again in 432ms
Checking watch output again in 518ms
Checking watch output again in 621ms
Checking watch output again in 745ms
Checking watch output again in 894ms
Checking watch output again in 1072ms
Checking watch output again in 1286ms
Checking watch output again in 1543ms
Checking watch output again in 1851ms
Checking watch output again in 2221ms
Checking watch output again in 2665ms
Checking watch output again in 3198ms
Checking watch output again in 3837ms
Checking watch output again in 4604ms
Checking watch output again in 5524ms
Checking watch output again in 6628ms
Checking watch output again in 7953ms
Checking watch output again in 9543ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Checking watch output again in 10000ms
Cancelling nested steps due to timeout
```

**Comment by gabemontero** [comment]
Depending on the timing of a) when pods from deployments actually getting scheduled, and b) how soon before the logic in the description the deployment was triggered, I could see a window where the selector's count is zero and `untilEach` returns immediately.

The `if (it.count() < min) return false;` line in particular is curious... the entire block is at https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1094-L1108

I think that should be changed to sleep for sec, then continue and the check again if `the number of objects is greater-than or equal to the minimumCount parameter (defaults to 1)`  ... it most likely was a fast fail mechanism, but I think the timings on the master side have changed a bit since this piece was first authored.

Pipelines of course have the timeout directive to control how long you want to wait before bailing on any calls ... and the help already calls out that `will not terminate until the number of objects selected by the receiver is greater-than or equal to the minimumCount and the closure body returns true for each selected object`

**Comment by gabemontero** [comment]
the fix for this will be in v1.0.6 of the openshift-client plugin

**Comment by gabemontero** [comment]
the openshift jenkins centos image will be updated in the next day or two

the openshift jenkins rhel image update will be part of the 3.9 release targeted for March

**Comment by tomcooperca** [comment]
@gabemontero Given your explanation and since I know the number of objects I need to operate on, would it simply be resolved by setting the minimumCount? Something like this:

```Groovy
timeout(10) {
    for (module in modulesToBuild) {
        //truncated...
        podSelector.untilEach(modulesToBuild.size()) {
            echo "pod: ${it.name()}"
            return it.object().status.containerStatuses[0].ready
        }
    }
}
```

Apologize for my ignorance - just been a happy user of the plugin and didn't get a chance to dive through the src :smile:

**Comment by gabemontero** [comment]
Cool glad to help @tomcooperca
