### ISSUE TITLE
What would be the best equivalent of openshiftVerifyDeployment() in this plugin?

### ISSUE THREAD

**Issue by etsauer** [openshift/jenkins-client-plugin#122]

**Comment by gabemontero** [comment]
See https://github.com/openshift/jenkins-client-plugin/issues/84 @etsauer 

Some examples are cited there, and I've asked @coreydaley to officially document / provide examples when he has some bandwidth

As noted in that issue as well, we are considering some pipeline global libraries or other higher level abstractions in the future
