### ISSUE TITLE
Getting empty results from plugin when using custom slave

### ISSUE THREAD

**Issue by etsauer** [openshift/jenkins-client-plugin#123]
While attempting to run some openshift.selector() methods to grab some simple objects, I keep getting incorrect empty responses such as:

```
Verbose sub-step output:
	Command> oc get imagestream/jenkins-slave-image-mgmt -o=json --server=https://172.30.0.1:443 --namespace=multicluster-spring-boot-dev --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --loglevel=8 --token=XXXXX 
	Status> 0
	StdOut>
	StdErr> 
	Reference> {}
```

This then results in exceptions like: 
```
java.lang.IllegalArgumentException: Text must not be null or empty
...
```

This issue seems to be confined to a single Stage that is running within a custom kubernetes pod template, defined as:

```
      agent {
        kubernetes {
          label 'promotion-slave'
          cloud 'openshift'
          serviceAccount 'jenkins'
          containerTemplate {
            name 'jenkins-slave-image-mgmt'
            image "${SKOPEO_IMAGE}"
            ttyEnabled true
            command 'cat'
          }
        }
```

Are there some environmental requirements I am possibly missing in my slave that could be causing this?

Full stage example:
```
    stage('Promote to Prod') {
      agent {
        kubernetes {
          label 'promotion-slave'
          cloud 'openshift'
          serviceAccount 'jenkins'
          containerTemplate {
            name 'jenkins-slave-image-mgmt'
            image "${SKOPEO_IMAGE}"
            ttyEnabled true
            command 'cat'
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            echo "Looking for secret in ${openshift.project()}"
            openshift.verbose()
            testImage = openshift.selector( 'is/jenkins-slave-image-mgmt' ).object().status.dockerImageRepository
            echo "Test Image: ${testImage}"

            openshift.raw('whoami')
            def secretData = openshift.selector('secret', 'prod-credentials')
            echo "${secretData.object()}"
            openshift.verbose(false)
/*
            openshift.withProject("${STAGE2}") {
              def imageRegistry = openshift.selector( 'is', "${APP_NAME}").object().status.dockerImageRepository
              echo "Promoting ${imageRegistry}/${STAGE2}/${APP_NAME} -> ${secretData.registry}/${STAGE3}/${APP_NAME}"
              sh "skopeo copy --tls-verify=false --remove-signatures --src-creds openshift:${TOKEN} --dest-creds openshift:${secretData.token} docker://${imageRegistry}/${STAGE2}/${APP_NAME} docker://${secretData.registry}/${STAGE3}/${APP_NAME}"
            }
*/
          }
        }
      }
    }
```

**Comment by gabemontero** [comment]
Hey @etsauer 

Nothing about the single stage aspects seems relevant to me on whether your selector can find the image stream.

However, in looking at your full stage example, the fact that 
```
            testImage = openshift.selector( 'is/jenkins-slave-image-mgmt' ).object().status.dockerImageRepository
```
is outside the `openshift.withProject("${STAGE2}")` does seem important to me.

With the selector outside, it is going to look for the imagestream in the namespace that jenkins is running in.  Is that where it is?  

If not, surround it with a withProject call to the appropriate project.

If it is, then I'd be curious of
a) since it may be a timing thing, what are the particulars of when the images stream gets created
b) try `sh 'oc get is....` right before with the same options for oc for token, certificate, etc. and report what that returns ... since you are using the default cluster, the token would the the service account token mounted in the pod at `/var/run/secrets/kubernetes.io/serviceaccount/token`

**Comment by etsauer** [comment]
@gabemontero yeah, that example is kind of confusing as it has a bunch of stuff that appears to be specific to my environment.

To answer your questions, the object i'm attempting to fetch doesn't appear to matter, and I CAN use straight up oc commands in the shell to retrieve them in that image.

Here's a much simpler reproducer that shows two stages fetching the same object - one without the slave, and one with. When you run through this it will fail in the third stage. If you'd like to actually try it, the slave image can be built from here: 

```
pipeline {
    agent { label 'maven' }
    stages {
        stage ('Setup') {
            steps {
                script {
                    openshift.withCluster() {
                        def secret = [
                            "kind": "Secret",
                            "metadata": [
                                "name": "mysecret",
                                "labels": [
                                    'findme':'please'
                                ]
                            ],
                            "stringData": [
                                "username": "myname",
                                "password": "mypassword"
                            ]
                        ]
                        openshift.apply(secret)
                    }
                }
            }
        }
        stage ('Without Agent') {
            steps {
                script {
                  openshift.withCluster() {
                    // prove object exists
                    sh 'oc get secret/mysecret -o json'
                  
                    openshift.verbose()
                    mysecret = openshift.selector( 'secret/mysecret' ).object()
                    echo "Test Image: ${mysecret}"
                    openshift.verbose(false)
                  }
                }
            }
        }
        stage ('With Agent') {
            agent {
                kubernetes {
                  label 'promotion-slave'
                  cloud 'openshift'
                  serviceAccount 'jenkins'
                  containerTemplate {
                    name 'jenkins-slave-image-mgmt'
                    image 'docker-registry.default.svc:5000/multicluster-spring-boot-dev/jenkins-slave-image-mgmt'
                    ttyEnabled true
                    command 'cat'
                  }
                }
            }
            steps {
                script {
                  openshift.withCluster() {
                    // prove object exists
                    sh 'oc get secret/mysecret -o json'

                    openshift.verbose()
                    mysecret = openshift.selector( 'secret/mysecret' ).object()
                    echo "Test Image: ${mysecret}"
                    openshift.verbose(false)
                  }
                }
            }
        }
    }
}

**Comment by gabemontero** [comment]
ah ... ok that clarification helps @etsauer 

yeah there may be some differences with tokens being mounted in the slave pod vs. the master pod, and when you go with the default cluster, you don't have the auth you think you have ... but running oc from the command line gets a different auth, depending on what is in your image ... or we might have a bug.

I'll try building your image and use this sample to prove that out (might not get to it until Thursday).

Short term, you might want to try explicitly configuring a cluster in Jenkins with the various token, cert, url you need and then leverage that cluster specifically in `openshift.withCluster` ... if it works, my theory is on the right track.

**Comment by etsauer** [comment]
@gabemontero cool, and just one other comment on what you said.. nothing here runs on the 'master'. Its all slaves. Its just the preconfigured maven slave vs my custom defined slave, so I wouldn't think the token mounting would be different. Anyway, I'll keep investigating as well, but so far i've been able to reproduce on multiple clusters with different project names, etc.

**Comment by etsauer** [comment]
@gabemontero updated Jenkinsfile in https://github.com/openshift/jenkins-client-plugin/issues/123#issuecomment-367381257 to ensure both shell commands and plugin are using the same credentials. Same behavior.

**Comment by etsauer** [comment]
@gabemontero another component to this is this is my first attempt at defining a slave pod in a declarative pipeline. I'm wondering if there is something wrong with my agent config that's causing issues with native callbacks from slave to master or something.

@bparees would you mind taking a loot at the agent config in https://github.com/openshift/jenkins-client-plugin/issues/123#issuecomment-367381257?

**Comment by bparees** [comment]
It looks fine but I suggest you step back and configure the slave in jenkins itself and confirm it works as you expect. That will reduce the risk that you've simply gotten the syntax wrong.

**Comment by etsauer** [comment]
@bparees good suggestion. I was finally able to get a configuration that works. 

```
          agent {
              kubernetes {
                label 'promotion-slave'
                cloud 'openshift'
                serviceAccount 'jenkins'
                containerTemplate {
                  name 'jnlp'
                  image "docker-registry.default.svc:5000/${NAMESPACE}/jenkins-slave-image-mgmt"
                  alwaysPullImage true
                  workingDir '/tmp'
                  args '${computer.jnlpmac} ${computer.name}'
                  ttyEnabled false
                }
              }
          }
```

**Comment by bparees** [comment]
Cool!

**Comment by gabemontero** [comment]
Likewise cool ! 

So if I parsed all this correctly, we can close this out, right?

Doing so now, please reopen @etsauer if there is something still outstanding I am overlooking.
