### ISSUE TITLE
watching for serveral dcs ? / processing several templates ? 

### ISSUE THREAD

**Issue by funkomatic** [openshift/jenkins-client-plugin#124]
Hi,

I'd have a couple of questions regarding the best practices in order to : 
- deploy a template that contains a number of dcs 
- deploy a number of templates (each containing several dcs ) 

### Q1: A template with serveral deploymentconfig

The following code for processing the template and watinf for pods works fine as long as there is a *single* deployementconfig in the template file : 
```groovy
  // process file
  def model = openshift.process( "-f" , "pathToMyTemplateFile",  "--param-file", "pathToMyEnvFile" )
  // create ressources
  def created = openshift.apply(model) 
  // wait for pods to start 
  def dcs     = created.narrow("dc")
  timeout(timeOut) {
            dcs.related('pods').untilEach() {
              return it.object().status.phase == 'Running'
             }
  }
```
However if the template contains multiple deploymentconfig then it fails with the following error : 

_ERROR: Expected single name, but found multiple in selection: [deploymentconfig/A, deploymentconfig/B, deploymentconfig/C, deploymentconfig/D]_

Where A,B,C,D are the names of the deployementconfig in the template files.

Is there a way of achieving the same processing (template process, apply then watch ) for a template that contains any number of deployementconfig elements ? 

### Q2 : Handling several templates

I also have the use case where a given pipeline should deploy several templates.
Now it seems that opensfhift.process cannot handle more then one template file.
What I'd like to avoid is to loop on all template files and executing the timeout/untilEach for each and every template file, as the timeout would basically be per tempalte file and not for the global processing.
So is there a way of returning a "model" structure that is the result of the processing of serveral templates ? 
If not is there a way of merging the "model" structures from subsequent openshift.process calls ? 

Thanks in advance;

**Comment by gabemontero** [comment]
Hi @funkomatic 

For your Q2, yeah, this plugin models itself after the `oc` command, which currently does not provide the means of a) processing multiple templates with one invocation, or b) merging the results of multiple process template invocations.  So organically we have not received a lot of use cases around this.

That said, I *have* an answer for you with regard to merging after the fact ;-)

I have not tried it, and we don't expose it in our Global Variable help doc, so I'll claim we don't officially support it yet if you have a problem with it ;-) , but there is an `openshift.toSingleObject(...)` method.  If you pass it a java.util.List of models, it is suppose to combine them into a single model.

If you have the bandwidth, give it a go.  If it works for you, let me know, and I'll start thinking about bubbling this up to the global variable help, readme, etc. wrt handling multiple templates.

For your Q1, the immediate suggestion that come to my mind is use the `it.objects()` method first, iterate over that, and call `object().status.phase` on each iteration.

**Comment by funkomatic** [comment]
Hi, 
I'll definitely give a try to both suggestions and let you know by tomorrow.
Thanks

**Comment by funkomatic** [comment]
Hi, 
The day turned into two weeks but here is some feedback : 

I managed to use `openshift.toSingleObject(...)`, it seems to work from the code point of view, however passing the list to `openshift.apply()` don't seem to work properly. 

Anyway I ended by using `oc.raw` command in order to process my templates, then I simply read the output json and pass it to `openshift.apply()`. Of course I had to iterate on my templates, and this is probably not the most elegant way of doing it, yet it works.

For the pods, I had no choice but to iterate over templates then watch for all related DC pods to be up, the `it.objects()` did not help me.

**Comment by gabemontero** [comment]
Glad you got something working @funkomatic 

On passing the list from `toSingleObject(...)` into `apply(...)` not working properly, if you have a moment, I'd be curious if 
a) what version of the plugin you are using ... we recently redid how the processing of lists were done to account for list possibly referencing different projects ... I wonder if i) if you are at the right level, was a new bug introduced we have not seen yet, or ii) or would the latest level have helped you 

b) were there any error messages or exceptions when it did not work properly ... or could you elaborate on what did not work

thanks

**Comment by gabemontero** [comment]
Closing out ... @funkomatic - please reopen if you are able to get back to this and answer the questions from https://github.com/openshift/jenkins-client-plugin/issues/124#issuecomment-375426635
