### ISSUE TITLE
more useful step item title than "Internal utility function for OpenShift DSL"

### ISSUE THREAD

**Issue by phemmer** [openshift/jenkins-client-plugin#127]
Currently each item in the Blue Ocean output shows up as "Internal utility function for OpenShift DSL". This is rather unhelpful when you have lots of steps/commands, as to find the output of the one you want you just have to open each one.
It would be useful instead if this output were customizable, and/or defaulted to indicating which command was run.

**Comment by gabemontero** [comment]
thanks for highlighting this @phemmer 

Yeah, looking at a some other implementations of `org.jenkinsci.plugins.workflow.steps.AbstractStepImpl` in other plugins, including https://github.com/jenkinsci/docker-workflow-plugin, which this plugin modeled itself after during its initial creation, the step has a direct, precise correlation to the DSL

... i.e. the `withDockerContainer` DSL step correlates with `WithContainerStep.java` and hence the statically defined DescriptorImpl can hard code the display name

However, in the case of our plugin, we have a single `org.jenkinsci.plugins.workflow.steps.AbstractStepImpl`, `OcAction.java`, which is reused with each of multitude of methods off of the `openshift` Global Variable.

Certainly given the larger and still evolving list of methods in our plugin vs. docker workflow, that makes sense.

I currently see no way to provide input to the DescriptorImpl to vary the text.

So doing this would entail creating `org.jenkinsci.plugins.workflow.steps.AbstractStepImpl` extension classes (where they in turn could extend a modified form of OcAction to share logic) for all our different methods.  And continue to do so as we add methods.

Not sure yet how this lines up priority wise with all of our other reqs, but per our process, I'll open a trello card to track.

thanks again

@bparees @coreydaley fyi

@jupierce if bandwidth / interest permits, thoughts / historical perspectives ?

**Comment by gabemontero** [comment]
card https://trello.com/c/eII3QvHY/1528-pipelineintegration-create-method-unique-abstractstepimpl-extensions-to-provide-better-display-names opened

per our process, closing this issue

@phemmer - you are free to join our trello board at https://trello.com/b/wqe9UaaZ/developer-experience to further comment on this issue, or peruse our other jenkins related requirements and work in progress

**Comment by RoybertParada** [comment]
Hello, is this issue fixed? or do you something to avoid that unhelpful message in blue ocean?
