### ISSUE TITLE
version 1.0.8 openshift.selector doesn't work anymore

### ISSUE THREAD

**Issue by ramato-procon** [openshift/jenkins-client-plugin#131]
From version 1.0.8 the openshift.selector with pod and label doesn't work anymore.
Method-Call: 
```
openshift.withCluster(crp) {
    openshift.withProject(ocstage) {
       openshift.selector("pod", [ app: "${app}" ]) 
    }
}
```

Result:
`ERROR: projects were not set for selector([name=pod],[labels={app=mq-synchronizer}],[namelist=null],[projectlist=null])`

With version 1.0.7 it runs perfectly.

**Comment by gabemontero** [comment]
hey @ramato-procon - thanks for the report

the `projects were not set for selector` message come from `selector.withEach`, which is either called by your script directly, or by the `selector.untilEach` or using the rollout manager stuff ... I'm guessing the example you provided is just the beginning part, and you have one of those calls below.

For example, with 

```
openshift.withCluster() {
    openshift.withProject() {
       openshift.selector("pod", [ app: "asdf" ]) 
    }
}
```

I get no errors.

With

```
openshift.withCluster() {
    openshift.withProject() {
       def pods = openshift.selector("pod", [ app: "asdf" ])
       pods.withEach {
         echo "GGM"
       }
    }
}
```

I get an error just like yours:  `ERROR: projects were not set for selector([name=pod],[labels={app=asdf}],[namelist=null],[projectlist=null])`

Anyway, I'll go ahead and implement the fix based on my repro.  But do let me know if what I mentioned above does not line up with what you have and we need to look at other paths.

Thanks

**Comment by ramato-procon** [comment]
@gabemontero Sorry for the late answer. I didn't saw the notification.
Your fix was already released with 1.0.9, right?
Unfortunately I still get the same error.

And yes I was calling withEach.
My code including withEach:

```
openshift.withCluster(crp) {
	openshift.withProject(ocstage) {
		timeout(10) {
                        echo 'Select application pods'
			def pods = openshift.selector("pod", [ deploymentconfig: "${app}" ])
			def pod
			if (!pods.exists()) {
					error 'No pod found'
			} else {
			// Get running pod
			echo 'Selecting pod'
			pods.withEach {
				if (it.object().status.phase == 'Running') {
						pod = it.name();
						return true;
			  } else {
				  return false;
				}
			}
	  ....
   
```
The error appears after the echo 'Selecting pod', so it is definitely the withEach.

**Comment by gabemontero** [comment]
Thanks for the confirmation @ramato-procon 

Yeah, seeing a similar report in https://github.com/openshift/jenkins-client-plugin/issues/130

Unfortunately, while to date it still seems very intermittent for me, it seems to be occurring regularly for others.

I'll be making another attempt at reproducing locally today, but otherwise, I may be soliciting users to try and reproduce with a debug jar.

**Comment by gabemontero** [comment]
If you would be able to run the scenario with a debug jar I provide, certainly let me know ... thanks.

**Comment by gabemontero** [comment]
Hey @ramato-procon 

Ok, the deployment aspect of this changed my viewpoint on this and I now may understand what is going on.  There is a timing element involved here, as the `withEach` clause is ultimately performing an `oc get` and based on the results it gets, we may hit this.  In my testing, I was just dealing with pods in my prior testing.   The change to address, while certainly doable, is not trivial.

Would it be possible for you to take a pre-release version of the plugin and validate against your cluster?  Getting some early results from your env could expedite the overall resolution, as replicating the timing on my end could be problematic.

**Comment by ramato-procon** [comment]
Hi @gabemontero Yes, I can run a pre-release in my cluster.

The issue happens with all label selectors (also app)

**Comment by ramato-procon** [comment]
@gabemontero Now it is working. Thanks!

```
Selecting pod
[Pipeline] _OcAction
GGM withEach names [pod/mq-synchronizer-42-1tjgb] projects null
GGM _asMarkup null objlist [pod/mq-synchronizer-42-1tjgb]
[Pipeline] _OcAction
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
```

**Comment by gabemontero** [comment]
Thanks for the confirmation @ramato-procon 

I've received similar confirmation from some of the other upstream users.

The PR merge / new version of the plugin / image update process will be starting shortly.
