### ISSUE TITLE
Namespace null when using apply command

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#135]
Hi, I updated from version 1.0.7 to 1.0.8 and my pipeline stopped working. I am getting this error when I try to use apply command

err=Error from server (Forbidden): User "system:serviceaccount:cloudmgmt:svc-petclinic-test" cannot get buildconfigs in project "null", verb=apply, cmd=oc --server=xxxx --insecure-skip-tls-verify --namespace=null --token=XXXXX apply -f /tmp/apply427555795519702935.markup -o=name , out=, status=1}

It looks like the plugin is passing the namespace as null. If I downgrade to version 1.0.7 then it works again.

**Comment by gabemontero** [comment]
Yeah this is a dup of https://github.com/openshift/jenkins-client-plugin/issues/133

I should have v1.0.9 out later today my time.
