### ISSUE TITLE
have .delete(.process("yml")) work

### ISSUE THREAD

**Issue by diamark** [openshift/jenkins-client-plugin#137]
running cli oc allows for creation or deletion of a processed yaml file:

```
oc process -f yml | oc create -f -
oc process -f yml | oc delete -f -
```

```
openshift.create(openshift.process(readFile(yml), someparams))  works
openshift.delete(openshift.process(readFile(yml), someparams))  fails
```

I tried variations of deletion like .process().delete() and played with selectors but so far failed to have a one line equivalent to the .create(.process()) for deletion.

The delete expects selectors, I think. As pipe links in openshift.raw() have problems with setting namespace on both sides of the pipe, I am somewhat stuck with writing the output of process to file and then pass that file to a raw delete command like this `openshift.raw('delete', '-f', "${fname}")`

**Comment by gabemontero** [comment]
Hey @diamark 

Yeah, with the current implementation, this works for `create` cause because since it is returning a selector, it goes through our template post processing path.

Since `delete` only returns a result, that template post processing is not currently invoked.

And you are correct around the limitations of `raw` here.

Can you elaborate on exactly how it fails?  Is it simply that the namespace/project is not properly set when the actual `oc` invocation is made?

**Comment by diamark** [comment]
The call is something like this `openshift.raw(process, -f, tpl.yml, -p, FOO=bar, |, oc, delete, -f, -)` and it fails apparently because the server and token info gets appended to the actual call and thus only apply to the second oc invocation. I worked around this by forcing the process to local and that worked somewhat. But seeing the client plugin going GA and maturing pretty fast (thanks to your and the other commiters much appreciated hard work), I started to port all raw() calls to their dsl counterparts.

So this is just a humble feature/enhancement request of low prio. It just struck me as odd that something I got used to with the oc binary is kind of complicated when using dsl. Feel free to close it as WONTFIX, I am still grateful for everything the plugin offers :-)

**Comment by diamark** [comment]
Oh, that one :-D . Sure, I will fetch a sample once my corporate VPN comes back online. Probably tomorrow

**Comment by diamark** [comment]
Hmm, it used to be more talkative in previous versions. Here is the output of `openshift.delete(openshift.process(readFile("${largs.tpldir}/${tpl}.yml"), this.setTplParams(largs) ))`. The setup is basically the same as with https://github.com/openshift/jenkins-client-plugin/issues/133 , I just changed the .create to .delete.

I think I remember that my previous tests showed some error or usage message about selectors or those being required. Unfortunately, I do not have the logs from the tests anymore.

```
I0406 08:37:52.414319   30056 round_trippers.go:383] POST https://myopenshift:443/oapi/v1/namespaces/petclinic-build/processedtemplates
I0406 08:37:52.414326   30056 round_trippers.go:390] Request Headers:
I0406 08:37:52.414330   30056 round_trippers.go:393]     Authorization: Bearer XXXXX
I0406 08:37:52.414335   30056 round_trippers.go:393]     Content-Type: application/json
I0406 08:37:52.414339   30056 round_trippers.go:393]     User-Agent: oc/v3.6.173.0.96 (linux/amd64) openshift/8f6ff22
I0406 08:37:52.414343   30056 round_trippers.go:393]     Accept: application/json, */*
I0406 08:37:52.488003   30056 round_trippers.go:408] Response Status: 201 Created in 73 milliseconds
I0406 08:37:52.488021   30056 round_trippers.go:411] Response Headers:
I0406 08:37:52.488025   30056 round_trippers.go:414]     Cache-Control: no-store
I0406 08:37:52.488029   30056 round_trippers.go:414]     Content-Type: application/json
I0406 08:37:52.488032   30056 round_trippers.go:414]     Date: Fri, 06 Apr 2018 08:37:52 GMT
I0406 08:37:52.488036   30056 round_trippers.go:414]     Content-Length: 1619
I0406 08:37:52.536844   30056 request.go:991] Response Body: {"kind":"Template","apiVersion":"v1","metadata":{"name":"petclinic-${STACK}-${BRANCH}","selfLink":"/oapi/v1/namespaces//processedtemplates/petclinic-%24%7BSTACK%7D-%24%7BBRANCH%7D","creationTimestamp":null},"objects":[{"apiVersion":"v1","kind":"BuildConfig","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":null,"labels":{"app":"petclinic-build-master","application":"petclinic","branch":"master","commit":"abcd","template":"build-build-master","xpaas":"1.3.2"},"name":"petclinic-build-master"},"spec":{"output":{"to":{"kind":"ImageStreamTag","name":"petclinic:master"}},"postCommit":{},"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"500m","memory":"500Mi"}},"runPolicy":"Serial","source":{"binary":{"asFile":"petclinic.war"},"dockerfile":"FROM jboss-webserver30-tomcat8-openshift:latest\nCOPY petclinic.war /opt/webserver/webapps/petclinic.war","type":"Binary"},"strategy":{"dockerStrategy":{"env":[{"name":"REV","value":"abcd"},{"name":"BRANCH","value":"master"}],"from":{"kind":"ImageStreamTag","name":"jboss-webserver30-tomcat8-openshift:latest","namespace":"openshift"}},"type":"Docker"}}}],"parameters":[{"name":"REV","description":"The git revision the build is based on","value":"abcd"},{"name":"BRANCH","description":"The git branch the build is based on","value":"master"},{"name":"STACK","description":"The stack which created objects belong to","value":"build"},{"name":"COLOR","description":"Color label of the prod deployment, empty in most cases"},{"name":"CATALINA_OPTS","description":"Generated opts to help name resolution"}]}
	Reference> {}
[Pipeline] _OcAction
Verbose sub-step output:
	Command> oc --server=https://myopenshift:443 --insecure-skip-tls-verify --namespace=petclinic-build --loglevel=8 --token=XXXXX delete [metadata:[creationTimestamp:null, name:petclinic-build-master, annotations:[openshift.io/generated-by:OpenShiftWebConsole], labels:[app:petclinic-build-master, template:build-build-master, application:petclinic, xpaas:1.3.2, commit:abcd, branch:master]], apiVersion:v1, kind:BuildConfig, spec:[output:[to:[name:petclinic:master, kind:ImageStreamTag]], resources:[limits:[cpu:1000m, memory:1Gi], requests:[cpu:500m, memory:500Mi]], source:[type:Binary, binary:[asFile:petclinic.war], dockerfile:FROM jboss-webserver30-tomcat8-openshift:latest
COPY petclinic.war /opt/webserver/webapps/petclinic.war], postCommit:[:], strategy:[type:Docker, dockerStrategy:[env:[[name:REV, value:abcd], [name:BRANCH, value:master]], from:[name:jboss-webserver30-tomcat8-openshift:latest, namespace:openshift, kind:ImageStreamTag]]], runPolicy:Serial]] 
	Status> 255
	StdOut>
	StdErr> 
	Reference> {}
[Pipeline] echo
hudson.AbortException: delete returned an error;
{reference={}, err=, verb=delete, cmd=oc --server=https://myopenshift:443 --insecure-skip-tls-verify --namespace=petclinic-build --loglevel=8 --token=XXXXX delete [metadata:[creationTimestamp:null, name:petclinic-build-master, annotations:[openshift.io/generated-by:OpenShiftWebConsole], labels:[app:petclinic-build-master, template:build-build-master, application:petclinic, xpaas:1.3.2, commit:abcd, branch:master]], apiVersion:v1, kind:BuildConfig, spec:[output:[to:[name:petclinic:master, kind:ImageStreamTag]], resources:[limits:[cpu:1000m, memory:1Gi], requests:[cpu:500m, memory:500Mi]], source:[type:Binary, binary:[asFile:petclinic.war], dockerfile:FROM jboss-webserver30-tomcat8-openshift:latest
COPY petclinic.war /opt/webserver/webapps/petclinic.war], postCommit:[:], strategy:[type:Docker, dockerStrategy:[env:[[name:REV, value:abcd], [name:BRANCH, value:master]], from:[name:jboss-webserver30-tomcat8-openshift:latest, namespace:openshift, kind:ImageStreamTag]]], runPolicy:Serial]] , out=, status=255}
```

**Comment by gabemontero** [comment]
That output @diamark was actually sufficient for me to see what is going on, and I consider this a bug actually.

The delete as currently constructed is trying to pass in the groovy list/map representation retruned from `openshift.process` to `oc` instead of a json/yaml one.  The implementation current assumes you are passing in args like `bc/foo`, etc. and not actual api structs.

By comparison, the `openshft.create` equivalent is able to detect if it got a list/map and convert it to json.

I'm juggling a few fixes but could have something put together fairly soon I think.
