### ISSUE TITLE
Refactor Logging to Jenkins

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins-client-plugin#141]
The output looks really nasty in BlueOcean (see below screenshot). Anyway to clean this up so it only shows a single entry, not 40?

![screenshot from 2018-04-09 13-41-42](https://user-images.githubusercontent.com/1335137/38519471-3297f856-3bfd-11e8-925a-9cf0c1b013c6.png)

**Comment by gabemontero** [comment]
This is a manifestation of https://github.com/openshift/jenkins-client-plugin/issues/127 and the associated trello card opened for it.
