### ISSUE TITLE
job object status.phase is null

### ISSUE THREAD

**Issue by jmcu** [openshift/jenkins-client-plugin#144]
Job pods have a null status.phase. 

Jenkins OpenShift Client Plugin version: 0.9.6

From pipeline, ${OPENSHIFT_JOB} is a yaml file
- apiVersion: batch/v1
- kind: Job

```groovy
def fromYAML = openshift.create( readFile( "${OPENSHIFT_JOB}" ) )
echo "Create objects from YAML file: ${fromYAML.names()}"
fromYAML
sleep 20
echo "why is fromYAML object status phase null? ${fromYAML.object().status.phase}"
```

Console output log:
```
Create objects from YAML file: [job/micron-rhel7-robotrunner]
[Pipeline] sleep
Sleeping for 1 min 0 sec
[Pipeline] _OcAction
[Pipeline] echo
why is fromYAML object status phase null? null
```

Using untilEach(1) hangs because 'status.phase == null'
```groovy
def fromYAML = openshift.create( readFile( "${OPENSHIFT_JOB}" ) )
timeout(1) {
    fromYAML.untilEach(1) {
        return it.object().status.phase == "Complete"
    }
}
```

**Comment by gabemontero** [comment]
The job api object does not have a `phase` field.

See https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/api/batch/v1/types.go#L120-L151
