### ISSUE TITLE
Expose a specific port? 

### ISSUE THREAD

**Issue by djohnston89** [openshift/jenkins-client-plugin#145]
We're creating a service using s2i/ new-app and its base-image (fis-java-openshift) only exposes 8778 (jolokia). Our desired port 8080 is not opened, and we want to automate this port opening for all future microservices through our declarative OpenShift DSL pipeline. Any ideas on the best way to do this?

Do we have to modify the service object before running .expose() on it? Can this be achieved using this DSL?

**Comment by gabemontero** [comment]
The only way currently from this DSL/plugin is to use the `openshift.raw` to execute the `expose` verb of `oc` on the svc obj.

I don't believe you have to do anything to an existing svc before calling expose, assuming the credentials you are making the call with have the requisite permissions.  But consult openshift/origin and the doc for any clarifications there.

Adding expose is not overly complicated.  I'll craft a quick PR, though it may be a bit before we craft a new version, update our jenkins images, etc.
