### ISSUE TITLE
Build and Deploy Docker Image

### ISSUE THREAD

**Issue by sawetma** [openshift/jenkins-client-plugin#152]
Hi,

I am new to Docker with Jenkins, and I come across this awesome plugin, so I have a couple questions about this plugin if you don't mind to answer and help me out.
I am wondering if I can use this plugin to build Docker Image and deploy it to docker hub or any other container registry?

Thanks,
Sawet

**Comment by bparees** [comment]
not directly, no.  this is a plugin for interacting with openshift from your jenkins instance.  openshift itself can build images and push to docker hub or other registries.  This plugin just exposes openshift's capabilities so you can use them from within your jenkins job.
