### ISSUE TITLE
oc tool version recomendation

### ISSUE THREAD

**Issue by rkrawiec** [openshift/jenkins-client-plugin#155]
In #49 it was mentioned there would be some guidance provided for oc tool versions relating to plugin versions. Is this available yet? We have see some similar issues to what we were experiencing before and we want to ensure we are using recommended oc tool versions for our plugin version and cluster version.

**Comment by gabemontero** [comment]
@rkrawiec the key concern with respect to the `oc` version is how does it correspond to the openshift api server version.

Generally speaking, the recommendation is to align those versions.  See https://github.com/openshift/jenkins#inclusion-of-the-oc-binary

And you can control which version of `oc` this plugin uses per https://github.com/openshift/jenkins-client-plugin#setting-up-jenkins-nodes

The only time this plugin's version comes into play is if newer versions of the plugin expose verbs of `oc` which were not present with an older version of `oc`, if you choose to use an older version.
