### ISSUE TITLE
Installing oc client in a Jenkins container does not work

### ISSUE THREAD

**Issue by gomesp** [openshift/jenkins-client-plugin#158]
Hi team

I am trying to use the plugin on a Jenkins instance running in a docker container (outside openshift). 
I am running the ```jenkins/jenkins:2.124-alpine``` image and installing the default recommended plugins and then later adding the openshift client plugin as well.

I then proceed to follow the instructions for installing the oc client tool in Jenkins. These are the parameters that I supply at Global Tool Configuration > OpenShift Client Tools:
* Name: oc
* Tool directory: /tmp
* Extract zip/targz: 
  * Download URL for binary archive: https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
  * Subdirectory: openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
  * Install automatically: checked

If I bash into my container I can see that the tool has been downloaded and installed into the location, but if I try to execute ```oc``` I will get an error:

```
bash-4.4$ pwd
/tmp/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
bash-4.4$ ./oc version
bash: ./oc: No such file or directory
bash-4.4$ ls -latr
total 212664
-rwxr-xr-x 1 jenkins jenkins 217725304 Mar 30 21:35 oc
-rwxr-xr-x 1 jenkins jenkins     15862 Mar 30 21:35 README.md
-rwxr-xr-x 1 jenkins jenkins     10759 Mar 30 21:35 LICENSE
drwxrwxrwt 1 root    root         4096 May 28 01:46 ..
drwxr-xr-x 2 jenkins jenkins      4096 May 28 01:46 .
bash-4.4$ whoami
jenkins
```

Is it not possible to run ```oc``` in a jenkins container?

**Comment by gabemontero** [comment]
hi @gomesp - yes, we run `oc` in jenkins containers all the time, albeit typically from the openshift/jenkins images produced from https://github.com/openshift/jenkins, like docker.io/openshift/jenkins-2-centos7:latest

I downloaded `jenkins/jenkins:2.124-alpine`, set things up as you did, and produced a form of the error you are seeing, though with a bit more information.  I get:

```
$ docker exec bdea1805d1c3 /tmp/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit/oc version
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "no such file or directory"

```

The module appears to correspond to the `./vendor/github.com/opencontainers/runc/libcontainer/container_linux.go` dependency in openshift origin.

So there appears to be some incompatibility at the docker/runc level between `oc` and that image.

I'll have to solicit some help from the SMEs in those areas and report back.

@bparees @sspeiche fyi

**Comment by gabemontero** [comment]
Yeah it appears to be an incompatibility with apline linux and `oc` around gssapi and some other libraries... `oc` does in fact dynamically link some libraries.

There is some precedence:
- https://github.com/openshift/origin/issues/17621
- https://github.com/gin-gonic/gin/issues/1178

@juanvallejo from my org's master/cli team will be working on a pull to the openshift/origin doc to better spell out these `oc` dependencies.... thanks @juanvallejo !

In the short term @gomesp , either try our image at docker.io/openshift/jenkins-2-centos7:latest or or the docker.io/jenkins/jenkins:latest image, which I believe is ultimately debian based (though full disclosure, I did not have time to try the later out myself).

**Comment by gomesp** [comment]
Thanks @gabemontero. I understand it's not up to your project to fix it but I appreciate the feedback.

If you want to provide some advice on your README.md about people using Alpine containers, this is what worked for me. I am placing a shell script named ```oc``` in my PATH and this script know how to load the right Alpine libraries to properly execute the oc binary.

## Dockerfile
```
FROM jenkins/jenkins:2.125-alpine
ENV OC_VERSION 3.6.173.0.117
USER root

RUN curl -L https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-${OC_VERSION}-linux-64bit.tar.gz | \
    tar xz --directory /tmp/
COPY oc /usr/local/bin/
RUN chmod +x /usr/local/bin/oc
USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/
COPY custom.groovy /usr/share/jenkins/ref/init.groovy.d/custom.groovy
```

## oc
```
#!/bin/bash
/lib/ld-musl-x86_64.so.1 --library-path /lib /tmp/oc $@
```

**Comment by gabemontero** [comment]
Thanks for the update @gomesp and kudos on figuring out how to link in the correct libraries to get `oc` working for you.

As the set of libraries could evolve over time, I plan to just link to the appropriate openshift/origin doc for any how-to's

If you are interested in tracking, I went ahead and opened https://github.com/openshift/origin/issues/19882

**Comment by ll911** [comment]
`withEnv(["PATH+OC=${ocDir}"]) ` only works for master node, slave node download oc fine, but still defaults to use `/bin/oc`
slave using jenkins official docker image `jenkins/jnlp-slave`
```
Unpacking https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz to /home/jenkins/tools/com.openshift.jenkins.plugins.OpenShiftClientTools/oc3.11 on maven
[Pipeline] withEnv
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.51.124.1/172.51.124.1:37962
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1059)
		at hudson.Launcher$ProcStarter.start(Launcher.java:455)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:196)
		at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:128)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Caused: java.io.IOException: Cannot run program "/bin/oc" (in directory "/home/jenkins/workspace/Router_dev"): error=2, No such file or directory
```
