### ISSUE TITLE
Potential race condition when using multibranch and newBuild

### ISSUE THREAD

**Issue by jcpowermac** [openshift/jenkins-client-plugin#16]
When using [workflow multibranch plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin) with newBuild a potential race can occur.  If more than one build starts simultaneously the Dockerfile's base image could be added as an ImageStream twice - which will result in an error since the IS already exists.

Example of this issue using `oc new-build` from cli.
```
jcallen@jcallen ~                                                                                                                 [10:47:12] 
> $ oc new-build -D $'FROM centos\nRUN yum install -y vim wget curl zsh' --name master; oc new-build -D $'FROM centos\nRUN yum install -y vim wget curl zsh' --name foo
--> Found Docker image a8493f5 (2 weeks old) from Docker Hub for "centos"

    * An image stream will be created as "centos:latest" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "master:latest"
      * Every time "centos:latest" changes a new build will be triggered

--> Creating resources with label build=master ...
    imagestream "centos" created
    imagestream "master" created
    buildconfig "master" created
--> Success
    Build configuration "master" created and build triggered.
    Run 'oc logs -f bc/master' to stream the build progress.
--> Found Docker image a8493f5 (2 weeks old) from Docker Hub for "centos"

    * An image stream will be created as "centos:latest" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "foo:latest"
      * Every time "centos:latest" changes a new build will be triggered

--> Creating resources with label build=foo ...
    error: imagestreams "centos" already exists
    imagestream "foo" created
    buildconfig "foo" created
--> Failed
```
An optional resolution of this issue that I have tested is to use Jenkin's [lockable resources plugin](https://wiki.jenkins-ci.org/display/JENKINS/Lockable+Resources+Plugin) for example:
https://github.com/jcpowermac/ojalloy/blob/master/vars/newBuildOpenShift.groovy#L25

**Comment by gabemontero** [comment]
at first blush this seems to be a generic openshift issue and not something specific to the jenkins-client-plugin, though certainly the jenkins specific workaround @jcpowermac could be a tactical workaround if addressing this in origin is problematic.

@bparees - agree? thoughts?

**Comment by bparees** [comment]
yeah this is a general problem and @oatmealraisin is actually working on a fix already:
https://github.com/openshift/origin/issues/13169

closing in deference to that issue.
