### ISSUE TITLE
Race Condition in CurrentContext switching causes Null Pointer Exception

### ISSUE THREAD

**Issue by dbenoit17** [openshift/jenkins-client-plugin#163]
When using the Openshift DSL object from multiple threads, termination of the first thread sets the global class variable `currentContext` to `lastContext`.  In many cases this causes `currentContext` to be reset to `null` before the termination of subsequent threads, leading to a null pointer exception the next time the DSL object's `run()` method is called.

https://github.com/openshift/jenkins-client-plugin/blob/6485c4fd2507aac3977f967334d6d819b472e714/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L72

https://github.com/openshift/jenkins-client-plugin/blob/6485c4fd2507aac3977f967334d6d819b472e714/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L119-L127

A potential solution could be to instantiate new copies of the DSL object in calls to `context.run()`, and pass the body closure to the new DSL object.  In theory this could preserve the behaviour of returning to the previous context at the end of the call, while also eliminating the need to share state between threads.

**Comment by gabemontero** [comment]
hey @dbenoit17 - yep, I think you and your team have correctly zero'ed in here.  And in hindsight, our existing samples and regression testing are light in the parallel threading piece (though multi-threaded, concurrency type flows in groovy and pipelines in general seems adventuresome to me ;-) )

And yeah, fix insertion either in the run method or in the constructor seems at first blush ... I'm leaning more toward the constructor side, but am still evaluating.

In the meantime, would you all be able to provide some example skeletons of pipelines, groovy snippets, of what you are currently doing.  I certainly got a workable gist from you description here and the email you sent.  Just want to make sure I don't lose anything in translation.

thanks

**Comment by dbenoit17** [comment]
We're currently working on a pipeline for running tests on multiple CPU architectures.  Our pipeline [deploys these tests in parallel](https://github.com/dbenoit17/multiarch-ci-libraries/blob/virt-containers/src/com/redhat/multiarch/ci/test/MultiArchTest.groovy#L45), so they run on all target arches simultaneously.

Our current version of the tool provisions bare metal systems directly, but since we host our Jenkins instance in an Openshift cluster, we are adding support to run these tests in libvirt-containers with KubeVirt.  We are using the Openshift Jenkins Plugin to provision and manage the testing life-cycle of these containerized VMs.

The error we are seeing with the Openshift plugin always happens in the same place.  While [waiting for the containerized VMs to boot](https://github.com/dbenoit17/multiarch-ci-libraries/blob/virt-containers/src/com/redhat/multiarch/ci/provisioner/Provisioner.groovy#L319), the DSL object's `run()` method is almost guaranteed to be called from another thread before the current invocation terminates.  When this happens, the sleeping thread usually finishes last, and expects the state of the DSL object to have remained constant.  If the body closure doesn't immediately return, it will finish it's execution with an unexpected `null` context (or perhaps in some cases a context which is not null, but nonetheless different from expected), because it was reset by another thread.

In our case, the [next item which is called](https://github.com/dbenoit17/multiarch-ci-libraries/blob/virt-containers/src/com/redhat/multiarch/ci/provisioner/Provisioner.groovy#L323) after the context resets is the DSL's `raw()` method.  The exact point of failure comes when the DSL object calls its `getServerUrl()` method internally, with the following error:

```
java.lang.NullPointerException: Cannot invoke method getServerUrl() on null object
```

**Comment by gabemontero** [comment]
OK yeah that detail was very helpful.

If anything, it looks simpler than I expected ... I was was wondering if you were connecting to multiple clusters simultaneously.

Hitting some expected groovy in jenkins pain with my fix ... will report back when I've gotten past that.

**Comment by gabemontero** [comment]
Yeah cloning a new DSL object just isn't going to cut it.  The openshift ref in the Closure body is the original OpenShiftDSL object, and it bypasses our new OpenShiftDSL object.

I think I'm going to have to build some shared state with some form thread specific indexing.

Also ...@bparees FYI just in case ... don't remember if you are watching all activity in this repo.

**Comment by bparees** [comment]
> Also ...@bparees FYI just in case ... don't remember if you are watching all activity in this repo.

I am, but i don't have much to offer these days :)

**Comment by gabemontero** [comment]
The fun is growing ... closures appear to be on separate threads (not too surprising I suppose in hindsight) .... so our `watch` and `untilEach` functions can't just use their (newly created) thread id to pick up an Contexts stored during enty into `with...` as the thread is will be different.

**Comment by gabemontero** [comment]
Hoping closure owners/delegates work as advertised ....

**Comment by gabemontero** [comment]
OK the owners/delegates foray was fruitless, but I believe I've sorted out the per thread state on the `with...`  calls with our selector's watches running on different threads.

@dbenoit17  - I've installed my new version of the plugin on the jenkins instance you pointed me to in our email thread.  But I can't initiate a new run, given the use of multibranch, etc.

Could you do whatever is necessary to initiate a run?  If there are still problems I'll log back into the system and check out the logs, etc.

**Comment by gabemontero** [comment]
So I was unable to uncover a lot of angst around locking in pipelines (stackoverflow, registered JIRA requests..)

Basically, the only way is by leveraging this plugin external to the pipeline suite of plugins:  https://wiki.jenkins.io/display/JENKINS/Lockable+Resources+Plugin

It looks like from pipelines you don't need additional config (though you do need it elsewhere with non-pipelines).

I'll confirm that and start constructing the jenkins and jenkins-client-plugins pulls to protect the openshift dsl global variable as-is from parallel execution

@dbenoit17 - were you ever able to get anywhere with continuations?  If not, we'll go with the use of `lock()` along with doc'ing the behavior, etc.

**Comment by dbenoit17** [comment]
I have some preliminary macros working, but today I discovered that the functionality we really need is only present in groovy >= 2.5.  Jenkins currently ships groovy 2.4.11 in the latest pipeline plugin. 

I was planning to look tomorrow into whether it would be possible to include a local copy of the necessary libraries until Jenkins catches up.  Otherwise, locking resources to prevent parallel access is likely the best bet for a short term solution. 

Though if we can get past the groovy versioning issue, macros + continuations are looking increasingly optimistic for a solution that could see threads running in parallel without needing to wait for resources.

**Comment by gabemontero** [comment]
Thanks for the update @dbenoit17 ... does sound promising, though they have not updated the [pipelline plugin](https://wiki.jenkins.io/display/JENKINS/Pipeline+Plugin) since February of last year, so I'm a little curious as to what is going on there.

But yes, let's progress in parallel as long as you have bandwidth.

**Comment by gabemontero** [comment]
Well the immaturity of pipeline surfaces yet again.

Apparently while you can dynamically create locks from pipelines, you cannot clean them up or mark them transient so they are removed later on.  The only way to remove them is from the jenkins console, and even there, what happens is they clear the current list, and then recreate the new list.  So there is no remove of a single lock.

There is a long standing issue with a lot of interest and dialogue, but no action:  https://issues.jenkins-ci.org/browse/JENKINS-38906

This means that if we don't require the users to opt in or configure anything:
a) we have to create a truly global lock that would synchronize runs across jobs 
b) we could augment our our dynamic creation to append the job/run information, but then the locks will slowly leak and the jenkins admin has to periodically clean them up

Or we require users to configure / manage locks, and then set a flag on the `openshift` pipeline global var prior to their `openshift.withCluster` call to set the lock name to use.  So the patterns will be
a) they miss the new bit in our docs, and try using `parallel` assuming everything is OK
b) hit the race @dbenoit17 has reported
c) open an issue ... we point them to the new feature
d) everybody ends up more frustrated 

Leaning toward that last option but mulling .... also wondering about holding out a bit longer and see where @dbenoit17 lands with his upgrade groovy version (somehow only for our plugin) and leverage the newer macro/continuation capabilities.

@bparees FYI

**Comment by dbenoit17** [comment]
Good news, I have completed a simplified prototype which demonstrates that groovy's macro system is indeed powerful enough to implement this fix.  Pending our ability to bundle the groovy-macros library locally with the plugin, I am much more confident that we can probably solve this with continuations. 

Once I am able to determine whether bundling the macros library is possible, I'll work on applying the solution to the DSL object code.

**Comment by dbenoit17** [comment]
It turns out the groovy-macros module is available directly from maven, so we don't even need to attempt to ship it locally.  The only issue is that the stable release versions of the module are only compatible with groovy >= 2.5.  There are old beta versions which seem to be working with groovy 2.4.11 though.  

Perhaps the best solution would be to settle on the resource locking solution for now, and if there is still interest in continuing to develop a fully parallel solution, we could branch off and work with an older beta plugin to prepare for when Jenkins catches up to Groovy 2.5.
