### ISSUE TITLE
oc adm policy via the pipeline

### ISSUE THREAD

**Issue by gomesp** [openshift/jenkins-client-plugin#164]
I have a need to add a SCC to a service account on a specific project. Using the cli it would look like this:

```
oc adm policy add-scc-to-user sa-privileged system:serviceaccount:my-project:sa-privileged
```
With the Openshift DSL I tried using ```openshift.policy("my params here")``` but this will skip the "adm" part of the command and fail to execute what I need. According to this [code](https://github.com/openshift/jenkins-client-plugin/blob/6485c4fd2507aac3977f967334d6d819b472e714/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L889) it is a pass through, but not exactly to the command I need (please correct if I have my OCP concepts wrong).

Is there a way to run ```oc adm policy``` commands with this plugin?

Thanks!

**Comment by bparees** [comment]
For now you can use the raw oc invocation:
https://github.com/openshift/jenkins-client-plugin#i-need-more

but it sounds like we might want to add an admin flavor/wrapper that handles this for you.

**Comment by gomesp** [comment]
Awesome. I overlooked that. Thanks for pointing it out. :)
