### ISSUE TITLE
transient OpenShift.DescriptorImpl config?

### ISSUE THREAD

**Issue by tphenderson** [openshift/jenkins-client-plugin#165]
In the OpenShiftDSL.groovy file the `OpenShift.DescriptorImpl config` variable is set to transient so if Jenkins restarts while a pipeline is running, the openshift commands fail because `config` is now `null`. Is there a reason why it is set to transient? Is there a way to reload the config on Jenkins restarts so subsequent openshift calls do not fail?

**Comment by gabemontero** [comment]
That decision pre-dates my maintainer status, but most likely it has to do with OpenShiftDSL being Serializable the the Descriptor stuff is not ... though is is "Saveable".

I'll research with the plugin originator to confirm, and see if there is a fix-level solution, or if supporting continuation on restart will be a feature level change.

@bparees fyi
