### ISSUE TITLE
Do you call this documentation? ;-)

### ISSUE THREAD

**Issue by codrinbucur** [openshift/jenkins-client-plugin#168]
Is it possible to have a rendered page/wiki where the docs for the DSL syntax of this plugin are searchable and able to copy/paste from/to?

https://github.com/openshift/jenkins-client-plugin/blob/master/src/readme/images/jenkins-online-help.png
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/pipeline/OpenShiftGlobalVariable/help.jelly

Even better, add that page/wiki to the OpenShift docs, maybe here:
https://docs.openshift.com/container-platform/3.9/dev_guide/dev_tutorials/openshift_pipeline.html#the-jenkinsfile

Going through the Jenkins UI to find the syntax is absolutely difficult and painful.

Thanks
-Codrin

**Comment by gabemontero** [comment]
@bmcelvee - any chance you would be able to take the content from this repo that @codrinbucur is referring to and incorporate it to the OpenShift docs?

**Comment by gabemontero** [comment]
bump @bmcelvee
