### ISSUE TITLE
Plugin does not read correct Openshift variables when running on a Jenkins slave node

### ISSUE THREAD

**Issue by markperdue** [openshift/jenkins-client-plugin#169]
Hello,

I am running into an issue using the `openshift.withCluster()` method when no parameters are provided to a declarative pipeline running on a Jenkin's slave node using redhat's `registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7:v3.10.14-7` docker image.

I followed the documentation at https://github.com/openshift/jenkins-client-plugin#configuring-an-openshift-cluster to trigger the plugin to try to auto discover the correct information but the issue seems to arise because the plugin seems to use `System.getenv()` to discover `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT_HTTPS` which are not generally available that way when running on a Jenkin's slave node.

The documentation does say that `env.KUBERNETES_SERVICE_HOST` is used in discovery but the following two links shows `System.getenv()` being used which returns `null` for the values.

https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/ClusterConfig.java#L105
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/ClusterConfig.java#L110

I have a workaround in place that passes `withCluster()` with the correct values below but a fix to allow `withCluster()` to work without parameters from within the jenkins slave image would be nice. `openshift.withCluster("https://${env.KUBERNETES_SERVICE_HOST}:${env.KUBERNETES_SERVICE_PORT_HTTPS}")`

**Comment by markperdue** [comment]
Version info for the above:
OpenShift Client plugin v1.0.9 running on Jenkins 2.89.4
OpenShift v3.9

**Comment by gabemontero** [comment]
Hey @markperdue 

You description of the scenario at least sounds just like our https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml sample, which is run nightly as part of our regression test suite, and has been passing for quite a while, though that is at the latest levels of this plugin (and I don't recall prior bug fixes in this area).

Could you either provide your pipeline, so I can compare/contrast, or if you can compare/contrast and at least provide any differences between the two, that could provide some clues.

If there are no differences in the pipelines, I'll see about attempting a run with the pipeline above at v3.9/v1.0.9/v2.89.4.  Or we can see what happens if you pull in the latest version of the plugin perhaps.

**Comment by markperdue** [comment]
Hey @gabemontero 

I updated the openshift client plugin we are running to the 1.0.14 version and am still seeing the same error behavior. I've attached a sample pipeline that shows the error for when the `withCluster()` option is not set as a secondary stage in the pipeline.

Our Jenkins instance is not running within OpenShift but as an external Jenkins instance that is using the Kubernetes Pod Template to spin up registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7:v3.10.14-7 and attach it as a slave node within Openshift that is assigned work using the label 'jenkins-agent-nodejs.' Would this setup prevent the openshift client plugin from detecting the setup properly?

Strangely, replacing the openshift client plugin calls with `sh 'oc ***'` commands work without defining the cluster.

Jenkinsfile
```groovy
node('jenkins-agent-nodejs') {
    deleteDir()

    stage('working stage') {
        try {
            timeout(time: 10, unit: 'MINUTES') {
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/ca.crt'
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/namespace'
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/token'
                sh 'env | grep KUBERNETES_SERVICE_HOST'
                println "env.VAR version set - ${env.KUBERNETES_SERVICE_HOST} as well as VAR ${KUBERNETES_SERVICE_HOST}" // These exists
                openshift.withCluster("https://${env.KUBERNETES_SERVICE_HOST}:${env.KUBERNETES_SERVICE_PORT_HTTPS}") {
                    echo "Hello from ${openshift.cluster()}'s default project: ${openshift.project()}"  // This works
                }
            }
        } catch (err) {
            println err
        }
    }

    stage('failing stage') {
        try {
            timeout(time: 10, unit: 'MINUTES') {
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/ca.crt'
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/namespace'
                sh 'ls -la /run/secrets/kubernetes.io/serviceaccount/token'
                sh 'env | grep KUBERNETES_SERVICE_HOST'
                println "env.VAR version set - ${env.KUBERNETES_SERVICE_HOST} as well as VAR ${KUBERNETES_SERVICE_HOST}" // These exists
                openshift.withCluster() {
                    echo "Hello from ${openshift.cluster()}'s default project: ${openshift.project()}"  // This fails
                }
            }
        } catch (err) {
            println err
        }
    }
}
```

And the Jenkins log
```
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Agent jenkins-agent-nodejs-8-rhel7-mwl7h is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (jenkins-agent-nodejs): 
* [jnlp] ****/jenkins-agent-nodejs-8-rhel7:v3.10.14-7(resourceRequestCpu: 700m, resourceRequestMemory: 2Gi, resourceLimitCpu: 1000m, resourceLimitMemory: 3Gi)

Running on jenkins-agent-nodejs-8-rhel7-mwl7h in /tmp/workspace/****
[Pipeline] {
[Pipeline] deleteDir
[Pipeline] stage
[Pipeline] { (working stage)
[Pipeline] timeout
Timeout set to expire in 10 min
[Pipeline] {
[Pipeline] sh
[bug] Running shell script
+ ls -la /run/secrets/kubernetes.io/serviceaccount/ca.crt
lrwxrwxrwx. 1 root root 13 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/ca.crt -> ..data/ca.crt
[Pipeline] sh
[bug] Running shell script
+ ls -la /run/secrets/kubernetes.io/serviceaccount/namespace
lrwxrwxrwx. 1 root root 16 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/namespace -> ..data/namespace
[Pipeline] sh

[bug] Running shell script
+ ls -la /run/secrets/kubernetes.io/serviceaccount/token
lrwxrwxrwx. 1 root root 12 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/token -> ..data/token
[Pipeline] sh
[bug] Running shell script
+ env
+ grep KUBERNETES_SERVICE_HOST
KUBERNETES_SERVICE_HOST=10.45.0.1

[Pipeline] echo
env.VAR version set - 10.45.0.1 as well as VAR 10.45.0.1
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] echo
Hello from https://10.45.0.1:443's default project: cicd
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (failing stage)
[Pipeline] timeout
Timeout set to expire in 10 min
[Pipeline] {
[Pipeline] sh
[bug] Running shell script
+ ls -la /run/secrets/kubernetes.io/serviceaccount/ca.crt
lrwxrwxrwx. 1 root root 13 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/ca.crt -> ..data/ca.crt
[Pipeline] sh

[bug] Running shell script
+ ls -la /run/secrets/kubernetes.io/serviceaccount/namespace
lrwxrwxrwx. 1 root root 16 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/namespace -> ..data/namespace
[Pipeline] sh
[bug] Running shell script

+ ls -la /run/secrets/kubernetes.io/serviceaccount/token
lrwxrwxrwx. 1 root root 12 Aug  9 18:29 /run/secrets/kubernetes.io/serviceaccount/token -> ..data/token
[Pipeline] sh
[bug] Running shell script
+ env
+ grep KUBERNETES_SERVICE_HOST
KUBERNETES_SERVICE_HOST=10.45.0.1
[Pipeline] echo
env.VAR version set - 10.45.0.1 as well as VAR 10.45.0.1
[Pipeline] _OcContextInit
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
java.lang.IllegalStateException: No clusterName information specified and unable to find `KUBERNETES_SERVICE_HOST` environment variable.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by gabemontero** [comment]
On Thu, Aug 9, 2018 at 3:33 PM, Mark Perdue <notifications@github.com>
wrote:

> Hey @gabemontero <https://github.com/gabemontero>
>
> I updated the openshift client plugin we are running to the 1.0.14 version
> and am still seeing the same error behavior. I've attached a sample
> pipeline that shows the error for when the withCluster() option is not
> set as a secondary stage in the pipeline.
>
> Our Jenkins instance is not running within OpenShift but as an external
> Jenkins instance that is using the Kubernetes Pod Template to spin up
> registry.access.redhat.com/openshift3/jenkins-agent-
> nodejs-8-rhel7:v3.10.14-7 and attach it as a slave node within Openshift
> that is assigned work using the label 'jenkins-agent-nodejs.' Would this
> setup prevent the openshift client plugin from detecting the setup properly?
>
Ah, yes that is a key difference, and most likely has a key bearing in that
the API we are using in our Java code for the default case is most likely
not properly seeded in that scenario.
Probably need to use one of the hudson Computer APIs or some such.

Now that I can easily reproduce with your sample, I can experiment with the
Jenkins API until I can get the value reliably in both scenarios.

thanks @markperdue

**Comment by gabemontero** [comment]
OK, I've confirmed that the sample pipeline from @markperdue works when I run jenkins *WITHIN* and OpenShift pod, but fails when I run jenkins *STANDALONE*, i.e. outside of OpenShift.

I'll now see if I can find the Jenkins API that allows me to find the env's in the failing case.

**Comment by markperdue** [comment]
Thanks for verifying @gabemontero. Let me know if I can provide anything else to assist.

**Comment by gabemontero** [comment]
I'm cutting v1.0.15 of the plugin to include the fix
