### ISSUE TITLE
add new labels on namespace

### ISSUE THREAD

**Issue by gitkent** [openshift/jenkins-client-plugin#173]
Hi, I am trying to add new label on namespace object but I got this error:
... ...
java.lang.NullPointerException: Cannot set property 'TEAM' on null object
	at org.codehaus.groovy.runtime.NullObject.setProperty(NullObject.java:80)
... ...

This is my snippet:
...
openshift.withCluster( "https://${prodopenshifturl}" ){
            try {
              openshift.withCredentials("${usertoken}") {
                openshift.withProject("auto-05") {
                newProject = openshift.selector("namespaces/auto-05").object()
                echo "${newProject.metadata.name}"
                newProject.metadata.labels["TEAM"]="test"
                openshift.apply(newProject)
...

bear in mind that by default, a namespace object doesn't comes with any label at all when it first create. After I labelled it once manually:

oc label namespace auto-05 test=first

All subsequent pipeline builds succeeded without error and new label got created as well.

**Comment by gitkent** [comment]
This issue can be closed. I'd managed to label it with Selector.label() 

openshift.selector("namespaces/auto-05").label([ TEAM : "test" ], "--overwrite")

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] add new labels on namespace (#173)"
gesendet am 27.08.2018 23:53:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] add new labels on namespace (#173)"
gesendet am 28.08.2018 01:04:36.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
