### ISSUE TITLE
Resource selector exists() operation not covered in the documentaion

### ISSUE THREAD

**Issue by saikirandusari** [openshift/jenkins-client-plugin#178]
I know, we have a **exists()** operation on a resource selector but this is not well documented here. Would be great if we can add a small snippet explaining about the **exists()** operartion.

I have got a small shared library to determine if a resource exists.

`def call(Map config) {
    script {
        openshift.withCluster(config.cluster) { openshift.withProject(config.project) {
          def credentials = config.credentials ? config.credentials : openshift.raw('whoami -t').out.trim()
          openshift.withCredentials(config.credentials) {
            def resourceSelector
            def isResourceExists = false
            try {
              log.info "resourceType:resourceName = ${config.resourceType}:${config.resourceName}"
              resourceSelector = openshift.selector("${config.resourceType}", "${config.resourceName}")
              log.info "resourceSelector ${resourceSelector}"
              isResourceExists = resourceSelector.exists()
              log.info "isResourceExists: ${isResourceExists}"
              if(isResourceExists){
                  resourceSelector.describe()
              }
            } catch (err) {
              log.info "${config.resourceName} project does not exists"
            }
            return isResourceExists
          }
        }}
    }
}`

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] Resource selector exists() operation not
covered in the documentaion (#178)" gesendet am 12.09.2018 03:15:43.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Resource selector exists() operation not
covered in the documentaion (#178)" gesendet am 13.09.2018 18:41:56.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
