### ISSUE TITLE
selector with multiple labels 

### ISSUE THREAD

**Issue by Val94** [openshift/jenkins-client-plugin#181]
Hello, 

i am not sure if it's really supported but i found in the source of the DSL :
OpenShiftDSL.groovy(580): "selector("dc", [ alabel: 'avalue' ]) // Selects using label values"

I try to use a selector with a map of labels like this :
openshift.selector("dc", [param1: 'val1, param2: 'val2']

The DSL translates like this :
get secret -l param1=val1,param2=val2 -o=name
but not secrets was found.

The correct syntax is :
get secret -l param1=val1 -l param2=val2 -o=name

jenkins version : 2.121.2
plugin version : 1.0.16
oc CLI version: v3.5.5.24 or v3.6.173.0.21

Regards,

**Comment by gabemontero** [comment]
Hey @Val94 

Per https://github.com/openshift/jenkins-client-plugin#overview this plugin minimally requires v3.7 of openshift.

Yeah, the `oc` binary changed between 3.5/3.6 and 3.7 such that the processing for supplying labels to the `get` verb changed.
