### ISSUE TITLE
untilEach upon return true terminates parallel unit test stage

### ISSUE THREAD

**Issue by valdestrijus** [openshift/jenkins-client-plugin#183]
Hi,

Ran into very strange bug.

Pipeline looks something like this:
```groovy
//build.groovy
call () {
     openshift.withProject(project) {
            def builds = openshift.selector('bc', [ app: params.APP_NAME ])
            def build = null
            def buildObjects = builds.objects()
            def buildErrorLog = "Build Error"
            def imageName = config.imageName

            for (obj in buildObjects) {
                obj.spec.output.to.name = imageName
                openshift.apply(obj)
            }

            builds.withEach {
                build = it.startBuild()
            }

            timeout(100) {
                build.untilEach {
                    def phase = it.object().status.phase

                    if (phase == 'Complete') {
                        return true // when this is returned it kills unit test step which is parallel
                    } else if (phase == 'Failed') {
                        currentBuild.result = 'FAILURE'
                        buildErrorLog = it.logs().actions[0].err
                        return true
                    } else {
                        return false
                    }
                }
            }

            if (currentBuild.result == 'FAILURE') {
                error(buildErrorLog)
                return
            }

            echo "Tagging ${imageName} as: ${openshift.project()}/${params.APP_NAME}:latest"

            openshift.tag('--source=docker',
                    "${imageName}",
                    "${openshift.project()}/${params.APP_NAME}:latest")
        }
} 
...

pipeline {
        agent {
            label 'some-python-agent'
        }

       stage("Build") {
                parallel {
                    stage('Run Build') {
                        steps {
                            script {
                                build()
                            }
                        }
                    }

                    stage('Run Unit Tests') {
                        steps {
                            script {
                                sh "python runtests" // this is a bit more complex, its just example basically runing unit tests
                            }
                        }

                        post {
                            always {
                                doPost(
                                    closure:  paramsMap?.unitTest?.always ?: {}, 
                                    reporter: 'COBERTURA'
                                )
                            }
                        }
                    }
                }
            }

}
```

This is how it looks in logs:

```
09:47:57 [Run Build] Running watch closure body
09:47:57 [Run Unit Tests] [project-name-pipeline] Running shell script
09:47:57 [Run Unit Tests] + cp .env.example .env
[Pipeline] [Run Build] {
09:47:58 [Run Unit Tests] [project-name-pipeline] Running shell script
[Pipeline] [Run Unit Tests] sh
09:47:58 [Run Unit Tests] + venv/bin/python -m runtests
[Pipeline] [Run Build] readFile
[Pipeline] [Run Build] _OcAction
[Pipeline] [Run Build] readFile
[Pipeline] [Run Build] _OcAction
09:48:14 [Run Build] 
**09:48:14 [Run Build] watch closure returned true; terminating watch**
[Pipeline] [Run Build] }
[Pipeline] [Run Build] // _OcWatch
09:48:16 [Run Unit Tests] /tmp/workspace/project-name**pipeline@tmp/durable-ef3d5b21/script.sh: line 2:  1028 Terminated              venv/bin/python -m** runtests
```

As you can see once `build.untilEach` returns true, which means that build was successful, and timeout ends, it terminates parallel unit test stage.

Jenkins: Jenkins ver. 2.89.4

Plugins:
bouncycastle-api:2.16.2
ssh-agent:1.15
timestamper:1.8.10
cobertura:1.12.1
openshift-client:1.0.14
openshift-sync:1.0.24
lockable-resources:2.3

**Comment by gabemontero** [comment]
hello @valdestrijus 

We have a restriction with respect the the `parallel` step and this plugin.  See https://github.com/openshift/jenkins-client-plugin#compatibility-with-parallel-step

Essentially, the `parallel` step must
a) either be within all `openshift.with*` closures
b) or you need to our integration with lockable resources

I did not see  the actual call to the `call()` method in your example above, so could not confirm explicitly, but odd behavior like you are seeing fall into the timing issue type category we've seen with this.

Please reopen if you are still seeing issues after employing one of the workaround documented in https://github.com/openshift/jenkins-client-plugin#compatibility-with-parallel-step

**Comment by valdestrijus** [comment]
Yes so, the thing is that we are building cross cluster pipelines so we are not able to use .with{}. Other thing is, we are using lockable-resources and its working as expected:

Initialization looks like this:

```groovy
 stage("Initialize") {
                steps {
                    script {
                        // Race condition problem withCluster
                        // Seems parallel stages kills the context of openshift client
                        // therefore we are running in race condition problem of loosing the contenxt in parallel tasks
                        // 3.11 jenkins has updated openshift client plugins which uses resource-lock plugin
                        // maybe in the future when pipeline/parallels will be updated we can get rid of
                        // resource lockings
                        // https://github.com/openshift/jenkins-client-plugin/issues/163
                        resetResourceLock()
                    }
                }
            }

// resetResourceLock()

// cleans resource lockings
def call (Map parameters = [:]) {
        def lockName = parameters.lockName ?: env.JOB_BASE_NAME
        def manager = org.jenkins.plugins.lockableresources.LockableResourcesManager.get()
        def resources = manager
            .getResources()
            .findAll{
                !it.locked && it.name.contains(lockName)
            }
        
        resources
            .each{
                manager.getResources().remove(it)
            }
        
        manager.save()
}

```
Each time we run new pipeline we clean up resource lockings in intialization stage.

**Comment by gabemontero** [comment]
OK glad the lockable resource workaround is working as expected.

I like your clean up logic.  If you don't mind, I may see about updating our doc to provide a form of it as a reference.

thanks

**Comment by valdestrijus** [comment]
OK no problem, if it helps.

So I am still thinking that this is somehow related with sync plugin, as in our case unit test and build stage is completely unrelated, we are not using OpenshiftAPI to run unit tests and they are running on jenkins agent.

Right now the workaround make unit test stage non parallel.

**Comment by TomSchmitz** [comment]
Ich bin bis 08.10.2018 abwesend.
I am out of the office until 08.10.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] untilEach upon return true terminates
parallel unit test stage (#183)" gesendet am 03.10.2018 06:20:18.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
On Wed, Oct 3, 2018 at 12:20 AM valdas <notifications@github.com> wrote:

> OK no problem, if it helps.
>
cool

> So I am still thinking that this is somehow related with sync plugin,
>
nope I have seen this without the sync plugin...it has to do with my
explanation in the readme

> as in our case unit test and build stage is completely unrelated, we are
> not using OpenshiftAPI to run unit tests and they are running on jenkins
> agent.
>
> Right now the workaround make unit test stage non parallel.
>
given your restrictions wrt when to call openshift.with* yes we know

You can always call oc directly via the sh step
