### ISSUE TITLE
version 1.0.18: error processing the template

### ISSUE THREAD

**Issue by TomSchmitz** [openshift/jenkins-client-plugin#184]
Hello,

after updating the plugin to version 1.0.18 we get an error during processing the template.

we have the following code to process the template (
[Template.yml.txt](https://github.com/openshift/jenkins-client-plugin/files/2434180/Template.yml.txt)
):
`openshift.process(steps.readFile(file:"Template.yml"), "-p=LIVENESS_INITIAL_DELAY_SECONDS=120 -p=READYNESS_INITIAL_DELAY_SECONDS=80 -p=JVMARGS="-Xmx768m -Dmy.sys.param=aete" -p=APPNAME=verify -p=DEPLOYMENTTAG=aete -p=ROLLING_TIMEOUT_SECONDS=400 -p=NAMESPACE=grape-regtest-tools-aete")`

with version 3.5 of the oc CLI we get the following exception:
[Exception_oc35.txt](https://github.com/openshift/jenkins-client-plugin/files/2434184/Exception_oc35.txt)

with version 3.6 and 3.7 of the oc CLI we get another exception:
[Exception_oc36-37.txt](https://github.com/openshift/jenkins-client-plugin/files/2434190/Exception_oc36-37.txt)

With version 1.0.16 of the openshift jenkins client plugin processing of the template above works just fine.

If you need more info, just let me know.

Thank you for help
Tom

**Comment by gabemontero** [comment]
hello @TomSchmitz 

I created you template in my namespace tried a pipeline that copy/pasted the `openshift.process(...` invocation from your description (replacing the read file with referencing the template name), in other words:

`def objs = openshift.process("grape-spring-boot", "-p=LIVENESS_INITIAL_DELAY_SECONDS=120 -p=READYNESS_INITIAL_DELAY_SECONDS=80 -p=JVMARGS="-Xmx768m -Dmy.sys.param=aete" -p=APPNAME=verify -p=DEPLOYMENTTAG=aete -p=ROLLING_TIMEOUT_SECONDS=400 -p=NAMESPACE=grape-regtest-tools-aete")`

and got a groovy parsing error, with no invocation of this plugin ... that is what I would expect based on general groovy handling of `"` ... and of course Jenkins complains about this format regradless of whether I had v1.0.16 or v1.0.18.

I then escaped the `"` with `\` for `-p=DATABASE_SERVICE_NAME="-Xmx768m -Dmy.sys.param=aete"`  .... changing it to `-p=DATABASE_SERVICE_NAME=\"-Xmx768m -Dmy.sys.param=aete\"`, and the process worked correctly

And got one of the errors you noted.

So for now, I'm assuming what you literally posted in the description is not what existed in your pipeline, and we can go from there.  But chime in as needed here.

I think I might have a handle on how to address.

A possible short term work around for you ... split each `-p=<parm name>=<param value>` into a separate parameter into `openshift.process(...)`

i.e. this worked for me:


`def objs = openshift.process("grape-spring-boot", "-p=LIVENESS_INITIAL_DELAY_SECONDS=120", "-p=READYNESS_INITIAL_DELAY_SECONDS=80", "-p=JVMARGS=\"-Xmx768m -Dmy.sys.param=aete\"", "-p=APPNAME=verify", "-p=DEPLOYMENTTAG=aete", "-p=ROLLING_TIMEOUT_SECONDS=400", "-p=NAMESPACE=grape-regtest-tools-aete")`

**Comment by TomSchmitz** [comment]
Ich bin bis 08.10.2018 abwesend.
I am out of the office until 08.10.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] version 1.0.18: error processing the
template (#184)" gesendet am 04.10.2018 21:18:16.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
