### ISSUE TITLE
Can you push tags for releases?

### ISSUE THREAD

**Issue by svenstaro** [openshift/jenkins-client-plugin#190]
It would be nice for reference and packaging purposes if you tagged a git commit for every specific plugin version that you release.

**Comment by szpak** [comment]
It would be definitely useful, also to get notification from GitHub about a new version released.

**Comment by bparees** [comment]
You can find releases in the official jenkins repo for this plugin which is what is used to cut the actual releases we ship:

https://github.com/jenkinsci/openshift-client-plugin/releases

is that sufficient?

**Comment by bparees** [comment]
(you should consider this repo the upstream development repo for the official plugin)

**Comment by szpak** [comment]
@bparees Thanks, I confused the repositories. The tags and releases are enough for me to get notifications (although, if there is no technical issues with that, they could be also pushed to that repo to keep them (the repositories) more like a mirror).
