### ISSUE TITLE
OC params passed are not working as it is in the previous version (1.0.17)

### ISSUE THREAD

**Issue by manjeet88** [openshift/jenkins-client-plugin#195]
Hi,

We are getting errors while passing the params to openshift.process() method, previous plugin version 1.0.17, following syntax was working fine 

>  
     parameters = APPLICATION_NAME=management-service 
     REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12
     openshift.withCredentials(cred) {
                openshift.withCluster(cluster) {
                    openshift.withProject(project) {
                        if (openshift.selector('bc', appName).exists()) {
                            println 'deleting existing buildconfig for ' + appName
                            openshift.selector('bc', appName).delete()
                        }
                        def yml = "${templateTargetDir}/templates/builders/${template}.yml"
>                      def models = openshift.process(readFile(yml), '-p', parameters)

                        def created = openshift.create(models)
                        return openshift.selector('bc', appName).startBuild("--from-dir=${distDir}", "--wait")
                    }
                }
            }

But the same code fails with the new plugin (1.0.21) with following error:

> The BuildConfig "management-service REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12" is invalid: 
>  metadata.name: Invalid value: "management-service REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
>  metadata.labels: Invalid value: "management-service REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12": must be no more than 63 characters
>  metadata.labels: Invalid value: "management-service REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
> spec.output.to.name: Invalid value: "mobile-docker-1.repos.fismobile.com/test/management-service REGISTRY_URL=docker.repos.xyz.com/abc OUTPUT_IMAGE_TAG=1.0.0-18a2e12:latest": name is not a valid Docker pull specification: invalid reference format

Once we change the parameters and code like the following, it works fine

> 
          parameters = APPLICATION_NAME=management-service -p 
          REGISTRY_URL=docker.repos.xyz.com/abc -p OUTPUT_IMAGE_TAG=1.0.0-18a2e12
          openshift.withCredentials(cred) {
                openshift.withCluster(cluster)](url) {
                    openshift.withProject(project) {
                        if (openshift.selector('bc', appName).exists()) {
                            println 'deleting existing buildconfig for ' + appName
                            openshift.selector('bc', appName).delete()
                        }
                        def yml = "${templateTargetDir}/templates/builders/${template}.yml"
>                      def models = openshift.process(readFile(yml), parameters)

                        def created = openshift.create(models)
                        return openshift.selector('bc', appName).startBuild("--from-dir=${distDir}", "--wait")
                    }
                }
            }

This seems to be inconsistent from the previous version of plugin. Could someone please check and suggest if there is something wrong with the our code implementation or the new plugin accepts the parameters in different format.

**Comment by gabemontero** [comment]
Hi @manjeet88 

Yeah there were several issues with the v1.0.17 version of the plugin (and perhaps earlier) that generally caused problems, but in your case, it looks like it let an unsupported specification work as you expected.

This plugin in general intends to map directly to the options supported in the `oc` binary.

Per the help text there:

`-p, --param=[]: Specify a key-value pair (eg. -p FOO=BAR) to set/override a parameter value in the template.`

The key there is "a key-value pair" ...i.e. a single key-value pair.

prefacing each of your params with `-p` is what is expected ... please continue to use that approach.

thanks

**Comment by manjeet88** [comment]
thanks @gabemontero  for the confirmation
