### ISSUE TITLE
Error when running Moving Images Cluster to Cluster

### ISSUE THREAD

**Issue by dunse** [openshift/jenkins-client-plugin#196]
I'm testing out the oc image mirror in an OpenShift cluster, but facing some issues when following the instructions.

Got a Jenkins files as:
```
pipeline{
    agent { label 'maven' }
    stages {
        stage('Move Image') {
            steps {
            	withDockerRegistry([credentialsId: "secret-creds", url: "https://registry.hub.docker.com"]) {
                    	sh """
                        	echo works
                      	"""
                 }
             }
        }
    }
}
```

Running it fails on missing docker command as:
```
* [jnlp] docker.io/openshift/jenkins-agent-maven-35-centos7:v3.10(resourceRequestCpu: , resourceRequestMemory: , resourceLimitCpu: , resourceLimitMemory: )

Running on maven-93w3m in /tmp/workspace/a/b
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Cloning the remote Git repository
...
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Move Image)
[Pipeline] withDockerRegistry
$ docker login -u ****** -p ******** https://registry.hub.docker.com
[Pipeline] // withDockerRegistry
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
....
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Caused: java.io.IOException: Cannot run program "docker": error=2, No such file or directory
```

This runs in a Pipeline configured with provided Jenkins in OpenShift v3.10. All plugins has been updated.
Would it be possible to document the additional steps required?

**Comment by bparees** [comment]
the docker binary+daemon isn't available in your agent image.  The purpose of the docker login operation is to construct a valid .docker/config.json file which oc image mirror consumes so it can authenticate with the source+target registries.

So in your case you would need to construct/supply the .docker/config.json file directly, since you cannot invoke docker login to construct it (because running the daemon inside the agent image is likely to prove problematic)

**Comment by bparees** [comment]
I am providing clarifying documentation in the oc image mirror command:
https://github.com/openshift/openshift-docs/pull/12702

**Comment by gabemontero** [comment]
thanks @bparees 

I'll update the README in this repo to add/reference the clarifying information you've provided
