### ISSUE TITLE
Is there anyway to wait for a StatefulSet to be ready?

### ISSUE THREAD

**Issue by robpblake** [openshift/jenkins-client-plugin#199]
It seems that `oc` doesn't have support for StatefulSets so I'm struggling to work out how to wait for my StatefulSet to be "ready".

If I was using a DeploymentConfig, then I would of course be using `deploymentConfig.rollout().status()` to wait for the result of the rollout. How can I determine and wait for the result of my StatefulSet deployment?

**Comment by bparees** [comment]
This seems like a kube/origin question, not a client plugin question.

**Comment by mliker** [comment]
Well the plugin does not seem to know of the resource statefulset

openshift.selector("statefulset", "mongodb").related('pods').untilEach(1) results in 
`ERROR: Unknown how to find resources related to kind: statefulset`

It seems these are all the resources this plugin can work with:

https://github.com/openshift/jenkins-client-plugin/blob/437261e8808177c0cc8028d158d72cde54f4d182/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L84

https://github.com/openshift/jenkins-client-plugin/blob/437261e8808177c0cc8028d158d72cde54f4d182/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1756

okd 3.11, jenkins from the template and updated to the laster version of all the plugins.
