### ISSUE TITLE
Parallel Connections.

### ISSUE THREAD

**Issue by JuniorCtba** [openshift/jenkins-client-plugin#202]
Can i use this plugin running in multiples jobs and nodes in parallel?

How to avoid to have mixed context between the oc client in the same time of use

**Comment by gabemontero** [comment]
You have to have withCluster inside the parallel step ... see https://github.com/openshift/jenkins-client-plugin#compatibility-with-parallel-step

**Comment by JuniorCtba** [comment]
I am not saying to use the parallel in the same job, i would like to use in many job in the same time.

**Comment by gabemontero** [comment]
On Tue, Dec 4, 2018 at 12:07 PM Junior <notifications@github.com> wrote:

> I am not saying to use the parallel in the same job, i would like to use
> in many job in the same time.
>
you can do that
