### ISSUE TITLE
Documentation of Version Changes

### ISSUE THREAD

**Issue by mmkonrad** [openshift/jenkins-client-plugin#210]
Hello together,

I feel the need to open yet another issue, requesting a documentation of changes in your releases or directions to such in case it already exists.

At the moment we are using the plugin in version 1.0.16 and get recommendations for 1.0.23. We already did an upgrade but had to roll back because all of a sudden our pipelines failed due to the inability of the plugin to process templates anymore. Additionally there have been some other issues which I am unable to recall at the moment (I have to look them up if required).

To figure out what has changed and at what point our usage of your plugin has to be adjusted we need to know what has changed and what has to be considered when updating.
Therefore I ask you for the approporiate documentation or directions to an existing one.

**Comment by mmkonrad** [comment]
I know this is an open source project, but can you tell me if this issue made your to-do list and what an approximate schedule could be?

**Comment by akram** [comment]
We are closing this in favour of the fact that we have a CHANGELOG.md file now.

/close
