### ISSUE TITLE
java.io.FileNotFoundException: \tmp\ocstdout3204612150570745585.txt (The system cannot find the path specified)

### ISSUE THREAD

**Issue by Denis220795** [openshift/jenkins-client-plugin#213]
Hello,

This strange issue appears after updating the plugin to any version past this commit:
https://github.com/jenkinsci/openshift-client-plugin/commit/861cb2c1cf939696a75c39568d8a9c5fea999bdb

Full stacktrace:

`java.io.FileNotFoundException: \tmp\ocstdout3204612150570745585.txt (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:167)
	at com.openshift.jenkins.plugins.pipeline.OcAction$Execution.run(OcAction.java:128)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

We have a Jenkins master on Windows and build server (agent) on Linux. This exception occurs at any action in `withProject() {...}` block, e.g openshift.raw('status'), openshift.raw('get', 'dc/example-service') etc. All steps related to the Openshift Jenkins Client plugin are executed on the agent Linux server. Requested files also created at /tmp directory with empty content successfully.

Thank you for your help.
Denis

**Comment by gabemontero** [comment]
Hey @Denis220795 

Yea there has been some churn in our process invocation to deal with a varying set of scenarios, as well as to work around some jenkins bugs.

Certainly the path noted in the exception is a windows based path, which would not be tolerated on your linux agent.

I thought when testing the recent changes I had confirmed that the FilePath we received from Jenkins was local for our agent based scenarios.  But perhaps your pipeline invokes it differently than I did.

Can you provide the actual pipeline groovy itself?  Or if there is something in your pipelines that is proprietary to you all, can you provide enough of the pipeline so that I can see how precisely you specify the node/agent prior to calling `withProject() {...}` ?

thanks

**Comment by gabemontero** [comment]
correction ... just did some digging, and the filepath is on the master 

the pipeline details I asked for previously will still help with a few other things, so please provide those if possible, but I may have a few things to go with.

That said, I don't have access to a windows jenkins master  .... would you all be able to test pre-release versions of the plugin that I could attach to this issue?

**Comment by Denis220795** [comment]
Hi @gabemontero , thanks for your quick response. 

Yes we would be able to test pre-release version if you share it here.

About the pipeline that we use:
We use shared libraries and define our pipeline in vars directory of the library, then load it before the pipeline execution and just execute it as function.

Example definition of the pipeline:

```groovy
pipeline {
    agent none
    environment {
        ....
    }
    stage('Deploy') {
        agent {
            node {
                label "LinuxServer"
                customWorkspace "/my/custom/workspace"
            }
        }
        steps {
            script {
                openshift.withCluster("ClusterName") {
                    openshift.withProject("EnvironmentName") {
                        def models = openshift.process("-f", "configFile", "--param-file", "param-file")
                        openshift.apply(models)
                        openshift.raw("rollout", "latest", "dc/example-service")
                        try {
                            timeout(5) {
                                def dc = openshift.selector("dc", "example-service")
                                // this will wait until the desired replicas are available
                                dc.rollout().status()
                            }
                        } catch (err) {
                            openshift.raw("rollout", "undo", "dc/example-service")
                            error("Deployment to EnvironmentName failed, the app and configs were rolled back to the latest successful deployment. ${err}")
                        }
                    }
                }
            }
        }
    }
}
```


Let me know if more details are needed. Yes, our pipeline is some soft of proprietary but if needed I may obfuscate some stuff and provide more complete pipeline example we use.

**Comment by donotello** [comment]
@Denis220795, @gabemontero,

Looks like we have the same issue. Were you able to figure out the root cause of find a workaround?

**Comment by gabemontero** [comment]
The changes I'm working via https://github.com/openshift/jenkins-client-plugin/pull/214 
https://github.com/openshift/jenkins-client-plugin/issues/211
and 
https://github.com/openshift/jenkins-client-plugin/issues/209

should address this

Here's a pre-release version if you'd like to try
[client-plugin-gerard-2.zip](https://github.com/openshift/jenkins-client-plugin/files/2800119/client-plugin-gerard-2.zip)

**Comment by gabemontero** [comment]
v1.0.24 of this plugin has been initiated at the update center with the fixes I noted above

After trying it if you get the same issue, please reopen

If something besides the exception occurs, please open a new issue 

thanks
