### ISSUE TITLE
-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/jenkins-client-plugin#215]
using plugin version 1.0.22

running
`openshift.exec("$podName","bash","-c","mkdir -p /etc/systemd/system/vagrant-vm.service.d/workDir/workspace")`

output
`ERROR: exec returned an error;
{reference={}, err=-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.
F0122 12:29:32.538061     622 helpers.go:119] error: invalid resource name "/etc/systemd/system/vagrant-vm.service.d/workDir/workspace": [may not contain '/']
, verb=exec, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=ember-csi --loglevel=3 --token=XXXXX exec ember-csi-c29002b6-6857-4edc-94c8-8101e1c4638c bash -c mkdir -p /etc/systemd/system/vagrant-vm.service.d/workDir/workspace , out=, status=255}`

The same functionality with a different openshift plugin works fine:
` openshiftExec(
             pod: podName,
             command: 'bash',
             arguments: ["-c", "mkdir -p /etc/systemd/system/vagrant-vm.service.d/workDir/workspace"],
            )`

**Comment by gabemontero** [comment]
Yeah the `-p` is getting associated with `oc exec` and not being included as the command to run within the pod.

To some degree I feel this is a bug in `oc` but will look into it more.

**Comment by lioramilbaum** [comment]
Will check if the '-p' in the command is the issue. Will check it with commands which doesn't have the '-p' and see if it works or not.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] -p POD_NAME is DEPRECATED and will be
removed in a future version. Use exec POD_NAME instead (#215)" gesendet am
09.02.2019 09:40:43.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
I'm also curious it changing this to

`openshift.exec("$podName","bash","-c","mkdir", "-p",  "/etc/systemd/system/vagrant-vm.service.d/workDir/workspace")`

changes the behavior for you ... we've seen some interesting "features" in how jenkins process launching handles args and how golang `oc` expects them to look

Not grouping multiple params separated by space has helped others

**Comment by lioramilbaum** [comment]
Tested the following pipeline:
`node {
    
    openshift.withCluster() {

        openshift.exec("jenkins-15-1wngp","bash","-c","mkdir", 
            "-p", "/var/tmp/workDir/workspace")
    }
`
The output:
`Running on Jenkins in /var/lib/jenkins/jobs/test/workspace
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: exec returned an error;
{reference={}, err=-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.
error: invalid resource name "/var/tmp/workDir/workspace": [may not contain '/'], verb=exec, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=ember-csi --token=XXXXX exec jenkins-15-1wngp bash -c mkdir -p /var/tmp/workDir/workspace , out=, status=1}

Finished: FAILURE
`

**Comment by gabemontero** [comment]
OK, that example helped narrow it @lioramilbaum 

Unfortunately, it appears to be a bug in the 3.11 `oc`.

See what transpired when I ran the same thing via `oc` from the command line:

```
gmontero ~/Downloads/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit $ ./oc exec jenkins-1-slppr bash -c mkdir -p /var/tmp/workDir/workspace
-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.
error: invalid resource name "/var/tmp/workDir/workspace": [may not contain '/']
gmontero ~/Downloads/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit $ 
```

Same problem.

Since the old plugin does not use `oc`, it is a different ball game wrt it working.  But this plugin is dependent on `oc` to work.

Btw I also see this with the 4.0 `oc`.

You should file an issue against https://github.com/openshift/origin
