### ISSUE TITLE
OC client stdout and stderr tmp files are not cleaned up

### ISSUE THREAD

**Issue by maikebertpsc** [openshift/jenkins-client-plugin#216]
We currently have the following environment:
- Jenkins 2.121.1
- OC command line tool 3.9.0
- jenkins-client-plugin 1.0.23

We now realized that on our Jenkins master the /tmp folder was consuming several GBs of disk space due to 100.000th of these stdout and stderr txt files.
These amount of files have been created in just 10 days.
This might be related to the fact that we use that plugin in our CI jobs all day long.

Nevertheless we expect that the plugin is cleaning up these tmp files automatically and not polluting the disk.

**Comment by gabemontero** [comment]
PR https://github.com/openshift/jenkins-client-plugin/pull/214 addresses this

Once we've completed regression testing, it will get merged and v1.0.24 of the plugin will be created.

**Comment by gabemontero** [comment]
v1.0.24 of this plugin has been initiated at the update center
