### ISSUE TITLE
verifyService does not work with headless Services

### ISSUE THREAD

**Issue by jtudelag** [openshift/jenkins-client-plugin#217]
verifyService does not work with headless Services.

Headless Services do not have clusterIPs associated, so when the method verifyService try to parse the IP, it fails.

https://github.com/openshift/jenkins-client-plugin/blob/release-3.10/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L946

**Comment by gabemontero** [comment]
interesting use case @jtudelag 

Longer term, some new support to add.  Short term, we can highlight this req/assumption in the help/readme where needed.

**Comment by waveywaves** [comment]
I would like to work on this issue @gabemontero.
Anything I need to keep in mind before I start this ?

**Comment by gabemontero** [comment]
working out how to test the headless service from within groovy / java will be the tricky part here @waveywaves 

the queries you have to make into openshift for headless require more sophistication and parsing

ultimately, if you parse the api objects correctly, you get an ip /port which you can test via socket connection like the current verifyService functionality does

and of course, you need to be able to handle either headless and non-headless services from the same method.

the details around headless service are at https://docs.openshift.com/container-platform/3.11/architecture/core_concepts/pods_and_services.html#headless-services

and before you ask ;-) .... I've never set up a headless service before ... so you get to ask question on the openshift mailing lists if you have trouble

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] verifyService does not work with headless
Services (#217)" gesendet am 01.06.2019 08:12:18.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
