### ISSUE TITLE
verifyService only works if the NameSpace is global

### ISSUE THREAD

**Issue by jtudelag** [openshift/jenkins-client-plugin#218]
The method verifyService only works if the namespace is global, so It can reach any Pod IP, no matter the NameSpace where Pods are running. 

Thats fine, but It would be good to have it documented somewhere. I haven't found it documented either here nor in the OCP docs: https://docs.okd.io/latest/install_config/configuring_pipeline_execution.html#openshift-pipeline-dsl-plugin.

**Comment by gabemontero** [comment]
the expectation is that like all the DSL for this plugin, that it is called within the context of 
```
openshift.withCluster(...) {
   openshift.withProject(...) {
   }
}
```

You would create different `withProject` closures for each namespace you needed to monitor.

This plugin's readme gets into all that, and is pointed to by the OKD/OCP docs.
