### ISSUE TITLE
expanded environment variables in raw oc invocation

### ISSUE THREAD

**Issue by thikade** [openshift/jenkins-client-plugin#22]
When using the build-step "generic oc invocation", environment variables are not expanded.

Build log output:
```
Executing: oc start-build testapp --from-dir=${OSE_BINARYBUILD_DIR} --server=https://xxxx --namespace=testapp-demo --token=XXXXX 
error: stat /var/jenkins_home/${OSE_BINARYBUILD_DIR}: no such file or directory
Client tool terminated with status: 1
```

**Comment by gabemontero** [comment]
Hi @thikade 

Per jenkinsfile references like https://jenkins.io/doc/book/pipeline/jenkinsfile/#working-with-the-environment
and 
https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md#managing-the-environment
You have to use the `env` step, and syntax like "$env.VARNAME" or "${env.VARNAME}"
Note: the double quotation marks are important and required.  Can't use single quotes.

As an example, I have the build config "frontend" created in my environment.  The following simple Jenkins files work, env.BCNAME is resolved to "frontend".
```
openshift.withCluster() {
    env.BCNAME = 'frontend'
    echo "GGM ${env.BCNAME}"
    openshift.raw('start-build', "${env.BCNAME}")
}
```

and 

```
openshift.withCluster() {
    env.BCNAME = 'frontend'
    echo "GGM ${env.BCNAME}"
    openshift.raw('start-build', "$env.BCNAME")
}
```

**Comment by thikade** [comment]
Hi @gabemontero 
Thanks a lot for the clarification and examples!

**Comment by gabemontero** [comment]
On Fri, May 19, 2017 at 9:05 AM Thomas Hikade <notifications@github.com>
wrote:

> Hi @gabemontero <https://github.com/gabemontero>
> Thanks a lot for the clarification and examples!
>
cool glad to help
