### ISSUE TITLE
openshift.selector('project') object.name() changed in plugin versino 1.0.24

### ISSUE THREAD

**Issue by maikebertpsc** [openshift/jenkins-client-plugin#221]
Until now we had plugin version 1.0.23.
In this version the following code worked as expected:
```
	def projects = openshift.selector('project')
	projects.withEach {
		if (it.name() == "projects/${ocpProjectName}") {
			println "Found existing project '${ocpProjectName}': ${it.describe()}"
		}
	}
```
Especially that object name() method returned 'projects/some-project-name'.

Since upgrading to plugin version 1.0.24 this code stopped working, because object name() does return singular project like  'project/some-project-name' instead (project VS projects).

I guess that's some kind of regression?

**Comment by gabemontero** [comment]
the changes between 1.0.23 and 1.0.24 did not change anything with respect to`project` vs. `projects` getting returned ... it solely focused on launching the `oc` process ... the ways the params were passed into `oc` and how the output from `oc` was processed was unchanged

at face value how the process was launched would not affect those

the more likely suspect is that either the `oc` version or openshift master version changed in some fashion in the interim

I'm not seeing any differences with local tests here between the 2.

that said, to see the details of the flows and confirm/deny any speculation, add `openshift.verbose(true) .... openshift.verbose(false)` around your block above and do a run each with v1.0.23 and v1.0.24, and make sure the oc/openshift envs are the same for each run.

Post the logs for each here and I'll analyze

**Comment by gabemontero** [comment]
closing out for inactivity ... please reopen if data requested in https://github.com/openshift/jenkins-client-plugin/issues/221#issuecomment-459110772 can be provided

**Comment by maikebertpsc** [comment]
The problem is in fact the upgrade from oc client 3.9 to 3.10.

This code prints different results based on the oc client version:
```
def imageStreamsSelector = openshift.selector('imagestreams')
imageStreamsSelector.withEach { imageStream ->
  def name = imageStream.name()
  println "name=$name"
}
```

3.9
name=imagestreams/pinshop

3.10
name=imagestream/pinshop
