### ISSUE TITLE
Multi-tenant security on a single Jenkins instance

### ISSUE THREAD

**Issue by maximmold** [openshift/jenkins-client-plugin#223]
We are looking to leverage a single jenkins master, but have pipelines and build configs associated to individual projects. We currently have given access to the ci serviceaccount to the other projects to be able to perform various operations with build configs, builds, and image streams, but ideally we'd like to change which service account the pipeline is running under on a per jenkins folder basis. This would help enable better multi tenant security. We also have been looking at the jenkins templates that spin up on an individual project basis, but we would prefer to manage just a single jenkins. Is this a common use case?

Glancing at the [documentation](https://github.com/openshift/jenkins-client-plugin#setting-up-credentials), it looks like we could setup credentials per project and use openshift.withCredentials to specify a token corresponding to the service account that is associated to the project.

**Comment by maximmold** [comment]
Also note that the commands don't jive with the screenshots. The spelling on prilvileged/privileged doesn't match.
`oc create secret generic my-prilvileged-token-id --from-file=openshift-client-token=mysecretToken.txt`

**Comment by maximmold** [comment]
I was able to follow the documentation and get the DSL to use the credential appropriately. I think we're at a roadblock though because we'd like to continue to use the Openshift login plugin as well, but have permissions set at the folder level. This doesn't appear possible since it only supports the Global Matrix and the Project matrix strategies.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Multi-tenant security on a single Jenkins
instance (#223)" gesendet am 31.01.2019 20:08:31.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
@maximmold 
1) good news re: openshift.withCredentials
2) yeah no plans at this time to augment login plugin beyond those strategies; off hand don't know what would even be involved in supporting that one

I've reached out to some of our PM folks offline

**Comment by gabemontero** [comment]
@siamaksade @pweil- @bparees ^^ 

login plugin enhancement request
