### ISSUE TITLE
how can i specify/overwrite-default  skipTLSVerify value to true 

### ISSUE THREAD

**Issue by rajmechi** [openshift/jenkins-client-plugin#225]
for example i want to use below in pipeline. 

openshift.withCluster() {
      openshift.withProject( "${DEV_PROJECT}" ){
      def latestDeploymentVersion = openshift.selector('dc',"${APP_NAME}").object().status.latestVersion
      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
      rc.untilEach(1){
          def rcMap = it.object()
          return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
      }
}

seems  default value is  --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

can i set skipTLSVerify = true .

i seen below 

if (this.skipTLSVerify) {
             cmd.add("--insecure-skip-tls-verify");
        } else {
            if (this.caPath != null) {
                cmd.add("--certificate-authority=" + this.caPath);
            }
        }
in src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java

but i am not sure where to set skipTLSVerify

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] guys how can i specify/overwrite-default
skipTLSVerify to true  (#225)" gesendet am 31.01.2019 01:48:29.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by bparees** [comment]
@TomSchmitz i have been forced to block you from my personal account.  please fix your auto-responder and/or do not subscribe to our repositories.  This the second time this has happened and you did not acknowledge it last time.  These messages are a distraction from our ability to collaborate with the community.  If it continues, I will request permission to block you from the org to prevent this.

**Comment by rajmechi** [comment]
found it seems i need to add insecure://   to cluster url       (  insecure://xxxxx:443 )  that set skipTLS = true     --   src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy.

let me know if there is any other way to it. 

Thanks.

**Comment by rajmechi** [comment]
can you guys add insecure:// will set skipTLS = true to the README file.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] how can i specify/overwrite-default
skipTLSVerify value to true  (#225)" gesendet am 31.01.2019 16:00:42.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] how can i specify/overwrite-default
skipTLSVerify value to true  (#225)" gesendet am 31.01.2019 15:59:07.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
hey @rajmechi the `insecure://` trick is an `oc` nuance I'm not sure we want to promote

the more official way is to set this flag when creating your cluster

If you see the screen shot at https://github.com/openshift/jenkins-client-plugin#configuring-an-openshift-cluster you'll see the disable tls flag
