### ISSUE TITLE
How to use wildcard to get artifact for startBuild method

### ISSUE THREAD

**Issue by emregozen** [openshift/jenkins-client-plugin#226]
Hello,

I put a Jenkinsfile to my spring boot application's root folder for creating a pipeline on Openshift,
Everything looks great,
But I want to use pipeline for my JAR file, because it contains a version prefix,
When I put a '*' instead of version, it could not find the JAR artifact,
Is it possible to use wildcard chars when calling startBuild method?

My Jenkinsfile is like that,

```
pipeline {
  agent {
    label 'maven'
  }
  stages {
    stage('Unit Test') {
      steps {
        sh "mvn test"
      }
    }
    stage('Build App') {
      steps {
        sh "mvn clean package -DskipTests"
      }
    }
    stage('Build Image') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              openshift.startBuild("my-gateway", "--from-file=target/my-gateway-*.jar").logs("-f")
            }
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              dc = openshift.selector("dc", "my-gateway")
              dc.rollout().latest()
              timeout(10) {
                  dc.rollout().status()
              }
            }
          }
        }
      }
    }
  }
}
```

Jenkins Log,

`{reference={}, err=error: stat /tmp/workspace/my-gateway/my-gateway-mygateway-pipeline-git/target/my-gateway-*.jar: no such file or directory, verb=start-build, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=my-gateway --token=XXXXX start-build my-gateway --from-file=target/my-gateway-*.jar -o=name , out=, status=1}`

Thanks.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] How to use wildcard to get artifact for
startBuild method (#226)" gesendet am 31.01.2019 08:51:37.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
@emregozen - sorry, this is a function of the `oc` binary, and that binary currently does not support wildcards for that parameter.

You could try to request such a feature change at https://github.com/openshift/origin, or if you have a RH subscription, open an RFE.
