### ISSUE TITLE
Question about result of bc.startBuild()

### ISSUE THREAD

**Issue by mbecca** [openshift/jenkins-client-plugin#228]
Hi,

How can I determine if the output of this buildconfig had errors?

def bc = openshift.selector("bc", "app")
def result = bc.startBuild()
bc.logs('-f')
#here determine result of build#

Thanks in advance!

Regards, M.

**Comment by mbecca** [comment]
> 
> 
> Hi,
> 
> How can I determine if the output of this buildconfig had errors?
> 
> def bc = openshift.selector("bc", "app")
> def result = bc.startBuild()
> bc.logs('-f')
> #here determine result of build#
> 
> Thanks in advance!
> 
> Regards, M.

Is valid?:

def latestVersion = openshift.selector('bc',"app").object().status.lastVersion
def build = openshift.selector('build', "app-${latestVersion}")
def status= build.object().status.phase
if (status == 'Failed'){
  currentBuild.result = "ABORTED"
  error('ABORTED')
}

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] Question about result of bc.startBuild()
(#228)" gesendet am 09.02.2019 01:25:44.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 11.02.2019 abwesend.
I am out of the office until 11.02.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Question about result of bc.startBuild()
(#228)" gesendet am 09.02.2019 01:53:59.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
That looks like the right direction @mbecca 

You can see similar things in our testing script of miscellaneous script interactions at https://github.com/openshift/jenkins-client-plugin/blob/master/examples/jenkins-image-sample.groovy#L228-L244

**Comment by mbecca** [comment]
@gabemontero thanks for all!

Regards,

M.
