### ISSUE TITLE
Invalid flag '--ignore-not-present' used in README.md example

### ISSUE THREAD

**Issue by gsalamin** [openshift/jenkins-client-plugin#231]
In the example ["Want to promote or migrate objects between environments?"](https://github.com/openshift/jenkins-client-plugin#want-to-promote-or-migrate-objects-between-environments) the delete statement use the flag `--ignore-not-present`.
This argument is not recognized as a valid flag. Do you mean `--ignore-not-found` which is a valid flag of the `oc delete` command?

`maps.delete( '--ignore-not-present' )` --> `maps.delete( '--ignore-not-found' )`

**Comment by gabemontero** [comment]
thanks @gsalamin 

PR to fix is up
