### ISSUE TITLE
No logs when running in Docker agent

### ISSUE THREAD

**Issue by sohrab-** [openshift/jenkins-client-plugin#232]
I have set up a job that executes in a short-living container, i.e. `agent { docker {} }`.

None of the log outputs from `oc` seem to be making its way to console logs: 

![image](https://user-images.githubusercontent.com/4444588/53020462-05a0ff80-34ab-11e9-9440-f9bed779cd0c.png)

For example, one of the above actions is a `startBuild` that [should](https://github.com/openshift/jenkins-client-plugin/pull/189) print out the command stdout.

Current work-around is to go back to using `Selector.logs()` and `echo()`.

Jenkins 2.164
Jenkins OpenShift Client 1.0.24

**Comment by gabemontero** [comment]
did you follow the instructions at https://github.com/openshift/jenkins-client-plugin#compatibility-with-declarative-pipeline and enclose all your `openshift` invocations with `script { ... }` closures?

**Comment by sohrab-** [comment]
@gabemontero I am using _scripted pipelines_, not declarative pipelines.

Here is the snippet from my shared library, if that helps:

```groovy
stage('Build') {
  checkout scm

  openshift.withCluster(config.openshiftCluster) {
    openshift.withProject(config.openshiftProject) {
      if (config.ocApply) {
        openshift.apply(readFile(config.buildConfigFile))
      }

      openshift.patch("buildConfig/${config.buildConfigName}",
        '\'{"spec":{"output":{"to":{"name": "' + config.imageName + '"}}}}\'')

      openshift
        .selector("buildConfig/${config.buildConfigName}")
        .startBuild("--follow --wait --from-file=\"${config.jarPath}\"")

      if (config.tagLatest) {
        openshift.tag(config.imageName, "${config.appName}:latest")
      }
    }
  }
}
```

**Comment by gabemontero** [comment]
your snippet above may be scripted @sohrab- but in your description you noted the use of the `agent` step.

That is declarative syntax.

See https://jenkins.io/doc/book/pipeline/syntax/#agent

It is a declarative pipeline "Section"

When you call the snippet above, is it within a `pipeline { ...}` closure?

If so, then you need to following the instructions I noted in https://github.com/openshift/jenkins-client-plugin/issues/232#issuecomment-465319429

**Comment by sohrab-** [comment]
My apologies for the confusion. It _is_ scripted pipelines. Please ignore the `agent {}` thing above. We start with `node {}` and the _agent_ is defined like below:

https://jenkins.io/doc/book/pipeline/docker/

![image](https://user-images.githubusercontent.com/4444588/53202618-186a2e80-367b-11e9-86f1-ca83451bb391.png)

**Comment by gabemontero** [comment]
OK, I was able to set something analogous up.

Here is my pipeline:

```
node {
    docker.image('docker.io/openshift/jenkins-2-centos7:v3.11').inside {
        stage('Test') {
            openshift.withCluster('mycluster') {
                openshift.withProject() {
                    openshift.startBuild('nosrc-build', '--follow')
                }
            }
        }
    }
}
```

And I get the output ... same output I get when running from the command line in my cluster:

```
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] _OcAction
NOTE: the selector returned when -F/--follow is supplied to startBuild() will be inoperative for the various selector operations.
Consider removing those options from startBuild and using the logs() command to follow the build output.
could not find oc binary on the target computer of OS type UNIX
but your launcher is of a type that might have hindered out scan
[start-build] build/nosrc-build-2
Using docker.io/openshift/test-build-simples2i:latest as the s2i builder image
assembled!
Build complete, no image push requested
```

Can you add a `openshift.verbose(true)` before your start-build call (you can add an `openshift.verbose(false)` right after it to minimize output) ?

I suspect 
```
"--follow --wait --from-file=\"${config.jarPath}\""
```
has something to do with it .... Jenkins and Jenkins/groovy is a super big pain when it comes to quotes and parameters.

**Comment by gabemontero** [comment]
I suspect it needs to be something like 
```
'--follow', '--wait', '--from-file="${config.jarPath}"'
```
with double quotes inside single quotes, but I'll know more after you get me the debug data, and I don't have time to construct a --from-file test scenario

**Comment by sohrab-** [comment]
Thanks, @gabemontero. I am not sure if the quotes are the issue but just to remove them as a factor, I stopped using string interpolation altogether:

```groovy
buildConfig.startBuild('--follow', '--wait', '--from-file="' + config.jarPath + '"')
```

With verbose logging on, I saw the following log entry:

```
NOTE: the selector returned when -F/--follow is supplied to startBuild() will be inoperative for the various selector operations.
Consider removing those options from startBuild and using the logs() command to follow the build output.
```

I am not sure why it would inoperable for a BuildConfig selector but I changed my code to this and now the logs are getting printed:

```
openshift.startBuild("buildConfig/${config.buildConfigName}", '--follow', '--wait', '--from-file="' + config.jarPath + '"')
```
![image](https://user-images.githubusercontent.com/4444588/53309118-21b4fe80-38fa-11e9-86e7-49774cc61fd1.png)

Interestingly, it still prints out the "NOTE" even when using `openshift.startBuild()`.

(Please ignore "could not find oc binary on the target computer...". That seems to be a regression as part of the plugin update  1.0.24 -> 1.0.26. I may raise a separate issue for that.)

**Comment by gabemontero** [comment]
OK good news @sohrab- 

A couple of follow ups:
1) on the message 
```
"NOTE: the selector returned when -F/--follow is supplied to startBuild() will be inoperative for the various selector operations."
```
the implementation detail is that the build output log processing can interfere with the json processing from interactions with the openshift api server.  There is no good way to isolate the two.

That is why our examples promote the form

```
    def buildSelector = bc.startBuild()
    buildSelector.logs('-f')

```

2) yeah I meant to also note isolating each arg as a param as well as noting the quote stuff ... that is the better form

Going to close this one out ... will move on to the other item you opened.
