### ISSUE TITLE
Search of oc cli in the filesystem may take too long time

### ISSUE THREAD

**Issue by Denis220795** [openshift/jenkins-client-plugin#234]
Hello @gabemontero , after adding some logic for debug in #224  (search of oc cli executable in all the filesystem) we start getting case when plugin stucks in pending state on oc_action step and it doesn't print debug info with the path of found oc cli executable so I think it searches oc cli executable in all the filesystem that on development Jenkins node takes to long time.

Note that it worked fine on the test Jenkins server that we had because it doesn't have many of directories and files as it is used only for testing, but when we moved to the development Jenkins instance it start getting too much time until plugin will find the executable oc file and execute any action.

Here is the log from the test instance:
```
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] _OcAction
found the following oc executables on the target computer of OS type UNIX: [/scm/Apps/OpenShift-Client/3.5.5.31.67/oc]
The dir of an oc that was found is in the path: /scm/Apps/OpenShift-Client/3.5.5.31.67
```

And from development isntance:
```
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] _OcAction
Aborted by denis.gerasimov
```

Note that I had to abort pipeline execution after pause >45 mins.

Thanks, 
Denis

**Comment by gabemontero** [comment]
Hey @Denis220795 

Here's one that only searchs the directories in `PATH` on the target

[client-plugin-1.zip](https://github.com/openshift/jenkins-client-plugin/files/2882225/client-plugin-1.zip)

Would you be able to try it like before?  There is no debug in it currently (I removed it after vetting it in some of my agent scenarios).

**Comment by Denis220795** [comment]
@gabemontero , confirm that I don't see any debug messages in the logs now. I've tested it on the test instance without lots of files in the file system but hope as you have removed searching of oc executable in the file system it should also work fine on development instance too. Let me know please when we can try new release version on the development server.

**Comment by gabemontero** [comment]
great news @Denis220795 and thanks again for helping with testing

I'll continue to post updates here and/or https://github.com/openshift/jenkins-client-plugin/pull/235 as I move the fix through our pipeline until we have a new official version, etc.

**Comment by Denis220795** [comment]
Ok, great, thanks for quick fixes @gabemontero !

**Comment by gabemontero** [comment]
v1.0.26 has been initiated at the jenkins update center

**Comment by gabemontero** [comment]
and it is available at https://updates.jenkins-ci.org/download/plugins/openshift-client/
