### ISSUE TITLE
To be able to run some Openshift commands without node

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#237]
Hi, currently this plugin does not allow run Openshift commands outside a node block. I don't think you really need to make a Jenkins agent busy just to start a build or a deployment in Openshift. I suggest as an improvement to be able to run Openshift commands outside node block

**Comment by gabemontero** [comment]
Our integration points into jenkins pipelines requires it.  Changing that would be rewrite of the plugin.  That is not happening at this point.
