### ISSUE TITLE
Warnings that oc command is not found when it does exists

### ISSUE THREAD

**Issue by sohrab-** [openshift/jenkins-client-plugin#238]
Since upgrading the plugin from 1.0.24 to 1.0.26 (Jenkins v2.165), I started getting these warning when invoking each `openshift` commands.

![image](https://user-images.githubusercontent.com/4444588/53309625-0c8d9f00-38fd-11e9-9c7b-b09faccfcc31.png)

I am running the jobs in a containerised agent that does have the `oc` binary available in `/bin`. The first few lines of the screenshot above are the output of the following commands that proves this fact:

```groovy
sh 'echo $PATH'
sh 'ls -ltr /bin/oc'
sh 'oc version'
```

It is annoying to see the logs but the openshift commands are still getting executed so there are no _functional_ regressions, i.e. no workaround required (low priority).

**Comment by gabemontero** [comment]
Yeah eventually I'll make this a debug message that only appears if you have verbose on.  But given the problems we have had hitting the sweet spot of a) which jenkins launch mechanism to use and b) all the `oc` permutations folks want to run, I want this debug readily available for a bit.

Leaving this open to remind me about changing the log level eventually.

If by "containerised agent" @sohrab- , you mean using the `conatiner` step from the k8s plugin, then yeah, this makes sense as to why you are getting that message.

**Comment by sohrab-** [comment]
We do a few different setups. From memory, the screenshot is from a pipeline similar to below:

```groovy
node {
   docker.image('gradle:5.2.0-jdk8').inside('-v /opt/openshift-client-v3.11.0/oc:/bin/oc') {
      sh 'gradle bootJar'
      openshift.withCluster('my-cluster') {
         openshift.withProject('my-project') {
            openshift.startBuild('buildConfig/my-build', '--follow', '--wait', '--from-file=./build/libs/myapp-1.0.0.jar')
         }
      }
   }
}
```

(I know it's a strange way of doing it but it's handy.)

**Comment by NickLiffen** [comment]
Hey 👋 Any update on making this into a specific verbose/debug stage? Love the plugin; but sometimes this is causing confusion on people thinking it doesn't work; even when it does.

**Comment by gabemontero** [comment]
thanks for the reminder @NickLiffen .... I'll try to get to it this week.

@waveywaves fyi only (I can handle this one, but I'll tag you in the PR).

**Comment by gabemontero** [comment]
PR https://github.com/openshift/jenkins-client-plugin/pull/272 is up

I'll cut v1.0.31 at the jenkins update center after it merges.

**Comment by NickLiffen** [comment]
@gabemontero Thanks for the update 👍 Appreciate how quick you got the PR up there 👍

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Warnings that oc command is not found
when it does exists (#238)" gesendet am 31.05.2019 16:35:47.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Warnings that oc command is not found
when it does exists (#238)" gesendet am 31.05.2019 20:05:07.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
