### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#24]
I need to connect to Openshift through a corporate proxy. How can I configure the proxy in this plugin?

**Comment by gabemontero** [comment]
For a proxy between jenkins and openshift, I believe this falls under:  https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy

And it lists which plugins support proxies.  If I am correct, jenkins-client-plugin will need to be updated.  Need to investigate more ... looks like a trello card.

@bparees - thoughts?

Also, just for completeness, while this particular issue would appear to be orthogonal to a proxy between openshift and the internet, per https://docs.openshift.org/latest/install_config/http_proxies.html, I am mentioning it here in case @GolanTrevize10 had not yet read about that and might be affected by it.

**Comment by bparees** [comment]
Since the openshift client plugin is ultimately just invoking the oc binary, this is really a question of "how do i use the oc client binary when i need to go through a proxy".  For which i don't know the answer but i'd hope that the oc client binary respects the HTTP_PROXY env var, so in theory if you set that var in your jenkins job environment, it should "just work", assuming the shell that we invoke the oc binary in, inherits the job environment.

**Comment by gabemontero** [comment]
On Fri, May 26, 2017 at 11:15 AM, Ben Parees <notifications@github.com>
wrote:

> Since the openshift client plugin is ultimately just invoking the oc
> binary, this is really a question of "how do i use the oc client binary
> when i need to go through a proxy". For which i don't know the answer but
> i'd hope that the oc client binary respects the HTTP_PROXY env var, so in
> theory if you set that var in your jenkins job environment, it should "just
> work", assuming the shell that we invoke the oc binary in, inherits the job
> environment.
>
Just searching for HTTP_PROXY in the origin source tree, the answer would
appear to be "no"

**Comment by gabemontero** [comment]
I was also curious as to how exactly these other plugins gained "citation" by jenkins as supporting http proxy (that was part of the card/research)

**Comment by gabemontero** [comment]
But yes, understanding how `oc` in general deals with or is immune to (unlikely I suppose) proxies is still fundamentally the question.

**Comment by GolanTrevize10** [comment]
Thanks for your answers. If I run oc client from command line I have to set https_proxy env variable. But in Jenkins it seems it is not working. Does the jenkins client plugin use env variables defined in Jenkins?

**Comment by gabemontero** [comment]
I believe the assumption is the shell provided when org.jenkinsci.plugins.durabletask.BourneShellScript would inherit any env vars defined in Jenkins.  But after poking around the durable task plugin some, I'm not so sure.

@jupierce - do you recall any specifics during your initial development?

Perhaps we can look at `GlobalVariable` and/or `GlobalVariableSet` and explicitly set all name/value pairs on the durable task invocation.  I'd want to research that some more before committing to such an approach.

**Comment by jupierce** [comment]
@gabemontero I would expect oc to be executed in an environment with variables:
(1) Inherited by the Jenkins global configuration for environment variables
(2) Variables set in the Jenkinsfile itself (e.g. ```env.MY_VARIABLE=5``` )

i.e. It should be identical to those available to sh/bat steps. 

However, I did not do any testing specific to this area.

**Comment by gabemontero** [comment]
Thanks for the background @jupierce 

I've run through a few tests with a debug version of the plugin and a test script to help clarify.

First, when using `env.HTTPS_PROXY='foo'`, `env.https_proxy='foo'`, `env.http_proxy='foo'`, or `env.HTTP_PROXY='foo'`, I see the env var processed, and the goproxy code consuming the variable and attempting to leverage the proxy on connection (of course I gave it a bogus URL so it fails):

```
Caught: hudson.AbortException: Error during describe;
{reference={}, err=Unable to connect to the server: http: error connecting to proxy http://foo: dial tcp: lookup foo: no such host, verb=describe, cmd=oc describe serviceaccount --server=https://172.30.0.1:443 --namespace=myproject --token=XXXXX , out=, status=1}
``` 

The same holds if I define those as job parameters and execute the job via "build with parameters"

And the same holds if I define them via 'Manage Jenkins' -> 'Configure Jenkins' -> 'Global Properties' -> 'Environment variables'.  The proxy env vars are consumed, and the goproxy code attempts to connect.

So, assuming either HTTPS_PROXY, HTTP_PROXY, https_proxy, or http_proxy is set, we are at the point of needing to debug the actual setting and what if any results from the goproxy connection.

@GolanTrevize10 - could you insert a `openshift.loglevel(10)` in your script prior to any other uses of `openshift` and provide the output to us?  Thanks.

**Comment by gabemontero** [comment]
@GolanTrevize10 - I did some more experimenting with this today.  Based on my results, I suspect that there is a difference between the server URL used when running `oc` from your command line vs. the server URL used within Jenkins.

I had to change my server URL configuration for the plugin (i.e. create a new cluster like is documented at https://github.com/openshift/jenkins-client-plugin#configuring-an-openshift-cluster ) to something accessible.

Can you compare these items:
- the server URLs for the command line run vs. what is configured for the plugin?
- the /etc/hosts on the system for your command line run vs. the one for the jenkins pod (`oc rsh <jenkins pod name> cat /etc/hosts` should display it)
- the /etc/resolv.conf on the system for you command line run vs. the one for the jenkins pod (`oc rsh <jenkins pod name> cat /etc/resolv.conf` should display it)

I suspect there will be differences that will explain why the behavior is different.

Also, if you could supply the precise error message, that might provide some clues.

thanks

**Comment by GolanTrevize10** [comment]
Hi, even with log level 10 it is not giving more information,  so I decided to reinstall Jenkins from scratch and now it is working. I have to set https_proxy variable though. Don't know why it was not working before.

Thanks.

**Comment by gabemontero** [comment]
Glad you can get it running @GolanTrevize10 

Yes, currently the setting of either https_proxy, HTTPS_PROXY, http_proxy, HTTP_PROXY, is required.

And with respect to plugins using the proxy setting for the plugin manager Jenkins, there is some debate in the Jenkins community whether that was a good approach.  Or at least that plugins should allow that setting to be overridden by env vars in pipeline scripts.

An approach where we inspect the jenkins plugin manager setting if those expected env vars are not present does at least warrant consideration where we explore the pros/cons, etc.

Per my team's process, I have opened https://trello.com/c/lAJ0rmCa/1241-various-jenkins-plugins-inspect-jenkins-plugin-manager-proxy-setting-along-with-env-vars-jenkinsintegration on our trello planning board to track resolution of this request, and am closing this issue out.

Thanks.
