### ISSUE TITLE
[QUESTION] Any support for Job execution in a pipeline?

### ISSUE THREAD

**Issue by mbecca** [openshift/jenkins-client-plugin#241]
Hi,

I need execute a Job (for liquibase migrations) in a pipeline (https://docs.openshift.com/container-platform/3.11/dev_guide/jobs.html).
Is there some kind of support for this? For example, execute it (simil rolllout() of a DC) and monitor that it has been executed correctly.

Excuse me for my poor English.

Regards,

M.

**Comment by gabemontero** [comment]
There is an `openshift.run(...)` command that is a passthrough to `oc run`

Presumably you could duplicate the `oc run` example in https://docs.openshift.com/container-platform/3.11/dev_guide/jobs.html

`openshift.run(...)` only returns a result, not a selector.  So you would have to manually create a selector via `openshift.selector(...)` and they you could monitor

**Comment by mbecca** [comment]
Hi @gabemontero !

Thanks for the comment! I'm going to keep this in mind.

M.
