### ISSUE TITLE
_OcAction does not have a timeout or data for the status

### ISSUE THREAD

**Issue by alexanderrtaylor** [openshift/jenkins-client-plugin#244]
Issue:
If _OcAction from https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1384 is failing(because of a template which does not have resources or the image is not there or the pod keeps failing) the Jenkins pipeline is never able to make progress or give any data about what is happening. It means that the pipeline must be killed off manually.

Steps to solve:
A timeout within that `_asMarkup` method to ensure that a pipeline does not hang indefinitely on OC methods or at least grab some data for the status for the OC Action method?

**Comment by gabemontero** [comment]
Sorry @alexanderrtaylor but that gets to tricky if folks are using `timeout` within their pipeline.

Whose timeout duration takes precedence among others.

Nor at this point am I inclined to add parameters to signatures to enable this.

This plugin defers to writers calling this plugin from within a timeout closure.

We won't be making this change.

Thanks for the suggestion / interest.
