### ISSUE TITLE
how to fail fast in untilEach

### ISSUE THREAD

**Issue by jiangytcn** [openshift/jenkins-client-plugin#254]
Hello,

I'm using  https://github.com/openshift/jenkins-client-plugin#watching-and-waiting-of-course this method to watch my pod status. 
Pod is created by the job file, and what I want to do is only watching the running state of the container, if the container in `Error` state,  is that possible to make it fail fast other than the timeout interrupt the pipeline ?

**Comment by vfreex** [comment]
Yes, you can add a condition to check the unexpected status then throw an exception or call the `error` step:
``` groovy
if (it.object().status.phase in ["Error", "Failed", "Cancelled"])
  error('Some error')

```
