### ISSUE TITLE
input step with jenkins restart causes failure

### ISSUE THREAD

**Issue by stujb** [openshift/jenkins-client-plugin#255]
We have a fairly complex pipeline that loads different steps depending on how users want to deploy their applications. These various steps include build steps, deployment steps and approval steps.. We migrated from the deprecated openshift plugin to this one and found an issue where we get a failure on pipelines with multiple approval steps in the same pipeline. 

The issue manifests itself on a pipeline with multiple approval steps when the jenkins pod is restarted and the pipeline is sitting waiting at an approval step that is NOT the first approval step. If the jenkins is restarted at the first approval step we do not see this issue.

The issue itself appears to eminate from the watch loop that is verifying a deployment. The actual error we get is `watch closure threw an exception: "java.lang.NullPointerException: Cannot invoke method getServerUrl() on null object; Cannot invoke method getServerUrl() on null object".`

I have reproduced the issue with some test code and it only occurs in code that uses load & execute of an external groovy file. If the same code is dropped directly in to the top level Jenkinsfile the error does not occur.

I have attached this test code - there are two Jenkinsfiles (marked broken and working) and a separate deploy.groovy that is loaded by the broken Jenkinsfile.

To replicate the issue run the Jenkinsfile and when the pipeline is waiting at the second approval gate restart the Jenkins pod (eg `oc rollout latest jenkins`) and then once the Jenkins pod is running again approve to continue the pipeline. The pipeline then fails when trying to verify the deployment

[jenkins issue.zip](https://github.com/openshift/jenkins-client-plugin/files/3043377/jenkins.issue.zip)

**Comment by gabemontero** [comment]
First, thanks for the precise details and simplified test case.

This is feeling like jenkins pipeline limitations to me, especially in the context of external groovy's.  I *may* have an acceptable work around for you.

Some background:
- so this plugin is implemented using the pipeline "Global Variable" integration point.  That choice was the best for producing fluent style syntax, which was an initial/key goal of this plugin
- sidebar analysis ... that integration point seems to be losing "importance" in the pipeline ecosystem as declarative pipelines have evolved
- now, to facilitate the jenkins attempts at restarting jobs, the best we can do is mark anything serializable that would be needed again, so see lines like 
  --- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L25
  --- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L100
  --- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1108
- your NPE is a result of this [variable](https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L78) being null when your watch closure is called
- in theory, that variable should be hydrated as part jenkins loading a job back in

So why does that hydration not work in you case .... purely speculation on my part, but that scenario is non-trivial and there are bugs.  Some internet searching now and in the past lends some credence to that speculation, but there are not hits precisely like your scenario.

Now, the workaround.
- your pipelines are calling `openshift.withProject(...)` closures without being inside an `openshfit.withCluster(...)` closure.  Either you all are assuming you'll pick up the default project, or your external groovy snippets are being called from places where the `openshift.withCluster(...)` exists.  Confirm to me which of those or both of those it is if possible.
- but the working around is to *ALWAYS* leverage the form:
```
openshift.withCluster(...) {
   openshift.withProject(...) {
   }
}
```

Full disclosure: I did not try your repro recipe as of yet, and it may be a bit before I could.  But if you have the cycles/willingess to try the workaround, please do and we can go from there.

thanks

@pradeepto @sthaha @waveywaves FYI

**Comment by stujb** [comment]
Thanks for the prompt and detailed reply.

My bad on one thing - in our original code that failed we did have the call to openshift.withCluster() prior to the openshift.withProject() call. I mistakenly omitted this when reducing down to the test code.

I have added the withCluster() call into the test code and the same issue still occurs when I have the withCluster() call paired with each withProject() call.

However if I encapsulate all the groovy code in a single withCluster() closure so both the withProject() calls are in the same withCluster() call then the issue does not occur.

In our use case we would use multiple different nodes so I have tested wrapping the whole of the groovy code in the Jenkinsfile within a single withCluster() closure with multiple node steps and that has worked as well.

From my perspective I believe I do now have a workaround that will allow us to migrate our pipeline code to the new plugin.

However there does still seem to be an edge case where if you have multiple withCluster() calls in a pipeline, where each call loads an external groovy file, and the jenkins instance is restarted in between those withCluster() calls being made then there is an issue with the variable hydration as you mentioned above.


Updated test case files attached for reference

Jenkinsfile.broken : updated file showing issue occurring but this time with multiple withCluster() closures
Jenkinsfile.working : original example showing working file that does not use load/execute but this time with multiple withCluster() closures
Jenkinsfile.fixed : new file showing working code with everything inside one withCluster() closure, including multiple nodes and load/executes of external groovy files - this mirrors our use case and is the workaround I will be implementing
deploy.groovy : the same external groovy to be loaded

[jenkins issue.zip](https://github.com/openshift/jenkins-client-plugin/files/3047522/jenkins.issue.zip)

**Comment by gabemontero** [comment]
Thanks for the updates @stujb 

First:  glad you have workaround

Edge case: yeah, I'm only more convinced on my original suspicion ...where I suspect separate groovy files has different ramifications wrt hydrating after jenkins restart, especially in conjuction with pipeline "global variable" integrations like this plugin.

Next steps: nothing we can codify to address within this plugin, so updating the things to watch out for section of our readme to at least warn others, and propose the work around.

Would you be good with our using your test cases and examples when documenting?  And certainly if you are willing to review any doc updates, that would be great too.

thanks

@pradeepto @sthaha @waveywaves fyi

**Comment by stujb** [comment]
Please feel free to use whatever test code you require and happy to review any doc updates as well

**Comment by gabemontero** [comment]
FYI, looking at the combination of the GlobalVariable, CpsScript, CpsFlowExecution, and LoadStepExecution (the actual `load` step implementation) source code in the jenkins workflow plugin, I've further convinced myself that this is a side of how these things work.

In particular:
- the GlobalVariables our housed in the binding of the CpsScript
- the load step uses the flow execution to create a new script and then invokes whatever you call on it
- so if our global variable is 
  a) not the outer most context, I can see where getting the binding, or 
  b) fully created within the script (i.e. the withCluster is called from within the script you load), the binding of the new script does not have our GlobalVariable instance, so it creates a new one, and saved state like the current context is lost

So yeah, gonna add this as another one of our "compatibilty" bullets in the readme

**Comment by gabemontero** [comment]
PR with the readme update is up
