### ISSUE TITLE
Error in jobs with spaces in name

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#257]
Hi, after upgrading from 1.0.23 to 1.0.29 we are getting the following error in jobs with blank spaces in the name. After downgrading it works again. 

`err=error: Unexpected args: [jobs/jobs/Openshift- CB-endtoend_monitoring/workspace/apply3955269616185031854.markup]
See 'oc apply -h' for help and examples.
, verb=apply, cmd=oc --server=xxxxx --insecure-skip-tls-verify --namespace=its-cicd-endtoend-monitoring-build --token=XXXXX apply -f /var/lib/jenkins/jobs/Monitoring jobs/jobs/Openshift- CB-endtoend_monitoring/workspace/apply3955269616185031854.markup -o=name , out=, status=1}

Finished: FAILURE `

**Comment by waveywaves** [comment]
Hello @GolanTrevize10 Thank you for opening up this issue !
Could you pass on the Jenkinsfile ? It would help in understanding the issue better.

**Comment by gabemontero** [comment]
@waveywaves this is an old pain point (spaces in names or params) among several paint points wrt launching `oc` and its multitude of possible options from the client plugin in the various jenkins env/scenarios.  A definite touch point in day 1 code walkthroughs at the f2f.

we've oscillated a fair bit between 1.0.17 and 1.0.29 in trying to handle everything

and there certainly was change in this space between 1.0.23 and 1.0.29.

the value for `-f` come from https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L721

the space in name thing has been most prevalent when dealing with templates, and to date, I've scoped the kludges we've done around spaces to `oc process`

See 
- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L721
- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java#L138

Most likely with our switch back to `ClientCommandRunner` in `OcAction` and `OcWatch` we'll need to expand on that some.

My first thought is to keep the expansion to a minimum and apply some form of quoting in https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L721
like we do in the next line

@GolanTrevize10 - please refresh my memory, were you able to take pre-release versions of the plugin to try out in the past?  If so, are you still able to do that ?  Creating a job with a space in the name should be pretty straight forward, but just in case there are other env diffs in play, any possible validations on your end would be great.

thanks

**Comment by gabemontero** [comment]
And I realized, one of the other changes we had to employ recently was moving any temp files created from the generic jenkins tmp dir to the workspace tmp dir (this was for some multi container agent runs).

the generic jenkins temp dir did not have any spaces in the name

workspaces can, as noted here

**Comment by GolanTrevize10** [comment]
@gabemontero yes we can test a pre-release version in our test environment

**Comment by gabemontero** [comment]
cool thanks @GolanTrevize10 
the changes in the PR referenced above have passed our regression bucket
but I'll hold off for a bit on cutting a new release until I hear from you
here it is:
[client-plugin.zip](https://github.com/openshift/jenkins-client-plugin/files/3094956/client-plugin.zip)

there are a few debug message that show up in the jenkins pod log (not the run log in the jenkins console) that have a "GGM" prefix if it comes to that.

**Comment by gabemontero** [comment]
Hey @GolanTrevize10 - if you think you can try the patch in https://github.com/openshift/jenkins-client-plugin/issues/257#issuecomment-484544021 in the next day or so, great.

But if you think you'll be delayed further, I'll go ahead and cut the next version of the plugin

thanks again

**Comment by GolanTrevize10** [comment]
Hi Gabe sorry for the delay. I was on vacations. We will try it tomorrow

**Comment by pavenova** [comment]
Hi, @gabemontero 
Did I understood it correctly, fix should be included at version 1.0.29? 
I was trying to find the changelog, but there is probably none existing ;/ 

Thanks :)

**Comment by gabemontero** [comment]
I have *NOT* cut a new version with the fix contained in the patch I attached here @pavenova

**Comment by pavenova** [comment]
> I have _NOT_ cut a new version with the fix contained in the patch I attached here @pavenova

Hi, as mentioned in edit of the comment, I noticed it seems to be impacted version with bug, once I tried that attached there, it seems to be working fine , FYI, thanks

**Comment by gabemontero** [comment]
ok thanks for trying the patch @pavenova and confirming it addressed the problem for you

**Comment by GolanTrevize10** [comment]
Pavenova and me work together so it is OK for me as well 🙂

**Comment by gabemontero** [comment]
initiated v1.0.30 of this plugin
