### ISSUE TITLE
Is there a way to "watch" an openshift.exec ?

### ISSUE THREAD

**Issue by cadwmaster** [openshift/jenkins-client-plugin#268]
I'm using `openshift.exec` to execute a large process and what to see the progress of that live and not just at the end of the process, is any way to do that ?

**Comment by gabemontero** [comment]
Not at the moment @cadwmaster  ... it would entail a code change in the plugin.

I *think* it would be possible if we changed `openshift.exec` to work like `OpenShiftResourceSelector.logs` and `OpenShiftResourceSelector.startBuild` but we'd have to prototype to be sure.  

/assign @waveywaves

Another educational exercise (probably easier than the verifyService endeavor)

**Comment by waveywaves** [comment]
Will take this up. Putting it in the queue as of now.

**Comment by akram** [comment]
The PR #284 will fix this.
