### ISSUE TITLE
using selector to delete a route

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins-client-plugin#269]
I am trying to delete a route via the selector like so

```
stage("delete route") {
      steps {
        script {
          openshift.withCluster( "${env.CLUSTER_URL}", "${env.CLUSTER_TOKEN}" ) {
             openshift.withProject("${env.NAMESPACE}") {
                openshift.selector("route/myroute").delete()
             }
          }
        }
      }
    }
```

This returns an error: `the server doesn't have a resource type "route"`

Per https://github.com/openshift/origin/issues/15020, it seems like I need to pass in `--service-catalog=true`. I don't really see any information around this for the jenkins client plugin. Maybe I am missing something? Thanks!

**Comment by gabemontero** [comment]
hey @Gl4di4torRr  - yeah this is a version of `oc` and your cluster thing.  I just tried it on a 4.x cluster and `openshift.selector("route/myroute").delete()` worked for me.

And yeah, we don't cover every nuance of `oc` interaction with the cluster in this plugin's doc.  There is an implied expectation that you know those nuances exist and consult the docs and `oc` help as needed.  End of the day, this plugin for better or worse is a sugary groovy wrapper for invoking `oc` from jenkins pipelines.

If you supply the `oc` version and cluster version, we can see about reproducing and perhaps wrangling the right syntax for you.

@pradeepto @sthaha @waveywaves fyi ^^

**Comment by Gl4di4torRr** [comment]
@gabemontero thanks! i'll get back to you on this.

**Comment by Gl4di4torRr** [comment]
@gabemontero getting back to looking into this.

Here is my oc version and cluster version:

```
+ oc version
oc v3.11.88
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip:443
openshift v3.10.119
kubernetes v1.10.0+b81c8f8
```

I'll be digging more into this myself today. I'll see what I can come up with.

**Comment by Gl4di4torRr** [comment]
@gabemontero you know what it just worked... maybe i was going crazy the other day. if i find this to be some intermittent issue with the OC and Cluster version, I'll try to look more closely into the implementation of this client before opening an issue next time :)

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] using selector to delete a route (#269)"
gesendet am 31.05.2019 15:38:29.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] using selector to delete a route (#269)"
gesendet am 31.05.2019 15:46:03.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] using selector to delete a route (#269)"
gesendet am 31.05.2019 15:46:00.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
