### ISSUE TITLE
openshift.patch always returning 400 BadRequest

### ISSUE THREAD

**Issue by toschder** [openshift/jenkins-client-plugin#270]
Hi, 
I need to patch an existing ImageStream. I tried the code sample from the documentation adjusted to my needs - but I always got 400 BadRequest. Here´s the code:

`openshift.patch("is/mystream", '\'{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}\'')`

The error I receive is:
`17:53:25  {reference={}, err=, verb=patch, cmd=oc --server=https://...... --insecure-skip-tls-verify --namespace=myspace --loglevel=4 --token=XXXXX patch is/mystream -p '{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}' , out=I0525 15:53:25.299908      59 helpers.go:201] server response object: [{
17:53:25    "kind": "Status",
17:53:25    "apiVersion": "v1",
17:53:25    "metadata": {},
17:53:25    "status": "Failure",
17:53:25    "message": "invalid character 'm' looking for beginning of object key string",
17:53:25    "reason": "BadRequest",
17:53:25    "code": 400
17:53:25  }]
17:53:25  F0525 15:53:25.299996      59 helpers.go:119] Error from server (BadRequest): invalid character 'm' looking for beginning of object key string
17:53:25  , status=255}`

When I copy/paste the command from the log output to CLI it´s working.

What´s wrong in the String or the parsing when it´s parsed to openshift.patch(....) command? 
I get the same error when trying it with openshift.raw(......)

Thanx.

**Comment by waveywaves** [comment]
Hello @toschder Below is the input in the Jenkinsfile I used and you can see the error I got below.
```
pipeline {
    agent {
        node {
            label 'nodejs'
        }
    }
    options {
        timeout(time: 20, unit: 'MINUTES')
    }
    
    stages {
        stage('test imagestream patch') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.patch("is/ruby", '{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}')
                    }
                }
            }
        }
    }
```

```
ERROR: patch returned an error;
{reference={}, err=Error from server (BadRequest): invalid character 'm' looking for beginning of object key string
, verb=patch, cmd=oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=vibhav-jenkins --token=XXXXX patch is/ruby -p {"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}} , out=, status=1}
```

After I tested it out with the below, it worked properly.

**Comment by toschder** [comment]
Hello @waveywaves - that´s what I already implemented, but thank you anyway :-)
Modifying the ImageStream this way works - but gives a warning in the log(s): 
`StdOut>Warning: oc apply should be used on resource created by either oc create --save-config or oc apply`
So,using the "openshift.patch(...)" method is currently not possible?

**Comment by waveywaves** [comment]
@toschder Currently I am working on another issue and will update this as soon as I am done with that. As for now, I would suggest using the workaround method to patch the image stream.

**Comment by gabemontero** [comment]
@waveywaves @toschder at least with the origin error that @toschder reported it is the use of `/` ... groovy in jenkins is a real pain about those type of characters.

The `m` character the message is complaining about most likely is from `is/mystream"`

Try separating `is` and `mystream` into separate charactivers.

**Comment by toschder** [comment]
@gabemontero I dont think it´s from `is/mystream` - I´ve tested it with `is/a-real-life-name` and whatever the name is, the error remains. The hint `invalid character 'm' looking for beginning of object key string` is pointing me to the json.

**Comment by TomSchmitz** [comment]
Ich bin bis 03.06.2019 abwesend.
I am out of the office until 03.06.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] openshift.patch always returning 400
BadRequest (#270)" gesendet am 31.05.2019 12:23:05.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
sorry I got my forward and backward slashes confused @toschder 

So I just tried this and it works for me.  But I'm undoubtedly at a different oc version / cluster version than you.  My belief is it related to the particulars of your client/cluster verions combination.

Particulars of my repro:

```
gmontero ~ $ oc create is mystream
imagestream.image.openshift.io/mystream created
gmontero ~ $ oc get is mystream -o yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: "2019-05-31T16:00:38Z"
  generation: 1
  name: mystream
  namespace: jenkins
  resourceVersion: "61618"
  selfLink: /apis/image.openshift.io/v1/namespaces/jenkins/imagestreams/mystream
  uid: 3b7bc1b5-83bd-11e9-a038-0a580a81001c
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/jenkins/mystream
gmontero ~ $ 
```

Then my pipeline:

```
openshift.withCluster() {
    openshift.withProject() {
        openshift.logLevel(3)
        openshift.patch("is/mystream", '\'{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}\'')
    }
}
```

Output of the jenkins job:

```
Started by user kube:admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] echo

[Pipeline] node
Running on Jenkins in /var/lib/jenkins/jobs/asdf/workspace
[Pipeline] {
[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
found the following oc executables on the target computer of OS type UNIX: [/usr/bin/oc, /bin/oc]
Verbose sub-step output:
	Command> oc --server=https://172.30.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=jenkins --loglevel=3 --token=XXXXX patch is/mystream -p '{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}' 
	Status> 0
	StdOut>imagestream.image.openshift.io/mystream patched

	StdErr> 
	Reference> {}
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

Verification of the results:

```
gmontero ~ $ oc get is mystream -o yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.insecureRepository: "true"
  creationTimestamp: "2019-05-31T16:00:38Z"
  generation: 1
  name: mystream
  namespace: jenkins
  resourceVersion: "63542"
  selfLink: /apis/image.openshift.io/v1/namespaces/jenkins/imagestreams/mystream
  uid: 3b7bc1b5-83bd-11e9-a038-0a580a81001c
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/jenkins/mystream
gmontero ~ $ 
```

Supply the current client/server version and we'll see if myself or @waveywaves can repro with that (this would be a good educational exercise for him :-) ) and we'll go from there.

**Comment by toschder** [comment]
Hi @waveywaves and @gabemontero sorry for the delay, here´s my output. Hopefully the version(s) help you in finding out what´s going wrong here:
```
Verbose sub-step output:
	Command> oc --server=https://master-cnap-00-mp-prod.mycompany.net:8443 --insecure-skip-tls-verify --namespace=iqpress-os-prod --loglevel=4 --token=XXXXX  version 
	Status> 0
	StdOut>oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master-cnap-00-mp-prod.mycompany.net:8443
openshift v3.9.68
kubernetes v1.9.1+a0ce1bc657

	StdErr> 
	Reference> {}
[Pipeline] _OcAction
could not find oc binary on the target computer of OS type UNIX
but your launcher is of a type that might have hindered out scan
Verbose sub-step output:
	Command> oc --server=https://master-cnap-00-mp-prod.mycompany.net:8443 --insecure-skip-tls-verify --namespace=iqpress-os-prod --loglevel=4 --token=XXXXX patch is/iqpress-ol-ms-azure-rawdata-extract -p '{"metadata":{"annotations":{"openshift.io/image.insecureRepository":"true"}}}' 
	Status> 255
	StdOut>I0604 08:00:06.587138      58 helpers.go:201] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "invalid character 'm' looking for beginning of object key string",
  "reason": "BadRequest",
  "code": 400
}]
F0604 08:00:06.587329      58 helpers.go:119] Error from server (BadRequest): invalid character 'm' looking for beginning of object key string

	StdErr> 
	Reference> {}
```

**Comment by myron-randall** [comment]
I am running oc 3.11 and get the same error for the patch, so I also tried the raw command and got the same error:
ERROR: raw command [patch, bc/name-service, -p, {"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"/home/jenkins/workspace/Online Service Name CRP/NameService/src/main/docker/Dockerfile.native"}}}}] returned an error;
{reference={}, err=Error from server (BadRequest): invalid character 's' looking for beginning of object key string, verb=, cmd=oc --server=https://44.128.0.1:443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=agcs-ea-apps --token=XXXXX  patch bc/name-service -p {"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"/home/jenkins/workspace/Online Service Name CRP/NameService/src/main/docker/Dockerfile.native"}}}} , out=, status=1}


oc v3.11.59
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://console.tools.adp.allianz:443
openshift v3.11.59
kubernetes v1.11.0+d4cacc0

**Comment by gabemontero** [comment]
In your case @myron-randall it looks like the `{"spec":{"strategy":{"dockerStrategy":{"dockerfilePath":"/home/jenkins/workspace/Online Service Name CRP/NameService/src/main/docker/Dockerfile.native"}}}}` is not surrounded by single quotes.

It looks like you need to employ the `'\'` prior to the first `{` and last `}` like @toschder and I have.

Also, what version of the client plugin are you using.  There were issues with parameters and spaces, quotes, double quotes, that have been fixed since 3.11 was shipped.

Or if you could supply the actual pipeline groovy, we can compare.

Next, just to clarify, on my repro attempt at https://github.com/openshift/jenkins-client-plugin/issues/270#issuecomment-497767353 I was using 4.1 and the latest version of this plugin at  the time, which was v1.0.30 at the time.

I've gone back and run against 3.11, with the now latest v1.0.31 of this plugin, and my example at https://github.com/openshift/jenkins-client-plugin/issues/270#issuecomment-497767353  still works.

Now, running with v3.9 that @toschder has ... I pulled down
https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz  (that is at least the same `oc` level) and `oc cluster up` things worked for me.
- if I use both the default version of the client plugin in the 3.9 image (v1.0.7), or the latest version, v1.0.31, 
- as well as the default `oc` that comes with that image, and then using Gloal Tools Configuration to inport oc v3.9.0+191fece and us it instead

I searched back through this and did not see what version of the client plugin your are using @toschder (though I think I recall from other exchanges you typically use something recent).

We might have to start looking at whether of versions of the workflow plugins from jenkins, etc. are different ... maybe there is a groovy processing difference.

I'm admittedly grasping at remote possibilities here.

I'm using the defaults  that come with the image ... did you all upgrade any of these?

**Comment by myron-randall** [comment]
I changed the quoting as described earlier in the conversation and it does work now. Thank You!

**Comment by akram** [comment]
Good to see that.
So we close it in favour of the fix being "check the escaping" .

/close
