### ISSUE TITLE
Needs two credentials for this plugin and oc commands

### ISSUE THREAD

**Issue by racodond** [openshift/jenkins-client-plugin#277]
Hi,

Among others, due to https://github.com/openshift/jenkins-client-plugin/issues/276, for now, I use both this plugin and oc commands in my scripted pipelines.

I have to define twice the credentials (token) in Jenkins: once with this plugin format and another time as a Secret format.

Would it be possible to eventually be able to use the same credentials for both ways?

Thank you

Regards,

David

**Comment by gabemontero** [comment]
don't see how @racodond
