### ISSUE TITLE
openshift build pod keep running even after the Jenkins pipeline is cancelled from UI

### ISSUE THREAD

**Issue by Joyce808** [openshift/jenkins-client-plugin#278]
My Jenkins is using Openshift Client 1.0.18 and Jenkins version is 2.130. 

I cancelled the Jenkins pipeline build from Jenkins UI, but found the openshift build pod is still running and caused the build image is uploaded to artifactory. Ideally the openshift build pod is cancelled too. 

I think our problem is similar to: 
https://bugzilla.redhat.com/show_bug.cgi?id=1357752
and the fix is done at pull request: 
https://github.com/openshift/jenkins-plugin/pull/106

I am wondering if this is also fixed in jenkins-client-plugin, or I need to upgrade the client version? Sorry in advance if I asked questions in a wrong place. 

Thanks!

**Comment by adambkaplan** [comment]
This should also be fixed in jenkins-client-plugin - try upgrading your Jenkins client. Note that we only have limited backwards support guarantees - the current client plugin works on OpenShift 3.11 and higher.

**Comment by gabemontero** [comment]
The user’s pipeline can also factor into the cancel not working.  Please
supply the pipeline content for review as well.  There has been a fix here
in the past and this aspect has been stable for a bit.  Also, if by chance
there is a bug, the stack trace when it times out will be definitive in
yelling us where to apply any fixes.

**Comment by Joyce808** [comment]
Thanks guys for your help, my openshift version is 3.9. I am going to upgrade openshift jenkins-client-plugin version and see if it can fix the problem first. Can you please tell me what is the latest stable version of jenkins-client-plugin? 

Thanks!

**Comment by gabemontero** [comment]
On Wed, Jul 3, 2019 at 9:01 PM Joyce808 <notifications@github.com> wrote:

> Thanks guys for your help, my openshift version is 3.9. I am going to
> upgrade openshift jenkins-client-plugin version and see if it can fix the
> problem first. Can you please tell me what is the latest stable version of
> jenkins-client-plugin?
>
latest version is good

**Comment by akram** [comment]
@Joyce808 did you by any change manage to perform the update and test it ?

/assign @akram

**Comment by Joyce808** [comment]
Sorry @akram, I missed your message. I could not update plugins easily, and have not tested it yet. I think you can close this issue. I will have to test it using my own local Jenkins later. Thanks!

**Comment by TomSchmitz** [comment]
Ich bin bis 05.08.2019 abwesend.
I am out of the office until 05.08.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] openshift build pod keep running even
after the Jenkins pipeline is cancelled from UI (#278)" gesendet am
04.08.2019 12:01:24.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
