### ISSUE TITLE
Use existing credentials type instead of OpenShiftTokenCredentials for ClusterConfig

### ISSUE THREAD

**Issue by jaysiee** [openshift/jenkins-client-plugin#279]
I've extended the Jenkins installation on Openshift with the Jenkins Configuration-as-Code plugin. We are using Jenkins to access multiple clusters, so I'm creating ClusterConfigurations with Casc (as mentioned in the docs). However, I have not found a way to create credentials of type OpenShiftTokenCredentials with Casc yet. There is a [well documented way](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/credentials/credentials.yaml) to create other credentials with Casc such as StringCredentials  (which are [supported by the Kubernetes plugin](https://issues.jenkins-ci.org/browse/JENKINS-49717?focusedCommentId=370339&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-370339)).

I've found a [corresponding TODO tag](https://github.com/openshift/jenkins-client-plugin/blob/b0cedb2efba05208df7cde4c4852165721be9438/src/main/java/com/openshift/jenkins/plugins/ClusterConfig.java#L162) in the sources. Are there any plans to move to a more standardized credentials type?

**Comment by gabemontero** [comment]
no plans as of yet @jaysiee 

we are actually in the process this week among other things of reviewing existing requests for function

we can add this to that list

@akram @waveywaves @siamaksade

**Comment by jaysiee** [comment]
@gabemontero Thanks, I'd appreciate that. I'm sure there are plenty of other ways to achieve this but It would be nice to have uniform way to setup Openshift configuration in Jenkins via code.

**Comment by akram** [comment]
Hi @jaysiee 

we are currently taking a look at this issue. By following the different links you sent, people from the upstream people tends to say that it is now "Resolved" by using the Kubernetes-credentials plugin.

Did you try this plugin in conjunction with the Jenkins-client plugin? If you have any more up to date information feel free to add on comment on this issue because we still need to understand it more.

**Comment by akram** [comment]
We recently re-update the kubernetes plugin which also uses kubernetes-credentials-plugin.
I will close it then.

/close
