### ISSUE TITLE
Start pods in sequence

### ISSUE THREAD

**Issue by Joyce808** [openshift/jenkins-client-plugin#280]
Hello,

My project has multiple pods, A, B, C pods (apps). Each A, B and C has 2 replica count.  We really need to start at least one A pod and one B pod first before any C pod starts. 

I have used below code to verify deployment is successful or not recommended by the doc 

```
openshift.withCluster() {
      openshift.withProject( "${DEV_PROJECT}" ){
      def latestDeploymentVersion = openshift.selector('dc',"${APP_NAME}").object().status.latestVersion
      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
      rc.untilEach(1){
          def rcMap = it.object()
          return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
      }
}
```

My pipeline pseudo code looks like: 
```
scale up 2 A pod
use above code to verify at least one A pod is running
scale up 2 B pod
use above code to verify at least one B pod is running
scale up 2 C pod
use above code to verify at least one C pod is running
```

I have run many times of testing, and the order seems correct 2A -> 2B -> 2C, but I got one test run failed today with 2A -> 1C -> 2B -> 1C. This is not right, Pod C should not be started before one A and one B started. How come the scale up 2C jumped the queue before watch 2B to finish? 

I wonder if i have used the wrong deployment verification logic. Is any method to make sure the pod are started in order? 

Thanks very much!

**Comment by waveywaves** [comment]
Hello @Joyce808 Thank you for opening this issue. 

Can you send the version of the cluster, version of the jenkins image and have you overriden `oc` in your jenkins ?

**Comment by Joyce808** [comment]
I am using 3.9 cluster, jenkins 2.130. I did not override oc and everything directly comes from the jenkins client plugin. 

I found out a way to resolve this by watching the pod instead of watching the replica controller. This is the code: 

`openshift.withCluster(clusterName, tokenId) {
        openshift.withProject(projectName) {
            if (openshift.selector('dc', appName).exists()) {
                def dcObj = openshift.selector('dc', appName).object()
                
                //scale pod
                openshift.apply(dcObj).scale("--replicas=${replicaCount}")
                
                def latestDeploymentVersion = dcObj.status.latestVersion
                echo "latestDeploymentVersion is ${latestDeploymentVersion}"
                
                def podSelector= openshift.selector('pod', [deployment: "${appName}-${latestDeploymentVersion}"])
                if (podSelector.exists()) {
                    podSelector.untilEach {
                        echo "pod: ${it.name()}"
                        return it.object().status.containerStatuses.every {
                            it.ready
                        }
                    }
                }
            }
        }
    }`
