### ISSUE TITLE
Pipeline CPS method mismatch

### ISSUE THREAD

**Issue by mbarbero** [openshift/jenkins-client-plugin#283]
Since upgrade to Jenkins 2.176.1, pipelines using this plugin show warnings:

    expected to call com.openshift.jenkins.plugins.OpenShiftDSL.dieIfWithout but wound up catching com.openshift.jenkins.plugins.OpenShiftDSL.contextContains; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/

    expected to call com.openshift.jenkins.plugins.OpenShiftDSL.dieIfNotWithin but wound up catching com.openshift.jenkins.plugins.OpenShiftDSL.contextContains; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/

    expected to call com.openshift.jenkins.plugins.OpenShiftDSL.dieIfWithin but wound up catching com.openshift.jenkins.plugins.OpenShiftDSL.contextContains; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/

Jenkins version: LTS 2.176.1
OpenShift Client Jenkins Plugin version: 1.0.31

FYI, this is the step:

      steps {
        script {
          openshift.withCluster("${CLUSTER_NAME}") {
            openshift.withProject("${NAMESPACE}") {
              def appSelector = openshift.selector('deployments', [app: "${APP_NAME}", environment: "${ENVIRONMENT}"])
              appSelector.describe()
              def app = appSelector.object()
              app.spec.template.spec.containers[1].image = "${IMAGE_NAME}"+':'+"${IMAGE_TAG}"
              openshift.apply(app)
              timeout(5) {
                appSelector.rollout().status()
              }
            }
          }
        }
      }

**Comment by akram** [comment]
Hi @mbarbero thank you for reporting this. I will have a look at it

/assign @akram

**Comment by akram** [comment]
Hi @mbarbero 

yesterday, we just bumped a new release using  2.176.**2** and we are using the 1.0.38 version of the sync plugin.
I just re-tested yet a simple pipeline similar to yours, and we do not reproduce the issue nor we see a warning. [1]
Can you please update your jenkins-client-plugin to 1.0.38 and make the test? Also, you can update your Jenkins server to   2.176.**2*. A recent security advisory affecting your version has been published.


[1] https://github.com/akram/openshift-agentless-pipeline/blob/master/Jenkinsfile.21762-regression

**Comment by ThomVivet** [comment]
Same message for me with jenkins 2.164.2 since last plugins update.
With the following changes:
- openshift-login 1.0.15 -> 1.0.19
- openshift-pipeline 1.0.55 -> 1.0.56
- openshift-sync 1.0.27 -> 1.0.38
- workflow-cps 2.70 -> 2.72
- workflow-remote-loader 1.4 -> 1.5

**Comment by waveywaves** [comment]
@ThomVivet Please upgrade your Openshift-client plugin to the latest release as well. And let me know if the issue persists.

**Comment by akram** [comment]
Hi @ThomVivet 

Can you provide:
- a full reproducer pipeline 
- your jenkins logs
- your pipeline output result

Thanks.

**Comment by mbarbero** [comment]
I've done the upgrade to 2.176.2 (client plugin is still 1.0.31). Same issues.

**Comment by nc-jape** [comment]
on jenkins 2.164.3,

Changing workflow-cps back to version 2.70, "fixed" the issue for me.

**Comment by akram** [comment]
Hi guys,

based on the Jenkins Worflow CPS plugin changelog [1], you should be hitting the issue if you are using version 2.71+ 

You may have to check that you are not pulling version (2.17+) this plugin from another dependency which would explain why you see the warning+.


[1] https://wiki.jenkins.io/display/JENKINS/Pipeline+Groovy+Plugin#PipelineGroovyPlugin-2.72(11Jul2019)




```
We are for now packaging workflow-cps 2.65 version with the openshift jenkins plugins.
2.71 (05 Jul 2019)
Fix: Allow script-level initializers (including @Field) in sandboxed Pipelines. Fixes a regression from version 2.64. (JENKINS-56682)
Improvement: Print detailed warnings to the build log when CPS-transformed code is called in a non-CPS context where possible. The warnings link to https://jenkins.io/redirect/pipeline-cps-method-mismatches/ which gives additional context and some examples of how to fix common issues. (JENKINS-31314)
```

**Comment by mbarbero** [comment]
Thanks @akram for finding this out. However I don't think it's reasonable to ask users to not pull newer version of pipeline-groovy, especially when the issue on your plugin is caused by an improvement in the dependency. 

Is there any way the openshift client plugin could work better with CPS?

**Comment by akram** [comment]
@mbarbero , we are still having a look at it , don't worry ;-)
we just needed to figure out why we weren't able to reproduce it yet in our packaging of the OpenShift Jenkins Image.

We will keep the issue open now, while investigating it. Can you just confirm that using 2.70 is working for you?

We will be trying to upgrade to the 2.71 version and see the impacts on the other plugins also.

**Comment by philippmoeller** [comment]
Any plan to fix this in the near future?

**Comment by max-l-weaver** [comment]
Also receiving this error when running a pipeline. Downgrading `workflow-cps` to < v2.1 didn't make a difference so having to use an older version of Jenkins for the time being (2.89.3) which is unfortunate. Hopefully there'll be some movement on this issue soon 🤞

**Comment by akram** [comment]
Hi all,
thank you for your feedbacks.
we will put additional efforts to release the new version including the fix asap.

**Comment by akram** [comment]
we will cut the release probably tomorrow.
In the meantime, feel free to report any issue if you run the plugin with a handcrafted version.

**Comment by severi** [comment]
after upgrading to the newest version my pipelines have started failing with the following message
```
ERROR: openshift.withCluster cannot be used within a openshift.withProject closure body
```

Seems like fix for the problem described here could be causing this as the error message comes from the dieIfWithin function
https://github.com/openshift/jenkins-client-plugin/blob/0c359c2a0e9de03a4505aa14869f15f1e110c8d0/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L256

**Comment by waveywaves** [comment]
@severi We have added a fix to dieIfWithin function in the latest release. And seems like you have a withCLuster block inside of the withProject block. It should be defined in the fashion below.
```
openshift.withCluster(){
    openshift.withProject(){
    }
}
```

**Comment by akram** [comment]
@severi : as @waveywaves said: before version 1.0.40 of the jenkins-client-plugin, it was possible to create "syntactically incorrect" pipelines that were still able to work.

You need to ensure that, in your pipeline definition, every withProject() closure is enclosed in a withCluster() closure. The opposite must not work and will not work anymore. And, a "standalone" withProject closure does not work also.

**Comment by severi** [comment]
@waveywaves yeah that much I understood from the output as well :) What I wasnt sure is whether this change was made on purpose or were the results considered thoroughly enough.  

@akram well that is unfortunate to hear. Our shared library has been working perfectly for the past two years until this change was introduced. Kind of feels like a major change rather than a patch to me. The problem in my case isn't as simple as just having a `withProject()` call not enclosed in a `withCluster()`. I have multiple functions that call withCluster+withProject, and a function might call other functions which results in nested withCluster+withProject calls. Of course fixing this is doable but requires quite much rework that I wouldn't have expected from upgrading a plugin from version 1.0.31 to 1.0.32 😐

**Comment by Reamer** [comment]
Hi @akram,
thanks for fixing this issue. I updated successfully the plugin and warnings disappear. I think we can close this issue.

**Comment by akram** [comment]
> @waveywaves yeah that much I understood from the output as well :) What I wasnt sure is whether this change was made on purpose or were the consequences considered thoroughly enough.
> 
> @akram well that is unfortunate to hear. Our shared library has been working perfectly for the past two years until this change was introduced. Kind of feels like a major change rather than a patch to me. The problem in my case isn't as simple as just having a `withProject()` call not enclosed in a `withCluster()`. I have multiple functions that call withCluster+withProject, and a function might call other functions which results in nested withCluster+withProject calls. Of course fixing this is doable but requires quite much rework that I wouldn't have expected from upgrading a plugin from version 1.0.31 to 1.0.32 😐


Hi @severi , 
we had to upgrade Jenkins Worflow CPS plugin  to a higher version because of a CVE/Security issue. Following this upgrade, we also fixed a long lasting bug that also may introduce instability and prevent "safe" restarts and job continuation of Jenkins Jobs. And this is what 1.0.32 also provides.

I regret that the impacts where important in your case, you can still "force" a downgrade to 1.0.31 to give you more time to fix the issue.
