### ISSUE TITLE
Creating objects is not easy

### ISSUE THREAD

**Issue by sbarre-esit** [openshift/jenkins-client-plugin#286]
https://github.com/openshift/jenkins-client-plugin#creating-objects-easier-than-you-were-expecting-hopefully says you can just define a map of an thing you want to create, but I'm getting an error. Anyone else have any luck doing this?
> Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (com.openshift.jenkins.plugins.OpenShiftDSL Create java.util.LinkedHashMap)

```groovy
    stage("Test") {
      agent any
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {

              def podspec = [
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": [
                  "name": "foo"
                ]]
              def pod = openshift.Create(podspec)
            }
          }
        }
      }
    }

**Comment by akram** [comment]
Hi @sbarre-esit 
the method create starts with a lower case "c". Could you please try this?

feel free to close the issue if it solves the problem.

**Comment by sbarre-esit** [comment]
I ended up having to whitelist the method in `scriptApproval.xml` to make Jenkins happy.

```xml
<?xml version='1.1' encoding='UTF-8'?>
<scriptApproval plugin="script-security@1.56">
  <approvedSignatures>
    <string>method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object</string>
  </approvedSignatures>
</scriptApproval>
```

**Comment by TomSchmitz** [comment]
Ich bin bis 05.08.2019 abwesend.
I am out of the office until 05.08.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Creating objects is not easy (#286)"
gesendet am 01.08.2019 18:02:52.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TomSchmitz** [comment]
Ich bin bis 05.08.2019 abwesend.
I am out of the office until 05.08.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Creating objects is not easy (#286)"
gesendet am 01.08.2019 18:02:55.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
