### ISSUE TITLE
Job name with spaces causes "Unknown command" error

### ISSUE THREAD

**Issue by schuch** [openshift/jenkins-client-plugin#292]
The `--certificate-authority` command line argument is not quoted when the certificate path contains spaces. Parts of the certificate path are interpreted as oc command.

The job that produced the following output is named `test iam-a-funky-command-from-the-job-name`

The pipeline script is minimal:
```
node('agent1') {
    withEnv(["PATH+OC=${tool 'oc3.7.2'}"]) {
        openshift.withCluster( 'mycluster' ) {
            echo "${openshift.raw( "version" ).out}"
            echo "In project: ${openshift.project()}"
        }
    }
}
```

This output demonstrates the problem:
```
ERROR: raw command [version] returned an error;

{reference={}, err=Error: unknown command "iam-a-funky-command-from-the-job-name/serverca8193261019186119850.crt" for "oc"

Run 'oc --help' for usage.

, verb=, cmd=oc --server=https://obscured-openshift-url --certificate-authority=/home/johndoe/.jenkins/workspace/test iam-a-funky-command-from-the-job-name/serverca8193261019186119850.crt --namespace=dbsearch --token=XXXXX  version , out=, status=1}
```
Plugin version `1.0.32`

Seems related to #257

**Comment by waveywaves** [comment]
Hello @schuch,
Thank you for opening this issue.

This seems like a simple issue with simple string parsing. 
We will look into this and update it here.

**Comment by akram** [comment]
/assign akram

needs to change in "	public List<String> buildCommand(boolean redacted)  "  in ClientCommandBuilder

**Comment by akram** [comment]
OK,

reproduced using the following pre-req:
- do no use the sync plugin
- create manually a "folder" in Jenkins
- create an openshift cluster name 'test' with a certificate 
- create a pipeline with the following code:
```
#!/usr/bin/env groovy

import java.text.SimpleDateFormat

pipeline {
  agent { node { label 'nodejs' } }
  options { timeout(time: 20, unit: 'MINUTES') }
  stages {
    stage('raw') {
      steps {
        script {
          openshift.withCluster() {
            def currentProject
            openshift.withProject('test') {
              echo "${openshift.raw( "version" ).out}"
              echo "In project: ${openshift.project()}"
            }
          }
        }
      }
    }
  }
}

```

**Comment by cniweb** [comment]
When will this bug be fixed?
We have the same problem!

**Comment by cniweb** [comment]
@waveywaves When will it continue here?
