### ISSUE TITLE
Waiting for single build

### ISSUE THREAD

**Issue by Gladskih** [openshift/jenkins-client-plugin#293]
Comment in [example](https://github.com/openshift/jenkins-client-plugin#watching-and-waiting-of-course) states:
> A robust script should not assume that only one build has been created so we will need to iterate through all builds.

And I really can't find API for manipulation by single object at once strictly.

Why? I need to start one build only once and wait for it compilation. Why should I assume there are multiple builds?

**Comment by waveywaves** [comment]
Hello @Gladskih 
Thank you for opening up this issue.

As it is possible that multiple resources are created at a time, and it is usually never the case that only a single ones would be createed and consumed. You can always check the number of builds to be equal to one, and if it is equal to one, you can query it to your need accordingly. Can you elaborate on what you mean by `manipulate ` here ? As it implies that you are trying to make changes to the build during runtime, which I am not sure how it would fare.

cc @akram

**Comment by Gladskih** [comment]
By manipulate I mean waiting.
If I start build I expect only one would be started.
The same is true for a deployment.
It's really awkward, that API concerns so uncommon scenario of multiple objects creation at once as main.

**Comment by akram** [comment]
> By manipulate I mean waiting.
> If I start build I expect only one would be started.
> The same is true for a deployment.
> It's really awkward, that API concerns so uncommon scenario of multiple objects creation at once as main.

Hi @Gladskih ,

I think that what you want to achieve is implemented through RunPolicy [1] on BuildConfig.
See link below.


You are maybe using builds with Parallel run policy, and as you noticed, and as you can read, "This can produce unpredictable results".

[1] https://docs.openshift.com/container-platform/3.11/dev_guide/builds/build_run_policy.html
[2] https://docs.openshift.com/container-platform/3.11/dev_guide/builds/build_run_policy.html#build-parallel-run-policy

**Comment by akram** [comment]
Based on the provided explanations this should be a solution

/close
