### ISSUE TITLE
build.untilEach cause pipeline failure

### ISSUE THREAD

**Issue by Gladskih** [openshift/jenkins-client-plugin#294]
On Jenkins 2.172
Having script in a stage:
```
...
openshift.withCluster(myCluster)
{
	openshift.withProject(myProject)
	{
		def build = openshift.selector( 'bc', 'mybuild' ).startBuild();
		build.untilEach(1)
		{
			return true
		}
	}
}
...
```
I get pipeline failure with console output:

> ...
> Running on myNodeServer
> ...
> [Pipeline] _OcContextInit
> [Pipeline] _OcContextInit
> [Pipeline] _OcAction
> [Pipeline] _OcAction
> [Pipeline] _OcAction
> [Pipeline] _OcWatch
> Entering watch
> Running watch closure body
> [Pipeline] {
> [Pipeline] _OcAction
> [Pipeline] }
> watch closure returned true; terminating watch
> [Pipeline] // _OcWatch
> [Pipeline] }
> ...
> [Pipeline] End of Pipeline
> Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to 
> 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
> 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
> 		at hudson.remoting.Channel.call(Channel.java:957)
> 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
> 		at com.sun.proxy.$Proxy102.getArguments(Unknown Source)
> 		at hudson.util.ProcessTree$Remote$RemoteProcess.getArguments(ProcessTree.java:1888)
> 		at hudson.plugins.msbuild.MsBuildKillingVeto.vetoProcessKilling(MsBuildKillingVeto.java:56)
> 		at hudson.util.ProcessTree$OSProcess$CheckVetoes.call(ProcessTree.java:351)
> 		at hudson.util.ProcessTree$OSProcess$CheckVetoes.call(ProcessTree.java:341)
> 		at hudson.remoting.UserRequest.perform(UserRequest.java:212)
> 		at hudson.remoting.UserRequest.perform(UserRequest.java:54)
> 		at hudson.remoting.Request$2.run(Request.java:369)
> 		at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
> 		at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:19)
> 		at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
> 		at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
> 		at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
> 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 		at java.lang.Thread.run(Thread.java:748)
> Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to channel
> 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
> 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
> 		at hudson.remoting.Channel.call(Channel.java:957)
> 		at hudson.util.ProcessTree$OSProcess.getVeto(ProcessTree.java:277)
> 		at hudson.util.ProcessTree$WindowsOSProcess.killRecursively(ProcessTree.java:516)
> 		at hudson.util.ProcessTree.killAll(ProcessTree.java:170)
> 		at hudson.Proc$LocalProc.destroy(Proc.java:384)
> 		at hudson.Proc$LocalProc.kill(Proc.java:376)
> 		at hudson.Launcher$RemoteLaunchCallable$1.kill(Launcher.java:1338)
> 		at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to myNodeServer
> 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
> 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
> 		at hudson.remoting.Channel.call(Channel.java:957)
> 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
> 		at com.sun.proxy.$Proxy85.kill(Unknown Source)
> 		at hudson.Launcher$RemoteLauncher$ProcImpl.kill(Launcher.java:1119)
> 		at com.openshift.jenkins.plugins.util.ClientCommandRunner.run(ClientCommandRunner.java:155)
> 		at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:163)
> 		at com.openshift.jenkins.plugins.pipeline.OcWatch$Execution.run(OcWatch.java:74)
> 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
> 		at hudson.security.ACL.impersonate(ACL.java:290)
> 		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
> 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 		at java.lang.Thread.run(Thread.java:748)
> org.jvnet.winp.WinpException: **Process with pid=9568 is not a 32bit process (or it is not running). Cannot query it from a 32bit library** error=268435458 at envvar-cmdline.cpp:183
> 	at org.jvnet.winp.Native.getCmdLine(Native Method)
> 	at org.jvnet.winp.WinProcess.parseCmdLine(WinProcess.java:151)
> 	at org.jvnet.winp.WinProcess.getCommandLine(WinProcess.java:126)
> 	at hudson.util.ProcessTree$WindowsOSProcess.getArguments(ProcessTree.java:569)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
> 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
> 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
> 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
> 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
> 	at hudson.remoting.Request$2.run(Request.java:369)
> 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Finished: FAILURE

Where myNodeServer is Windows Server 2016  with **x86** Jenkins worker

**Comment by akram** [comment]
Hi @Gladskih ,

can you please describe your run environment, and especially how you build your agent images ?
You are pointing this error, if I understand correctly?
```
org.jvnet.winp.WinpException: Process with pid=9568 is not a 32bit process (or it is not running). Cannot query it from a 32bit library error=268435458 at envvar-cmdline.cpp:183
```

Did you identify which process the message is talking about? 
Is it a standalone Jenkins? running on Windows? or only the agent node is running on windows?

Could you please be more accurate with the issues descriptions? it is really hard to figure out about the context.

**Comment by Gladskih** [comment]
@akram To be more accurate with issue description I need to be more familiar with the tool I have the issue with. So in case like this I can only assis you in "pull strategy" of knowlege management.

I have extremely heterogeneous environment: master node (amd64) is on Linux and worker (x86) node is on Windows Server 2016.

I did not identify the process meant in log but I can try to do it latter if it's really needed (I thought the script is enough).

**Comment by akram** [comment]
Yes please, I think this should help understanding the issue.

**Comment by akram** [comment]
@Gladskih we didn't get any feedback from you regarding this; based on the provided logs it looks like more to be related to org.jvnet.winp.Winp library which crashes because it cannot read the state of a 32 bit while the library itself is running in a 64bits JVM. This apparently the case for you.

You have the option to run Jenkins on 32 bits using 4.2.x or lower images using a 32bit hots. The 32bits JVM is automatically selected based on what  `uname` reports.

But you should look at this bug, it looks like similar: https://issues.jenkins-ci.org/browse/JENKINS-52868



/close

**Comment by Gladskih** [comment]
@akram Sorry for no feedback, we were urgently migrating to GitLab.
