### ISSUE TITLE
Direct oc call ignores openshift.withProject

### ISSUE THREAD

**Issue by Gladskih** [openshift/jenkins-client-plugin#295]
Faced the https://github.com/openshift/jenkins-client-plugin/issues/294 and looking for a workaround I was trying to "downgrade" my script mixing plugin API calles with oc calles:
```
openshift.withCluster(myCluster)
{
    openshift.withProject(myProject)
    {
        **bat "oc status"**
    }
}
```
But here I have another problem. Inner oc call operates on default project, not myProject specified in `openshift.withProjec()`

**Comment by akram** [comment]
This issue has been stale for more than 90 days, so closing it
/close
