### ISSUE TITLE
Add a DeploymentConfig scale example

### ISSUE THREAD

**Issue by samueltauil** [openshift/jenkins-client-plugin#296]
In the readme there is no example on how to use the Selector.scale(), what are the parameters? `replicas` ?

**Comment by akram** [comment]
Hi @samueltauil ,

Thank you for submitting this issue and for using the plugin.
The current implementation of the Jenkins client plugin uses a kind of passthrough arguments to many underlying `oc` command to simplify implementation, including the scale function/method which worked quite well. [1]

For this reason, the regular way to pass parameters to invoke "groovy implemented" commands uses the same pattern as the oc commands modifiers. [2]

I will keep your issue open and we will work on updating the documentation to provide a simple example and then probably implement what you recommend depending on time we have.

We also accept Pull Requests (PRs); so feel free to propose a backward compatible implementation, and we would be happy to merge.



[1] https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1605
[2] https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1583

**Comment by danielalejandrohc** [comment]
I agree the current scale method is not intuitive, Could be just like this: 

openshift.selector("dc", "tasks").scale(3);  // (removing the "replicas")?
