### ISSUE TITLE
Subsequent openshift.withCluster does not switch clusters

### ISSUE THREAD

**Issue by Gladskih** [openshift/jenkins-client-plugin#297]
Subsequent calls like:
```
openshift.withCluster(clusterA)
{
	bat "oc project MyProject"
}
openshift.withCluster(clusterB)
{
	bat "oc project MyProject"
}
```
do not switch cluster and `oc project` call in closure for clusterB is still executed with clusterA.

**Comment by waveywaves** [comment]
Thank you for opening this issue with us. Sorry for the late response.
WIll check this out and get back to you ASAP.

**Comment by akram** [comment]
I am closing it in favour of #300 because it is a replicate.
/assign @sunnyconcise
will also take a look at it

/close
