### ISSUE TITLE
Seperating cluster context when deploying to multiple deployment clusters

### ISSUE THREAD

**Issue by markperdue** [openshift/jenkins-client-plugin#300]
Hello,

I am running into an issue using the plugin that is not encountered when running `oc` cli directly. When running on one of the openshift provided Jenkins agents (which itself is running within openshift) the openshift.withCluster() syntax does not seem to allow other tools that leverage the default KUBECONFIG context to work properly.

**Use case:**
Deploy a helm chart to each of the deployment openshift clusters using the openshift client plugin

**Example:**
```
node('label-that-runs-rh-provided-agent-within-one-of-the-openshift-clusters') {
    openshift.withCluster(clusterA) {
        sh 'helm ls'
    }
    openshift.withCluster(clusterB) {
        sh 'helm ls'
    }
}
```

**Expected behavior:**
helm would list the helm releases in the default project of clusterA (line 3)
helm would list the helm releases in the default project of clusterB (line 6)

**Actual behavior:**
helm would list the helm releases in the default project of whichever openshift cluster relates to 'label-that-runs-rh-provided-agent-within-one-of-the-openshift-clusters' (line 3)
helm would list the helm releases in the default project of whichever openshift cluster relates to 'label-that-runs-rh-provided-agent-within-one-of-the-openshift-clusters' (line 6)

**Request**
Is there a way to use a specific clusters context to allow the above use case? Workarounds like below do get close to working but often lead to issues with subsequent openshift client plugin calls having a modified KUBECONFIG file that then takes precedence.

Tools like helm support a `--kube-context` flag but I don't see any reference in the openshift client plugin documentation to fetch this to then pass as `--kube-config` to helm cli when using openshift.withCluster(). Is there a way to accomplish that perhaps?

**Workaround but a workaround that causes other issues**
```
node('label-that-runs-rh-provided-agent-within-one-of-the-openshift-clusters') {
    openshift.withCluster(clusterA) {
        sh 'oc login'
    }
    openshift.withCluster(clusterB) {
        sh 'oc login'
    }

  // $KUBECONFIG now has entries related to both clusterA and clusterB from the `oc login`

    openshift.withCluster(clusterA) {
        openshift.raw('config use-context clusterAContext')
        sh 'helm ls'
    }
    openshift.withCluster(clusterB) {
        openshift.raw('config use-context clusterBContext')
        sh 'helm ls'
    }
}
```

Any ideas?

**Comment by akram** [comment]
@sunnyconcise could you please take a look at this one?

**Comment by sunnyconcise** [comment]
Tried to recreate the error using a node-js application - [https://github.com/sunnyconcise/nodejs-ex](https://github.com/sunnyconcise/nodejs-ex)

Attaching the build ouput 

![Screenshot from 2019-10-21 22-00-13](https://user-images.githubusercontent.com/50203761/67226127-0d59df00-f452-11e9-8bd3-e8650623c73c.png)


The build runs on the same cluster , the jenkinsfile code below doesnt seem to work

 openshift.withCluster('cluster2') {
                    openshift.withProject() {
                        sh 'oc status'
                    }

**Comment by sunnyconcise** [comment]
when I rsh into the pod I do not get any extra contexts. There are no multiple contexts set in the jenkins pod, that means that default is being used both times.

**Comment by itewk** [comment]
Any movement on this?

**Comment by itewk** [comment]
Determined the following works for anyone looking for workaround:

```
openshift.withCluster('cluster2') {
openshift.withProject() {
openshift.raw(“login”)
sh 'oc status'
}
```

**Comment by akram** [comment]
Hi @itewk 

thank you for reporting the workaround.
I had a look at it a while ago, I will return to it now that you gave this additional workaround, maybe I can find the solution
