### ISSUE TITLE
openshift.rsync operation failing with "java.io.IOException: invalid null character in command"

### ISSUE THREAD

**Issue by saikirandusari** [openshift/jenkins-client-plugin#303]
Hello

I have a pipeline where I am using openshift.rsync() method to copy a directory from one pod to another within the same project/namespace.

`openshift.rsync("${jobPod}:/jmeter/results", "${WORKSPACE}")`

`jobPod=jmeter-master-test-suite-kkkjf`

**OpenShift Server and Client Version** 
```
INFO: oc v3.11.146
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx.xx.xxxxxxx.com:8443
openshift v3.11.129
kubernetes v1.11.0+d4cacc0
```

Here are the logs

```
INFO: Copying report files from jmeter-master-test-suite-kkkjf to Jenkins /var/lib/jenkins/jobs/my-project/jobs/test-pipeline-jmeter/workspace
[Pipeline] readFile
[Pipeline] _OcAction
found the following oc executables on the target computer of OS type UNIX: [/usr/bin/oc, /bin/oc]
Verbose sub-step output:
	Command> oc --server=https://xxx.xx.xxxxxxxx.com:8443 --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --namespace=my-project --loglevel=9 --token=$(oc whoami -t) rsync jmeter-master-test-suite-kkkjf:/jmeter/results /var/lib/jenkins/jobs/my-project/jobs/test-pipeline-jmeter/workspace 
	Status> -1
	StdOut>
	StdErr> 
	Reference> {}
[Pipeline] echo
An exception occurred while running JMeter test: java.io.IOException: invalid null character in command
```

But, if I `rsh` into the pod (Jenkins pod) and run the same command manually it works without any issues.

Any help here would be much appreciated.

Thanks
Sai

**Comment by akram** [comment]
Hi @saikirandusari 

I suppose that you are doing this in a pipeline. Can you tell us if you are using a specific withCredentials() to connect to the cluster?

To help you debug, can you tell me what it is the return code of the oc rsync command in case you are running manually into the pod?

```
oc rsh your-pod
oc rsync source-pod:/src-dir dest-pod:/dst-dir
# it finishes succesfully right? then run the following:
echo $?

```

**Comment by saikirandusari** [comment]
Hi @akram 

Thanks for the quick response. Much appreciated.

Yes, I am performing rsync in the pipeline and I don't use specific withCredentials() (the jenkins pod runs with `jenkins` service account, I suppose it uses jenkins service account credentials by default)

The return code of the `oc rsync` command was `0` 

Thanks
Sai

**Comment by akram** [comment]
@saikirandusari sorry for the delay.
It looks like you are using a 3.11 `oc` binary in your image? can you also give a try by targeting the original 3.6 `oc` binary?

**Comment by saikirandusari** [comment]
@akram  sure, let me try with 3.6 `oc` binary, will come back with the results

**Comment by akram** [comment]
as this issue is getting stale for more than 90 days, we are closing it
/close
