### ISSUE TITLE
Example in readme for openshift.create throwing exception

### ISSUE THREAD

**Issue by matthiassommer** [openshift/jenkins-client-plugin#312]
Instead of 

```
def created = openshift.create( models )
echo "The template instantiated: ${models.names()}"
```

it should be 

```
def created = openshift.create( models )
echo "The template instantiated: ${created.names()}"
```

**Comment by waveywaves** [comment]
@matthiassommer Thanks for the check. I see that this example is present in https://github.com/openshift/jenkins-client-plugin#cannot-live-without-openshift-templates-no-problem .   PRs are much welcome :)
