### ISSUE TITLE
selector with negated labels

### ISSUE THREAD

**Issue by mjovanovic0** [openshift/jenkins-client-plugin#316]
Hi all,

I would like to execute `openshift.selector("ns", [customLabel: 'value'])` but with negated label selector.

So I would like to execute the command:
```
oc get ns -l customLabel!=value
```

I trace the source code and found code that generates label selector:
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L1248

Here is strict definition `%s=%s`.

I'm ready to contribute to this improvement but would like to discuss how DSL API should look first.

**Comment by akram** [comment]
Hi @mjovanovic0 

sure, the project is open to constructive discussions and contributions.
