### ISSUE TITLE
Failed Stage Indicating Weirdly in Web UI

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/jenkins-client-plugin#32]
From [this snippet of Jenkinsfile](https://github.com/openshift/release/blob/master/jenkins/setup/pipeline/Jenkinsfile#L63-L96):

```groovy
    stage("Generate ConfigMaps") {
      steps {
        script {
          openshift.withCluster() {
            // Create the build and run it
            def builderObjects = openshift.process("--filename=jenkins/setup/resources/config-generator-build.yaml")
            openshift.apply(builderObjects)
            def jobBuilder = openshift.selector("buildconfig/configmap-job-builder")
            sh "cp -R jenkins/library/src jenkins/setup/images/config-job-image"
            openshift.startBuild("configmap-job", "--from-dir=./jenkins/setup/images/config-job-image", "--follow")

            // Wait for an imagestream tag for the builder to be available
            def imageStream = openshift.selector("imagestream/configmap-job")
            def jobImageRef = ""
            imageStream.watch {
              is = it.object()
              if ((is.status.tags != null) && (is.status.tags.size() > 0)) {
                jobImageRef = is.status.tags[0].items[0].dockerImageReference
                return true
              }
            }

            openshift.selector("job/configmap-job").delete("--ignore-not-found")

            // Run the job to create config maps
            def configMapJob = openshift.process(
              "--filename=jenkins/setup/resources/config-generator-job.yaml",
              "-p", "JOB_IMAGE=${jobImageRef}",
              "-p", "JENKINS_ADMIN_SA=${env.JENKINS_ADMIN_SA}")
            openshift.apply(configMapJob)
          }
        }
      }
  }
```

I see in the logs:

```
apply returned an error;
{
  "reference": {
    "/tmp/apply1725148177158694347.markup": {
      "apiVersion": "v1",
      "kind": "List",
      "items": [
        {
          "metadata": {
            "name": "configmap-job",
            "labels": {
              "template": "configmap-job",
              "job-name": "configmap-job"
            }
          },
          "apiVersion": "batch/v1",
          "kind": "Job",
          "spec": {
            "template": {
              "metadata": {
                "labels": {
                  "job-name": "configmap-job"
                }
              },
              "spec": {
                "dnsPolicy": "ClusterFirst",
                "containers": [
                  {
                    "name": "configmap-setup",
                    "image": "172.30.1.1:5000/jenkins/configmap-job@sha256:ec005904f8f950d128deb6216ae0dd0a2a79bad8d0bcf93164285394787d6930",
                    "imagePullPolicy": "IfNotPresent",
                    "resources": {}
                  }
                ],
                "securityContext": {},
                "restartPolicy": "Never",
                "serviceAccountName": "jenkins-admin"
              }
            },
            "completions": 1,
            "activeDeadlineSeconds": 600,
            "parallelism": 1
          }
        }
      ]
    }
  },
  "err": "Error from server (NotFound): the server could not find the requested resource",
  "verb": "apply",
  "cmd": "oc apply -f /tmp/apply1725148177158694347.markup -o=name --server=https://172.30.0.1:443 --namespace=jenkins --token=XXXXX",
  "out": "",
  "status": "1"
}
```

But the web UI does not show a failed step:

![jenkins_bad](https://user-images.githubusercontent.com/7328370/26941322-f3e82b2c-4c32-11e7-928d-755d3cd1d98b.png)

**Comment by gabemontero** [comment]
hey @stevekuznetsov - Given the contents of that message, starting with the `;` appearing, then the AbortException is thrown [here](https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L736)

At that point, how the UI renders is in the hands of the pipeline code, and beyond the scope of the openshift client plugin.  Perhaps it has something to do with the use of `step { ... script { ...`

And throwing the Abort per everything we've seen is the right thing to do.

If there is doubt that the abort exception is being thrown, and if this is at all reproducible, you can temporarily but a try/catch around the apply to confirm.

@jupierce - any additional thoughts or items you think I might be overlooking?

**Comment by stevekuznetsov** [comment]
If this is an error on the GUI side of things -- where should I report it?

**Comment by gabemontero** [comment]
Per https://wiki.jenkins-ci.org/display/JENKINS/Blue+Ocean+Plugin I would follow the "Issue tracking" link which takes you to https://issues.jenkins-ci.org and the blue ocean category.

Aside from confirming the AbortException was thrown which I mentioned previously beforehand, as a heads up, I bet they are going to ask for a simplified test case for them to repro with, full logs, etc.

**Comment by gabemontero** [comment]
Going to go ahead and close ... of course reopen if new evidence like the AbortException not getting thrown emerges.

**Comment by jupierce** [comment]
It looks like something is catching the exception and printing it out instead of allowing the job to fail. 

The message you are seeing is constructed here and just the content of the AbortException: https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L729

This has traditionally been enough to stop a pipeline from executing. Perhaps declarative syntax handles exceptions differently?

What happens if you put an
`error( "This should stop the job") `
in your script somewhere? Is that exception swallowed as well?

ref: https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#code-error-code-error-signal

**Comment by gabemontero** [comment]
thanks @jupierce - the OpenShiftDSL.groovy link you posted lines up with the one I posted in https://github.com/openshift/jenkins-client-plugin/issues/32#issuecomment-307397992 

some goes wrt the new syntax and possible exception handling ...i.e. `step { .. script {...`

so all good on those points (thanks again) :-)

Didn't know about `error(...)` ... thanks for the tip / I agree a good sanity check for @stevekuznetsov to try.

If `error(...)` kills the job and throwing AbortException does not, then I suppose we use this bug to switch client plugin and OpenShiftDLS.groovy to use `error(...)` .... agree ?

**Comment by gabemontero** [comment]
Though it is interesting that the doc for that step says:  `You can also just throw new Exception(), but this step will avoid printing a stack trace. `
