### ISSUE TITLE
openshiftVerifyDeployment / openshiftDeploy is failing while running in Jenkins

### ISSUE THREAD

**Issue by Aaqib041** [openshift/jenkins-client-plugin#321]
Hi Team,

All of a sudden , I started facing issue with openshiftDeploy / openshiftVerifyDeployment  /  openshiftVerifyBuild / openshiftDeploy functions used in Jenkins pipeline. Whereas same is working with oc commands like oc start-build / oc deploy --latest dc/${appName} .....

Can you please look into issue and guide me to solution ? Share more information below .

I am using openshift jenkins ( version : 2.176.2 ).
Below are openshift plugin versions used : 

OpenShift Client Jenkins Plugin : 1.0.32

**Pipeline stages failing :**

stage("Deploy_App") {
            openshift.withCluster() {
                openshift.withProject("${project}") {
                    openshiftDeploy deploymentConfig: appName, namespace: project
                }
            }
        }

        stage ('Check deployment'){
            openshift.withCluster() {
                openshift.withProject("${project}") {
                    openshiftVerifyDeployment deploymentConfig: appName, waitTime: '360000'
                }
            }
        }

**Stages working:**

stage("Deploy") {
            //openshiftDeploy deploymentConfig: appName, namespace: project
            sh """
                oc deploy --latest dc/${appName}  
                oc logs -f dc/${appName} 
            """
        }

Regards,

**Comment by akram** [comment]
Hi @Aaqib041 ,

can you tell me which jenkins image are you using?
Also, it is more appropriate to open the issue in openshift/jenkins repository, as the syntax that you are mentionning is not related to jenkins-client-plugin.

If you need to migrate to jenkins-client-plugin, please consider reading the doc below. 

https://github.com/openshift/jenkins-client-plugin/blob/8715bb49d1336cba5659c850d05f533d9c83212e/README.md#looking-to-verify-a-deployment-or-service-we-can-still-do-that

The syntax you are mentioning is part of the deprecated plugin openshift/jenkins-plugin

**Comment by Aaqib041** [comment]
Hi @akram ,

Thanks for the response.

I have tried testing below mentioned Jenkins Images : 
 image: 'registry.redhat.io/openshift4/ose-jenkins:v4.1.14'
 image: 'registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.9'

Also , I have tried with below snippet which is also failing. Please suggest.

****stage("Deploy") {
    def dc = openshift.selector('dc', "${APP_NAME}")
    dc.rollout().latest()
}**
                        
stage ('Check deployment'){
    timeout(900) {
        def latestDeploymentVersion = openshift.selector('dc',"${APP_NAME}").object().status.latestVersion
        def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
            rc.untilEach(1){
                def rcMap = it.object()
                return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
            }
    }
}**

**Comment by akram** [comment]
@Aaqib041 : can you share logs for both of the situations ?

**Comment by Aaqib041** [comment]
@akram Looks like ticket is open on Bugzilla for same. I have shared required logs over there. Please check.

https://bugzilla.redhat.com/show_bug.cgi?id=1793878

**Comment by akram** [comment]
Hi @Aaqib041 
I have updated some informations there.

**Comment by akram** [comment]
Hi @Aaqib041
there is patch-002 update

**Comment by Aaqib041** [comment]
Hi @Akram,

I have shared the latest logs. Please check

Regards,
Akeeb K Y
