### ISSUE TITLE
Bug 1800771: Pipeline doesn't reflect updated code from Jenkinsfile

### ISSUE THREAD

**Issue by waveywaves** [openshift/jenkins-client-plugin#322]
## Description of problem:
New code commited into gitlab isn't being picked up by jenkins pod

Version-Release number of selected component (if applicable): OpenShift Dedicated 3.11
Jenkins image. Latest update for OSD 3

## How reproducible:

100 %

## Steps to Reproduce:
1. Deploy a new-app with a Jenkinsfile on OCP 
`oc new-app  https://gitlab.com/openshift-samples/node-example.git --strategy=pipeline `
2. Wait for the pipeline to be complete. (approve it on jenkins)
3. Add a new stage (Edit Jenkinsfile in git repo) and commit the code
4. Start a new pipeline

## Actual results:
Pipeline doesn't get the new code from gitlab

## Expected results:
Pipeline should fetch the new code from source

### Additional info:
Workaround is to remove the `/var/lib/jenkins/jobs/.../jobs/.../workspace@script` dir inside the jenkins pod and trigger a new pipeline from OCP.
This started to happen with latest jenkins image update.
Running the same flow with an older jenkins image works >> Edit Jenkins Deployment and select tag 1 under `Images` > Save

**Comment by akram** [comment]
@waveywaves this has to be opened wrt to jenkins or jenkins-sync-plugin, but not in client plugin.
can you re-create there ?

**Comment by waveywaves** [comment]
Moved to https://github.com/openshift/jenkins-sync-plugin/issues/373
