### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by gsouzab** [openshift/jenkins-client-plugin#328]
As stated in the [Openshift Docs](https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authentication.html#authentication-impersonation), it's possible to impersonate users using the `oc` cli flag `--as=<user>`. Does the plugin has support for this flag? 

I could of course use `openshift.raw`, but as I wanted to leverage some of the build in functionalities. I managed to get the desired behaviour by appending the flag into a selector, e.g.
```
    def dc = openshift.selector('dc/app --as=username')
    dc.rollout().latest()
    dc.rollout().status()
```
Is there a better approach to achieve it or can I go with this (seems kinda hacky to me though) ?

**Comment by akram** [comment]
Hi @gsouzab ,

thanks for using the plugin. We do not support impersonnating using a specific parameter. So, what you describe is indeed to the different ways to achieve it
