### ISSUE TITLE
Issue with startBuild().logs when starting an NPM project 

### ISSUE THREAD

**Issue by jland-redhat** [openshift/jenkins-client-plugin#347]
Hey Guys,

In your read me you have an example:
```
    // And if after some processing within your pipeline, if you decide
    // you need to initiate a new build after the one initiated by
    // new-app, simply call the `oc start-build` equivalent:
    def buildSelector = bc.startBuild()
    buildSelector.logs('-f')
```

Just wanted to let you know that when you do that with an NPM project the selector that is returned back ends up looking like this
`selector([name=null],[labels=null],[namelist=[Uploading directory "build" as binary input for the build ..., ., Uploading finished, build/manager-360-front-3]],[projectlist=null])`

Which causes issues when you try to use the `.logs` method. My team was able to work around it by just using the `.selector` method like this
```
   buildConfig.startBuild("--from-dir=build")
   builds = buildConfig.related('builds')
   builds.logs('-f')
```

Not sure this is actually a bug or just needs a readme update. But just don't want other folks spinning their wheels on the same issue.

**Comment by akram** [comment]
Thanks @jland-redhat 
you are right, there is a `.related('builds')` missing
I will update the README.md
