### ISSUE TITLE
How do I enter the password for my service account?

### ISSUE THREAD

**Issue by aditya-malviya** [openshift/jenkins-client-plugin#349]

**Comment by aditya-malviya** [comment]
I guess you missed in your documentation to tell us more about entering password and config

**Comment by akram** [comment]
Hi @aditya-malviya , can you explain what you want to do?

**Comment by aditya-malviya** [comment]
Hi,

I'm trying to add my openshift service account cred in Opneshift client
plugins in
Jenkins -> Manage -> config -> Cluster Configurations
but after adding the cred I don't see my user and pass in the drop down in
cred section, but If I add token it works which I dont want to try.


[image: Capture.PNG]

**Comment by aditya-malviya** [comment]
I'm trying to add my openshift service account cred in Opneshift client plugins inJenkins -> Manage -> config -> Cluster Configurationsbut after adding the cred I don't see my user and pass in the drop down in cred section, but If I add token it works which I dont want to try.

**Comment by aditya-malviya** [comment]
I figured it an alternative way to do so.
