### ISSUE TITLE
How do I enter Service account credentials while Configuring an OpenShift Cluster

### ISSUE THREAD

**Issue by aditya-malviya** [openshift/jenkins-client-plugin#350]
When I add Opensfhit username and password it never gets reflected in drop down, but when I add token it works.

**Comment by aditya-malviya** [comment]
I'm following this https://github.com/openshift/jenkins-client-plugin#installing-and-developing and wish to implement using Jenkins. The problem I'm getting is I'm not able to add the password in Jenkins -> config. It only accepts token, is there a way I can pass passwords directly in my jenkinsfile or add in cluster config

**Comment by dzabel** [comment]
Create a secret holding your credentials and afterwards label this secret using 
`credential.sync.jenkins.openshift.io=true`

Example using Service Account Token from jenkins:

```
JENKINS_TOKEN_DEV=$(oc sa get-token jenkins)

oc create secret generic default-registry-token --from-literal=username=jenkins \
 --from-literal=password=$JENKINS_TOKEN_DEV
oc label secret default-registry-token credential.sync.jenkins.openshift.io=true
```
Jenkins will sync the secret an you can use it afterwards. This feature is provided by jenkins-sync-plugin.
https://github.com/openshift/jenkins-sync-plugin
