### ISSUE TITLE
Can't get api token from com.openshift.jenkins.plugnis.OpenShiftTokenCredentials in pipeline

### ISSUE THREAD

**Issue by maxt** [openshift/jenkins-client-plugin#366]
Hello.
I'm faced with a scenario, where I have jenkins with credentials for openshift of type OpenShiftTokenCredentials on the one hand and ansible on the other. 
I  use ansible for deployemnt, so I just want to find a way to pass api token from credential to the playbook.

The problem is that I can't handle OpenShiftCredentials as a reguler built-in jenkins credentials,
I can't map api token from OpenShiftTokenCredentials to the variable. 

So, it's impossible to use this credential outside fo scope jenkins-client-plugin. 

Similar question was discussed here https://github.com/openshift/jenkins-client-plugin/issues/95
but unfortunatelly I didn't find any decent solution there.

**Comment by danielalejandrohc** [comment]
OpenShiftTokenCredentials  was ment to use for the Openshift plugin, If you need to use regular the token out of it why you don't use it as Secret Text?

**Comment by maxt** [comment]
Understand it. The point is that our huge pipeline partially uses jenkins-client-plugin for openshift deployment and partially - it uses ansible playbooks for the same task (k8s plugin). It would be really great to have the same credential for both approaches. Historically, it was custom OpenShiftTokenCredentials.

**Comment by akram** [comment]
@maxt the relevant option for your case as suggested is to use a k8s `Secret` which will be synced as a Credential in Jenkins as well. Then, you can both use it in your Jenkins pipeline and with your ansible script.

wdyt?

**Comment by maxt** [comment]
/close
> @maxt the relevant option for your case as suggested is to use a k8s `Secret` which will be synced as a Credential in Jenkins as well. Then, you can both use it in your Jenkins pipeline and with your ansible script.
> 
> wdyt?
I agree. I managed to negotiate for new bunch of credentials of type "Secret text" and it perfectly works for me.
