### ISSUE TITLE
List of DSL methods required

### ISSUE THREAD

**Issue by niconhum** [openshift/jenkins-client-plugin#367]
Good Day

Our current pipeline is using "OpenShift Pipeline Jenkins" plugin DSL [methods:](https://www.jenkins.io/doc/pipeline/steps/openshift-pipeline/)

After upgrading to Openshift4  we noticed Jenkins is now bundled with "OpenShift Client Jenkins Plugin". With the result that pipelines are now failing due methods not supported by the plugin anymore.

Can someone please guide me where to find the correlating/equivalent  DSL methods to use, in place of "OpenShift Pipeline Jenkins Plugin" ?

Example, in Openshift4 (with OpenShift Client Jenkins Plugin) the pipeline is now failing with errors like: `java.lang.NoSuchMethodError: No such DSL method 'openshiftVerifyBuild' and 'openshiftDeploy'` .

Thanks
Nic

**Comment by thikade** [comment]
Hi Nic,
have a look at https://github.com/jenkinsci/openshift-client-plugin#examples. There you will find a lots of examples for typical use-cases.
Regards,
Thomas

**Comment by akram** [comment]
thanks @thikade for replying. Indeed @niconhum I would advise the same.

/close
