### ISSUE TITLE
Argument was classified as an image, image~source, or loaded template reference but should be git repo

### ISSUE THREAD

**Issue by KiqoCode** [openshift/jenkins-client-plugin#374]
Hi,

We are trying to use openshift plugin for Jenkins and we have our own git repository, but using this url gives us the message "Argument was classified as an image, image~source, or loaded template reference" and errors, when it actually should be a git repo. Using a public repo at github works, but using our own local repo does not work.

Any ideas how to get around this so it classifies our own url as a git repo?

**Comment by KiqoCode** [comment]
`openshift.newApp( 'https://stash.tre.se/scm/itopstools/alerta-oc.git', '--source-secret=repo-at-bitbucket' )`
This is the step that's failing in jenkins, and what I understand is that it triggers a oc new-app command in the cluster..

And what we get is this:
```
ERROR: new-app returned an error;
{err=error: unable to load template file "https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc": error parsing https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc: error converting YAML to JSON: yaml: line 16: did not find expected <document start>
error: git ls-remote failed with: fatal: https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc/info/refs not valid: is this a git repository?;  local file access failed with: stat https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc"

Argument 'https://stash.tre.se/projects/ITOPSTOOLS/repos/alerta-oc' was classified as an image, image~source, or loaded template reference.
```
So it seems this is not recognized as a git repo by oc. So can we in the `openshift.newApp` command specify that this is actually a git repo? We know connection works between our cluster and this git repo atleast. The repo is BitBucket.

**Comment by thikade** [comment]
Try to get the `new-app` cmd working on the cmdline first, to fix the error(s).   
Use `oc new-app https://stash.tre.se/scm/itopstools/alerta-oc.git --source-secret=repo-at-bitbucket` and see what that gives you.  

On OCP v4.8 (and on all previous versions iirc), `oc new-app` will connect to the specified git repo and then tries to figure out which *type* of project is kept inside the repo (Java, NodeJS, ... ),  to determine the Source2Image *builder-image* to use in the BuildConfig.
Unfortunately new-app does not use the credentials given in the secret, but prompts for interactive authentication. So - that way it wont work from Jenkins pipeline. (Note, the *source-secret* is only used inside the generated Buildconfig!)

But you can override `new-app`'s behaviour by forcing it to use a S2I builder image using the tilde-syntax:  
eg: use the *httpd* builder image from Openshift:   
 `oc new-app httpd~https://stash.tre.se/scm/itopstools/alerta-oc.git --source-secret=repo-at-bitbucket` 
This should give you a few K8s/OCP manifests: Imagestream, BuildConfig, Deployment, Service

Personally, I would not use *new-app* inside a Jenkins pipeline. I would generate all required YAML manifests once and put them into Git. In my pipeline I would checkout that repo, then apply these YAMLs  ... but in the end that's your decision, and ymmv.

Regards
Thomas
