### ISSUE TITLE
Leftover oc processes after wait() calls

### ISSUE THREAD

**Issue by spasche** [openshift/jenkins-client-plugin#375]
Hello,

We are using OpenShift Client Jenkins Plugin version 1.0.35 together with Kubernetes plugin version 1.30.11 on an OKD cluster.

We noticed that when running `openshift.wait()` (also indirectly via `untilEach()`), the oc processes are kept running after the `wait` returns.
As the processes accumulate, the container memory is exhausted and commands terminate with exit codes 143.

Testcase:
```
podTemplate(containers: [
  containerTemplate(name: 'oc', image: 'quay.io/openshift/origin-cli:4.9', command: 'sleep', args: '99d')
  ]) {

  node(POD_LABEL) {
    container('oc') {
      openshift.withCluster() {
        def cm = openshift.create('cm', 'foo')
        cm.watch {
          return true
        }
        echo "List of processes"
        sh "sleep 10"
        sh "ps -efw"
      }
    }
  }
}
```

In the output, the oc process is still running:
```
UID          PID    PPID  C STIME TTY          TIME CMD
1000660+       1       0  0 15:01 ?        00:00:00 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 99d
1000660+      27       0  0 15:01 ?        00:00:00 sh
1000660+      34      27  2 15:01 ?        00:00:00 oc --server=https://kubernetes.default.svc.cluster.local --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt [...] get configmap/foo -w -o=name
```

Regards,
Sylvain

**Comment by akram** [comment]
Hi @spasche ,

can you help us investigate the issue by telling in which case you are falling:
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/OcWatch.java#L111

Based on what we have in the code, the return true is captured and normal exit code are also captured
https://github.com/openshift/jenkins-client-plugin/blob/78f1875db4300f088c5cb8ba625b00681763e507/src/main/java/com/openshift/jenkins/plugins/util/ClientCommandRunner.java#L24

?
