### ISSUE TITLE
adjust to underlying oc/openshift change in types returned on selectors

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-client-plugin#46]
When running jenkins-image-sample.groovy, we used to be able to run it multiple times within a jenkins instance.

However, there seems to have been a change in the underlying oc/openshift behavior.  I suspect, though have not precisely confirmed, from a quick grep of "deploymentconfigs" in the origin code base that it could be related to the recent API group changes.

When first creating the objs in jenkins-image-sample.groovy from the mongodb-ephemeral template, when iterating over the created objects, DCs are prefaced with the type "deploymentconfig/".  And the current jenkins-client-plugin code base works fine.

However, if you run the pipeline again, and we find existing objects (and hence don't create them), when we iterate over the objects from the selector, DCs are prefaced with "deploymentconfigs/" (note the 's' at the end on deploymentconfig), and the abbreviation mapping logic in OpenShiftDSL.groovy does not recognize the type and aborts.

Adjusting the abbreviation mapping from a 1-1 to a 1-many should be straight forward (though it will again tax my already tenuous feelings toward groovy I'm sure).

@bparees fyi

**Comment by bparees** [comment]
@deads2k @mfojtik

**Comment by gabemontero** [comment]
Regardless of the precise cause or when it occurred, my determination from my limited scan of what I've seen so far is that both say "deploymentconfig" and "deploymenconfigs" are valid and the plugin needs to tolerate it.

**Comment by deads2k** [comment]
Yes, it changed in 3.6. One of clayton's refactors did it, but since CLI tools have always been forced to support both it was deemed ok.
