### ISSUE TITLE
Checking if resource exists

### ISSUE THREAD

**Issue by nikolicjakov** [openshift/jenkins-client-plugin#49]
I am having a problem checking if resource exists before i delete it.
It would be good if you could implement method to do tasks like this.

```
def p = openshift.selector( 'hpa/myautoscaler' ).object()
if(p != null){openshift.selector( 'hpa/myautoscaler' ).delete()}
```

Right now when i try to execute first command to get the resource object it ends up failing my Jenkins pipeline build.

```
ERROR: Error during delete;
{reference={}, err=Error from server (NotFound): horizontalpodautoscalers.autoscaling "myautoscaler" not found, verb=delete, cmd=oc delete hpa/myautoscaler --insecure-skip-tls-verify --server=https://my.awsome.cluster --namespace=test --token=XXXXX , out=, status=1}
```

**Comment by gabemontero** [comment]
@nikolicjakov this was recently added as part of v0.9.4 of this plugin and is part of the latest openshift jenkins centos image on dockerhub

for a quick example, see https://github.com/openshift/jenkins-client-plugin/blob/master/examples/jenkins-image-sample.groovy#L13-L26

**Comment by rkrawiec** [comment]
I had a similar issue and even using .exists() method I am receiving an error when the resource does not exist.

`def bcSelector = openshift.selector("bc", "pas-groupsales-binary")
 def bcExists = bcSelector.exists()`

gives the error:

`ERROR: Unable to retrieve object names: selector([name=null],[labels=null],[list=[buildconfig/pas-groupsales-binary]]); action failed: {reference={}, err=Error from server: buildconfigs "pas-groupsales-binary" not found, verb=get, cmd=oc get buildconfig/pas-groupsales-binary -o=name --insecure-skip-tls-verify --server=removed --namespace=project-snd --token=XXXXX , out=, status=1}
Finished: FAILURE`

using version .0.9.5 of the plugin

**Comment by gabemontero** [comment]
@rkrawiec - your use case on the surface is just like our basic test case that runs each night.  See https://github.com/openshift/jenkins-client-plugin/blob/master/examples/jenkins-image-sample.groovy#L13-L15

I am unable to reproduce locally.

I've sometimes seen permission issues masked as not found issues.  Is it possible that serviceaccount jenkins is running under does not have the right authorization to the namespace `project-snd` ?

Otherwise, I will need you to reproduced this where you call `bcSelector.loglevel(8)` before calling `bcSelector.exists()`

thanks

**Comment by rkrawiec** [comment]
I should have been more clear, the error happens before the bcSelector.exists() executes. It occurs on the openshift.selector() call. I don't think its a permissions issue as we can successfully deploy when this logic is not in place and it does not error if the bc exists. I turned up logging on the openshift.selector() call but it produces a lot of logs that i would need to scrub before posting here. Is there part of those logs in particular you would like to see?

Below is the final response from the server in the logs:

`I0721 11:20:17.106504    5692 request.go:908] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"buildconfigs \"pas-groupsales-binary\" not found","reason":"NotFound","details":{"name":"pas-groupsales-binary","kind":"buildconfigs"},"code":404}
I0721 11:20:17.107505    5692 helpers.go:199] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "buildconfigs \"pas-groupsales-binary\" not found",
  "reason": "NotFound",
  "details": {
    "name": "pas-groupsales-binary",
    "kind": "buildconfigs"
  },
  "code": 404
}]`

**Comment by rkrawiec** [comment]
1. We are running a stand alone Jenkins instance outside OpenShift using oc tool version 3.4.1.2.
2. we are running OpenShift version 3.5.5.5

**Comment by gabemontero** [comment]
Yep, it is the 3.4 `oc`.  I can reproduce with that @rkrawiec 

Upgrade your `oc` to 3.5 and it should work.  It does for me.

We plan on removing the "experimental" tag on this plugin as part of the overall openshift 3.7 release.  When we do so, we'll make an official statement as to which minimum version of `oc` is required for this plugin.

thanks

**Comment by rkrawiec** [comment]
Thank you for your prompt assistance on this issue. I have requested the new version of the oc tool be installed and will update once I have rerun this scenario.

**Comment by gabemontero** [comment]
my pleasure - good luck

**Comment by rkrawiec** [comment]
Updating the oc tool to version 3.5 solved the issue, thanks!

**Comment by gabemontero** [comment]
cool!
