### ISSUE TITLE
Allow openshift methods to work with groovy strings and not just java strings

### ISSUE THREAD

**Issue by csrwng** [openshift/jenkins-client-plugin#5]
This fails:

```groovy
def name="foo"
def project="project-${name}"
openshift.raw('new-project', project)
```

while this works
```groovy
def name="foo"
def project="project-${name}"
openshift.raw('new-project', project.toString())
```

**Comment by csrwng** [comment]
When it fails, it's not very clear about why it failed.

**Comment by gabemontero** [comment]
I think groovy strings map to the java type GString.
Wonder if we can overload the raw method and any other methods to take
GString params and then do the toString call and call the version with
String params in those overloaded methods.

**Comment by gabemontero** [comment]
Interesting that merging the PR did not automatically close this issue since the "fixes ..." was included in the PR description.

I suppose I'll take that as an opportunity to not close this out until I've cut a new release of the plugin and updated the centos image.

**Comment by gabemontero** [comment]
the centos image update with this fix is in progress
