### ISSUE TITLE
openshift.process should support http(s) urls

### ISSUE THREAD

**Issue by coreydaley** [openshift/jenkins-client-plugin#63]
openshift.process should support http(s) urls by using the -f flag, similar to how openshift.(verb) works.

Code that needs to be fixed:
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L570-L604

Working example:
https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L523-L556

**Comment by gabemontero** [comment]
cool deal +1

and I get to teach you the PR testing process :-) .... ahhhh ahhhh ahhhhhhhhhhh (that was suppose to sound ominous)
