### ISSUE TITLE
OpenShift Generic OC Invocation cannot recognize parameters in jenkins project

### ISSUE THREAD

**Issue by eliu** [openshift/jenkins-client-plugin#69]
When I defined some parameter for my jenkins project. The plugin cannot recognize the parameter reference like ${MY_PARAMETER}

I use an `OpenShift Generic OC Invocation` plugin for one of build step.

Kindly help.

**Comment by gabemontero** [comment]
hey @eliu - this has come up before .... see https://github.com/openshift/jenkins-client-plugin/issues/22 for the detailed explanation what this plugin will tolerate wrt parameters

if you are still having trouble after adjusting your syntax, reopen, and we'll go from there

**Comment by eliu** [comment]
@gabemontero I think the reference you provide only works on Jenkins pipelines, not the case for a `free-style project`. I have tried all of the combining possibilities with no luck at all.

```
Started by user admin
Building in workspace /var/lib/jenkins/jobs/param_test/workspace
Executing: oc ${env.WORKSPACE}  --server=https://172.30.0.1:443 --namespace=ci --token=XXXXX 
Error: unknown command "${env.WORKSPACE}" for "oc"
Run 'oc --help' for usage.
Client tool terminated with status: 1
Build step 'OpenShift - Generic OC Invocation' marked build as failure
Finished: FAILURE
```
```
Started by user admin
Building in workspace /var/lib/jenkins/jobs/param_test/workspace
Executing: oc ${params.MY_PARAM}  --server=https://172.30.0.1:443 --namespace=ci --token=XXXXX 
Error: unknown command "${params.MY_PARAM}" for "oc"
Run 'oc --help' for usage.
Client tool terminated with status: 1
Build step 'OpenShift - Generic OC Invocation' marked build as failure
Finished: FAILURE
```

**Comment by eliu** [comment]
@gabemontero and i guess the following link have better instructions about how to use this `paramterized build` feature. And now i wonder if this feature can be supported by the `OpenShift Client` plugin itself.

https://wiki.jenkins.io/display/JENKINS/Parameterized+Build

**Comment by gabemontero** [comment]
@eliu yeah after completing your other issue I realized I may have misinterpreted this one.  The rules and/or what the plugin has to do can vary with freestyle.

I thought we migrated what was done with openshift pipeline plugin for this one but will take a look and report back.

**Comment by gabemontero** [comment]
Yep we did *NOT* migrate the param substitution logic.  I'll start working a change.

**Comment by eliu** [comment]
Good to know. I'll be waiting for the next update of the plugin :)

**Comment by eliu** [comment]
@gabemontero Sorry to interrupt, but i have still not receive an further update of this jenkins client plugin from Jenkins plugin management center. Is there anything else that need to proceed to make the update available?
