### ISSUE TITLE
Command and argument disappeared when re-config jenkins project

### ISSUE THREAD

**Issue by eliu** [openshift/jenkins-client-plugin#70]
I create a build step using `OpenShift Generic OC Invocation` plugin in my jenkins plugin and saved without problems. But the command line options and arguments field `DISAPPEARED` when i come back to configuration user interface to make some changes.

Kindly help!

**Comment by gabemontero** [comment]
yep I was able to reproduce this  ... yeah, most of the usage of this plugin has been with pipelines vs. freestyle steps

**Comment by gabemontero** [comment]
v1.0.2 of the client plugin has been cut

https://github.com/openshift/jenkins/pull/412 will update the openshift jenkin centos image

**Comment by gabemontero** [comment]
will post associated rhel job when ready

**Comment by gabemontero** [comment]
associated rhel plugin update:  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/9/

**Comment by eliu** [comment]
I noticed a plugin update and now it works perfectly. thanks for help!
