### ISSUE TITLE
Provide Example on how to configure the plugin via groovy

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-client-plugin#78]
It would be great if you could provide a guide on how to configure the plugin via Groovy (for automation with puppet/chef/ansible). 

This should include:

* Configuring Openshift Clusters
* Configuring Openshift Client Tools (basic example below)
* Configuring Openshift Tokens (basic example below)

Something like this https://github.com/samrocketman/jenkins-bootstrap-slack/blob/master/scripts/configure-slack.groovy

**Comment by elconas** [comment]
For Openshift Client Tools this seems to work:

```groovy
import jenkins.*
import jenkins.model.*
import hudson.*
import hudson.model.*
import com.openshift.jenkins.plugins.OpenShiftClientTools

def a = Jenkins.instance.getDescriptor("com.openshift.jenkins.plugins.OpenShiftClientTools");
def existing = a.installations as List;
existing.add(new com.openshift.jenkins.plugins.OpenShiftClientTools('oc', '/usr/local/bin', []));
a.setInstallations(existing as com.openshift.jenkins.plugins.OpenShiftClientTools[])
a.save()
```

**Comment by elconas** [comment]
For Credentials this seems to work:

```groovy
import hudson.util.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.domains.*
import com.openshift.jenkins.plugins.OpenShiftTokenCredentials

def credentials_store = Jenkins.instance.getExtensionList(
        'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
        )[0].getStore()

def credential = new OpenShiftTokenCredentials(
  CredentialsScope.GLOBAL,
  'mytokenid',
  'this is a openshift token',
  new Secret('thetoken')
)

credentials_store.addCredentials(Domain.global(), credential)
```

However I had a hard time getting anything to work with the openshift cluster config ... StaplerRequest etc ....

**Comment by gabemontero** [comment]
thanks for the input @elconas 

at first blush I agree it would be a good thing to have

Given our process wrt enhancement, I'm closing this issue out in favor of trello card https://trello.com/c/40z9fXkl/1413-jenkinsintegration-provide-example-on-how-to-configure-the-plugin-via-groovy

If you are interest in monitoring the progress there, register on trello and subscribe to the card.

thanks again

@openshift/sig-developer-experience fyi
