### ISSUE TITLE
Add support for "oc rsh"

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-client-plugin#79]
It seems that "oc rsh" is not working with the```openshift.raw()``` interface of the plugin: 

Pipeline:

```
node {
  def ocDir = tool "oc"
  withEnv(["PATH+OC=${ocDir}"]) {
  openshift.withCluster('minishift') {
    openshift.withProject('myproject') {
      echo "HELLO FROM ${openshift.project()}"
      echo openshift.raw('version').out
      echo openshift.raw('get','pod', 'petclinic2-3-hjx72').out
      echo openshift.raw("rsh","petclinic2-3-hjx72","hostname").out
    }
  }
  }
}
```

I get the following:

```
Started by user admin
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/openshift-test
[Pipeline] {
[Pipeline] tool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] echo

[Pipeline] _OcContextInit
[Pipeline] _OcContextInit
[Pipeline] echo
HELLO FROM myproject
[Pipeline] _OcAction
[Pipeline] echo
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxx.xxx.xxx.xxx:8443/
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

[Pipeline] _OcAction
[Pipeline] echo
NAME                 READY     STATUS    RESTARTS   AGE
petclinic2-3-hjx72   1/1       Running   4          39d

[Pipeline] _OcAction
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: raw command [rsh, petclinic2-3-hjx72, hostname] returned an error;
{reference={}, err=Error from server (NotFound): pods "petclinic2-3-hjx72" not found, verb=, cmd=oc  rsh petclinic2-3-hjx72 hostname --insecure-skip-tls-verify --server=https://xxx.xxx.xxx.xxx:8443/ --namespace=myproject --token=XXXXX , out=, status=1}

Finished: FAILURE
```

**Comment by gabemontero** [comment]
Yeah not 100% sure yet if this is to be expected or not.  This could either fall into a "document restriction, open trello/feature card to provide", or a "add explicit verb for rsh and perform the necessary massaging of stdout/stdin/etc. to allow it to work"

**Comment by bparees** [comment]
does oc exec work?

**Comment by gabemontero** [comment]
An explicit exec verb was originally put into the plugin.  I personally have not tested it yet.  But my suspicion is that some difference between the raw and explicit verb processing may be at the root here.  Or something in oc has changed since the plugin was first created and the plugin needs to adjust.

**Comment by elconas** [comment]
I tested with exec and it works, thanks:

```
echo "Reported Hostname" + openshift.exec(shortname,'hostname').out
```

However it is rather difficult to execute more complex commands with exec (e.g. scripts, loops and pipes (ps ax | grep ...)). So I came up with this workaround unless rsh may be available:

```
          sh "echo 'echo provisioning now ...' > provision_script"
          openshift.raw("cp","provision_script","${shortname}:/tmp/provision_script")
          echo openshift.exec(shortname,'bash', '/tmp/provision_script').out
```
I get the pod names with: 
```
      def pods = dcs.related('pods')
      pods.withEach { p -> 
        p.names().each { podname ->
           // podname is now pods/xxx-xxx-xxx
          shortname = podname.replaceAll('pods/', "")
           // podname is now xxx-xxx-xxx
           // .... do something with it
        }
     }
```
Maybe there is a better way to get the short names of the pods created.

**Comment by gabemontero** [comment]
OK, got around to trying this out.  For me, it appears to be the ordering of the args with oc rsh that messes things up.  The version of oc may have some bearing as well.

The key was to insert some of the args the plugin inserts for server url, project name, etc.

If the `--` args precede `oc rsh`, it works.  If they are appended, it fails:

```
gmontero ~ $ oc --server=https://172.30.0.1:443 --namespace=myproject  rsh jenkins-1-8h6bb hostname
jenkins-1-8h6bb
gmontero ~ $ oc  rsh jenkins-1-8h6bb hostname  --server=https://172.30.0.1:443 --namespace=myproject
hostname: unrecognized option '--server=https://172.30.0.1:443'
Usage: hostname [-b] {hostname|-F file}         set host name (from file)
```

The same things hold when using the plugin in a pipeline.

Note though that the error I got was slightly different than the error @elconas got.  If you have the time @elconas I would be curious of your results using the 3.6 `oc` from the command line where you insert --server and --namespace in the same fashion I did.  I don't have one handy but can pull one down and try 
if you don't have the time when I get an additional moment or two.

Short term though, I'm going to add a first class `rsh` step that will get the parameter ordering correct for the latest (3.7) `oc`, and we'll go from there.

**Comment by gabemontero** [comment]
I think in general if the `--` args precede the verb for `oc` things look happy so I may make that general changes as well for any other verbs passed into `raw()`

**Comment by gabemontero** [comment]
On pod short names, this will get you the short name:

```
dcs.related('pods').withEach {
   shortname = it.object().metadata.name
}
```

**Comment by gabemontero** [comment]
@elconas - I should be cutting a new version of the client plugin in the next day or so ... I believe v1.0.3 will have this fix

if you can take hand built plugins let me know and I'll provide a pre-release version for you

**Comment by elconas** [comment]
Hello, I tested the code:
```
run -it --rm -v $(pwd):/jenkins-plugin -v $(pwd)/../.m2:/root/.m2 -w /jenkins-plugin maven:latest mvn package
```
Installed the plugin, however some commands still fail:

Pipeline Code:
```
  echo openshift.rsh(shortname,"ps ax").out
```
Result:

```
ERROR: rsh returned an error;
{reference={}, err=error: unknown gnu long option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
command terminated with exit code 1, verb=rsh, cmd=oc --server=https://xxx.xxx.xxx.xxx:8443/ --namespace=myproject --token=XXXXX rsh centos7-im0t0k1k-1-62s9v ps ax --insecure-skip-tls-verify , out=, status=1}
```
It seems you you have to move ALL --param params in front of the command.

This works:

Pipeline:
```
echo openshift.rsh(shortname,"echo").out
```
Result:
```
[Pipeline] _OcAction
[Pipeline] echo
--insecure-skip-tls-verify
```

**Comment by elconas** [comment]
Will Create another issue for this
