### ISSUE TITLE
new oc rsh parially broken

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-client-plugin#82]
Hello, I tested the code introduced by https://github.com/openshift/jenkins-client-plugin/pull/81 and ran into an issue

```
run -it --rm -v $(pwd):/jenkins-plugin -v $(pwd)/../.m2:/root/.m2 -w /jenkins-plugin maven:latest mvn package
```
Installed the plugin, however some commands still fail:

Pipeline Code:
```
  echo openshift.rsh(shortname,"ps ax").out
```
Result:

```
ERROR: rsh returned an error;
{reference={}, err=error: unknown gnu long option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
command terminated with exit code 1, verb=rsh, cmd=oc --server=https://xxx.xxx.xxx.xxx:8443/ --namespace=myproject --token=XXXXX rsh centos7-im0t0k1k-1-62s9v ps ax --insecure-skip-tls-verify , out=, status=1}
```
It seems you you have to move ALL --param params in front of the command.

This works:

Pipeline:
```
echo openshift.rsh(shortname,"echo").out
```
Result:
```
[Pipeline] _OcAction
[Pipeline] echo
--insecure-skip-tls-verify
```

**Comment by gabemontero** [comment]
Thanks for giving turning around so quickly and giving the last change a go @elconas 

Per discussion with @bparees assigning to @coreydaley 

@coreydaley - see https://github.com/openshift/jenkins-client-plugin/pull/81 for background; I suspect what happened was that `--insecure-skip-tls-verify` is added elsewhere from the java file I modified in the pull (perhaps OpenShiftDSL.groovy), and hence still append that arg vs. prepend.

Also, I did confirm that `ps ax` works when executed at least in say a OpenShift Jenkins image pod.  I'm assuming it also works in the the pod @elconas was referencing.
