### ISSUE TITLE
How to verify deployment ?

### ISSUE THREAD

**Issue by arnaud-deprez** [openshift/jenkins-client-plugin#84]
Hi,

With https://github.com/openshift/jenkins-plugin, you can use the helper step `openshiftVerifyDeployment` to check wether the deployment actually full fit our specs. It's easy.

So how to do the same thing with Openshift client ?

For a build, the status is well expressed, we are waiting the build to be `Completed` and if so it means the build finish with success.
There is no such status for Deployment making it harder to verify.

Regards,

**Comment by gabemontero** [comment]
@arnaud-deprez - you should be able to create a watch (i.e. https://github.com/openshift/jenkins-client-plugin#watching-and-waiting-of-course) on the replication controller to determine the status, where you determine the correct RC from the DC.  That is what the old plugin does.

If you are able to infer the right scriptlet from the doc, great, let us know.  Otherwise, @coreydaley can help with constructing a precise example (and perhaps updating our watch example) 

@bparees fyi

**Comment by coreydaley** [comment]
@arnaud-deprez Here is an example of checking to make sure that the deployment is completed, you will need to check that status.phase == "Running"
https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/nodejs-sample-pipeline.yaml#L55-L65

**Comment by gabemontero** [comment]
On Fri, Nov 17, 2017 at 12:45 PM, Corey Daley <notifications@github.com>
wrote:

> @arnaud-deprez <https://github.com/arnaud-deprez> Here is an example of
> checking to make sure that the deployment is completed, you will need to
> check that status.phase == "Running"
> https://github.com/openshift/origin/blob/master/examples/
> jenkins/pipeline/nodejs-sample-pipeline.yaml#L55-L65
>

Ah forgot about your new sample @coreydaley :-) ... yep, you can check the
pods directly too in lieu of the replication controllers.

Yeah, perhaps adding this as a blurb in the readme's watch section would be
good too.

**Comment by arnaud-deprez** [comment]
Hi,

Thanks for the example but it does not really work.
When you perform a ‘Recreate rolling update’, at the time you check the dc/pod status, it will match 99% time the old pods because it is not yet stopped.

I could use a combination of watch to wait the deployment is complete and then check the dc/pods status. But what if I plan to scale 10 pods but I want to be sure there is at least one new running instance without waiting the whole deployment to complete ?

**Comment by gabemontero** [comment]
On Fri, Nov 17, 2017 at 3:07 PM, Arnaud Deprez <notifications@github.com>
wrote:

> Hi,
>
> Thanks for the example but it does not really work.
> When you perform a ‘Recreate rolling update’, at the time you check the
> dc/pod status, it will match 99% time the old pods because it is not yet
> stopped.
>
> I could use a combination of watch to wait the deployment is complete and
> then check the dc/pods status. But what if I plan to scale 10 pods but I
> want to be sure there is at least one new running instance without waiting
> the whole deployment to complete ?
>
Yeah that may be where we have to leverage the Replication Controller vs.
the Pod like the old pipeline does.

The relevant code in that plugin (though it calls some methods defined in
IOpenShiftPlugin.java) is
https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftDeploymentVerification.java#L59-L161

@coreydaley - see if you can construct a an analogous client plugin dsl
groovy script that mimics that logic

**Comment by tomcooperca** [comment]
For a new deployment of a single-container pod, we use following selectors & fields on the pod to verify deployments:

```Groovy
def module = 'app-a'
def dcObj = openshift.selector('dc', module).object()
def podSelector = openshift.selector('pod', [deployment: "${module}-${dcObj.status.latestVersion}"])
podSelector.untilEach {
    echo "pod: ${it.name()}"
    return it.object().status.containerStatuses[0].ready
}
```
Obviously, this won't work if your DeploymentConfig contains multiple containers.

**Comment by ramato-procon** [comment]
I do it this way:

``

**Comment by gabemontero** [comment]
@coreydaley - per my comment at https://github.com/openshift/jenkins-client-plugin/issues/84#issuecomment-345319952 let's use this bug to minimally document some of the best flavors for this.

As a follow on, this notion I think would make the perfect guinea pig for this plugin crafter a pipeline "global library" of common combination of various primitives of this plugin to achieve results that most users would find useful.

I need to get a card opened for the gloabl lib piece ... I know I've discussed with @csrwng and @bparees in the past.

**Comment by arnaud-deprez** [comment]
@gabemontero that's exactly what I liked in the deprecated openshift client plugin. However, the cons of the old plugin is that it was hard to perform more fine grained tasks and that's why most of the time we end up using `oc ...` command.

So definetely, having a high level library for common use case and best practices would provide more power :-)

**Comment by sherl0cks** [comment]
I want spelunking around in the code of the old plugin, here is the equivalent procedure from the old plugin with this new one. It doesn't have all the switches, but it gets the job done. I will open a docs PR shortly. 

I'd be very keen to contribute to a https://jenkins.io/doc/book/pipeline/shared-libraries/ if we set one up. There is https://github.com/fabric8io/fabric8-pipeline-library, but it does a ton of stuff. I'd be a fan of a smaller, more focused library, but that prob warrants a discussion with the fabric8 folks.

```
def latestDeploymentVersion = openshift.selector('dc',"${APP_NAME}").object().status.latestVersion
def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
rc.untilEach(1){
    def rcMap = it.object()
    return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
}
```

**Comment by gabemontero** [comment]
Thanks @sherl0cks ! ... such a foray was exactly what I was referring to in https://github.com/openshift/jenkins-client-plugin/issues/84#issuecomment-345364902

And agreed on your shared libs perspective.  Just a question on how it gets prioritized for my team...though I was looking for the trello card I was sure we had opened for this, and now I can't find it.

In the interim I've created https://trello.com/c/iQr3XsF8/1543-start-up-a-set-of-pipeline-global-libraries-for-common-client-plugin-patterns-pipelineintegration

we can close it as a dup if needed.

**Comment by igorfraa** [comment]
[@tomcooperca ](https://github.com/openshift/jenkins-client-plugin/issues/84#issuecomment-358351758)

For the second example, .objects().untilEach() didn't worked for me. It said "`No signature of method: ArrayList.untilEach() is applicable for argument types org.jenkinsci.<...>.CpsClosure2`".

I have modified it as follows:
```
timeout(5) {
    def numPods = 1
    def dcSelector = openshift.selector('dc', 'myapp')
    def deployment = "myapp-${dcSelector.object().status.latestVersion}"
    def podSelector = openshift.selector('pods', [deployment: "${deployment}"])
    podSelector.untilEach(numPods) {    // at least <numPods> is ready
        return it.object().status.containerStatuses.every {  //containerStatuses are an array of statuses for multi-container dc; check if all of them are ready
            it.ready 
        }
    }
}
```
