### ISSUE TITLE
Security: deny token retrieval

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-client-plugin#88]
Hello, 
right now you can use the following to retrieve the jenkins encrypted token:

```
openshift.raw("whoami","-t")
```
This should be blocked by the plugin to disable easy leakage of token information

**Comment by bparees** [comment]
you can also use "sh 'oc whoami -t'", this isn't something the plugin can protect you from.

**Comment by elconas** [comment]
Well the token is not stored in the .kube/config by the plugin, but explicitly provided by --roken=xxx or is it ?

**Comment by bparees** [comment]
The jenkins container has an openshift service account associated with it.  That is the token you are seeing when you run oc whoami -t  (unless you have setup other credentials).

The assumption is anyone who has permission to create/edit jobs on your jenkins server, already has meaningful permissions within your cluster.  (after all, even if they can't get the token, you've allowed them to run oc operations with the token, that's the entire role of the openshift client plugin).

**Comment by bparees** [comment]
again, no different from sh 'oc config view'.

**Comment by elconas** [comment]
Ok. So if this is intended "by design" it should be properly documented (e.g. global credentials at the cluster level, meaning everyone peforming git commits in any repo built ona Jenkins Server can steal jenkins credentials).

**Comment by bparees** [comment]
> meaning everyone peforming git commits in any repo built ona Jenkins Server can steal jenkins credentials

it does not mean that.  that is only the case if those users have permission to view your jenkins job logs *and* your jenkins job for some reason runs commands that print out the token.

Neither of those are prerequisites to having a CI system that builds/tests git commits by random users.
